<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see AdditionalMeasures}.
 */
final class AdditionalMeasuresBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<float>            $quantity
     * @param Option<string>           $units
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $quantity, private Option $units, private array $additionalProperties)
    {
    }

    /**
     * Specify commodity quantity.
     */
    public function setQuantity(float $quantity): self
    {
        $this->quantity = Some::create($quantity);

        return $this;
    }

    /**
     * Unit of measure used to express the quantity of this commodity line item.
     */
    public function setUnits(string $units): self
    {
        $this->units = Some::create($units);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): AdditionalMeasures
    {
        return new AdditionalMeasures($this->quantity, $this->units, $this->additionalProperties);
    }
}
