<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_int;
use function is_string;
use function sprintf;

final readonly class AdditionalLabelsDetail implements SelfNormalizingModel
{
    /**
     * @param Option<AdditionalLabelsDetailType|UnknownEnumValue<string>> $type
     * @param Option<int>                                                 $count
     * @param array<int|string, mixed>                                    $additionalProperties
     */
    public function __construct(private Option $type, private Option $count, private array $additionalProperties)
    {
    }

    public static function builder(): AdditionalLabelsDetailBuilder
    {
        return new AdditionalLabelsDetailBuilder(None::create(), None::create(), []);
    }

    /**
     * Specify the type of additional details to be added on the label.
     *
     * Example:MANIFEST
     *
     * @return Option<AdditionalLabelsDetailType|UnknownEnumValue<string>>
     */
    public function getType(): Option
    {
        return $this->type;
    }

    /**
     * Specifies the count of label to return.
     *
     * Example:1
     *
     * @return Option<int>
     */
    public function getCount(): Option
    {
        return $this->count;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $type = None::create();
        $count = None::create();
        if (array_key_exists('type', $data) && $data['type'] !== null) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = Some::create(AdditionalLabelsDetailType::tryFrom($typeRaw) ?? UnknownEnumValue::of($typeRaw));
        }
        if (array_key_exists('count', $data) && $data['count'] !== null) {
            $countRaw = $data['count'];
            if (!is_int($countRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "count" must be int, got %s.', get_debug_type($countRaw)),
                );
            }
            $count = Some::create($countRaw);
        }
        $additionalProperties = array_diff_key($data, ['type' => true, 'count' => true]);

        return new self($type, $count, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $typeOption = $this->type;
        if ($typeOption->isDefined()) {
            $type = $typeOption->get();
            $dataArray['type'] = $type->value;
        }
        $countOption = $this->count;
        if ($countOption->isDefined()) {
            $count = $countOption->get();
            $dataArray['count'] = $count;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): AdditionalLabelsDetailBuilder
    {
        return new AdditionalLabelsDetailBuilder($this->type, $this->count, $this->additionalProperties);
    }
}
