<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class AncillaryFeeAndTax implements SelfNormalizingModel
{
    /**
     * @param Option<AncillaryFeeAndTaxType|UnknownEnumValue<string>> $type
     * @param Option<string>                                          $description
     * @param Option<Money1>                                          $amount
     * @param array<int|string, mixed>                                $additionalProperties
     */
    public function __construct(
        private Option $type,
        private Option $description,
        private Option $amount,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): AncillaryFeeAndTaxBuilder
    {
        return new AncillaryFeeAndTaxBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Identifies the total amount of the shipment-level fees and taxes that are not based on
     * transportation charges or commodity-level estimated duties and taxes.
     *
     * @return Option<AncillaryFeeAndTaxType|UnknownEnumValue<string>>
     */
    public function getType(): Option
    {
        return $this->type;
    }

    /**
     * Identifies the amount of the shipment-level fees and taxes that are not based on
     * transportation charges or commodity-level estimated duties and taxes.
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * list of AncillaryFees And Taxes.
     *
     * @return Option<Money1>
     */
    public function getAmount(): Option
    {
        return $this->amount;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $type = None::create();
        $description = None::create();
        $amount = None::create();
        if (array_key_exists('type', $data) && $data['type'] !== null) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = Some::create(AncillaryFeeAndTaxType::tryFrom($typeRaw) ?? UnknownEnumValue::of($typeRaw));
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        if (array_key_exists('amount', $data) && $data['amount'] !== null) {
            $amountRaw = $data['amount'];
            if (!is_array($amountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "amount" must be object, got %s.', get_debug_type($amountRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $amountRawTyped */
            $amountRawTyped = $amountRaw;
            $amount = Some::create(Money1::fromArray($amountRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['type' => true, 'description' => true, 'amount' => true]);

        return new self($type, $description, $amount, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $typeOption = $this->type;
        if ($typeOption->isDefined()) {
            $type = $typeOption->get();
            $dataArray['type'] = $type->value;
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $description;
        }
        $amountOption = $this->amount;
        if ($amountOption->isDefined()) {
            $amount = $amountOption->get();
            $dataArray['amount'] = $normalizationTarget->model($amount);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): AncillaryFeeAndTaxBuilder
    {
        return new AncillaryFeeAndTaxBuilder(
            $this->type,
            $this->description,
            $this->amount,
            $this->additionalProperties,
        );
    }
}
