<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see BillingDetails}.
 */
final class BillingDetailsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $billingCode
     * @param Option<string>           $billingType
     * @param Option<string>           $aliasId
     * @param Option<string>           $accountNickname
     * @param Option<string>           $accountNumber
     * @param Option<string>           $accountNumberCountryCode
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $billingCode,
        private Option $billingType,
        private Option $aliasId,
        private Option $accountNickname,
        private Option $accountNumber,
        private Option $accountNumberCountryCode,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicates a billing code.
     */
    public function setBillingCode(string $billingCode): self
    {
        $this->billingCode = Some::create($billingCode);

        return $this;
    }

    /**
     * These are duties and taxes billing type.
     */
    public function setBillingType(string $billingType): self
    {
        $this->billingType = Some::create($billingType);

        return $this;
    }

    /**
     * This is bill to alias identifier.
     */
    public function setAliasId(string $aliasId): self
    {
        $this->aliasId = Some::create($aliasId);

        return $this;
    }

    /**
     * This is account nick name.
     */
    public function setAccountNickname(string $accountNickname): self
    {
        $this->accountNickname = Some::create($accountNickname);

        return $this;
    }

    /**
     * This is bill to account number.
     */
    public function setAccountNumber(string $accountNumber): self
    {
        $this->accountNumber = Some::create($accountNumber);

        return $this;
    }

    /**
     * This is the country code of the account number.
     *
     * Example: CA
     */
    public function setAccountNumberCountryCode(string $accountNumberCountryCode): self
    {
        $this->accountNumberCountryCode = Some::create($accountNumberCountryCode);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): BillingDetails
    {
        return new BillingDetails(
            $this->billingCode,
            $this->billingType,
            $this->aliasId,
            $this->accountNickname,
            $this->accountNumber,
            $this->accountNumberCountryCode,
            $this->additionalProperties,
        );
    }
}
