<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class BrokerDetailBroker implements SelfNormalizingModel
{
    /**
     * @param Option<PartyAccountNumber>           $accountNumber
     * @param Option<list<TaxpayerIdentification>> $tins
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private PartyAddress $address,
        private PartyContact $contact,
        private Option $accountNumber,
        private Option $tins,
        private array $additionalProperties,
    ) {
    }

    public static function builder(PartyAddress $address, PartyContact $contact): BrokerDetailBrokerBuilder
    {
        return new BrokerDetailBrokerBuilder($address, $contact, None::create(), None::create(), []);
    }

    /**
     * Specifies broker address details.
     */
    public function getAddress(): PartyAddress
    {
        return $this->address;
    }

    /**
     * Specifies broker contact details.
     */
    public function getContact(): PartyContact
    {
        return $this->contact;
    }

    /**
     * This is FedEx Account number details.
     *
     * @return Option<PartyAccountNumber>
     */
    public function getAccountNumber(): Option
    {
        return $this->accountNumber;
    }

    /**
     * This is the tax identification number details.
     *
     * @return Option<list<TaxpayerIdentification>>
     */
    public function getTins(): Option
    {
        return $this->tins;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $address = null;
        $contact = null;
        $accountNumber = None::create();
        $tins = None::create();
        if (array_key_exists('address', $data)) {
            $addressRaw = $data['address'];
            if (!is_array($addressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "address" must be object, got %s.', get_debug_type($addressRaw)),
                );
            }
            /** @var array<string, mixed> $addressRawTyped */
            $addressRawTyped = $addressRaw;
            $address = PartyAddress::fromArray($addressRawTyped);
        }
        if (array_key_exists('contact', $data)) {
            $contactRaw = $data['contact'];
            if (!is_array($contactRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "contact" must be object, got %s.', get_debug_type($contactRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $contactRawTyped */
            $contactRawTyped = $contactRaw;
            $contact = PartyContact::fromArray($contactRawTyped);
        }
        if (array_key_exists('accountNumber', $data) && $data['accountNumber'] !== null) {
            $accountNumberRaw = $data['accountNumber'];
            if (!is_array($accountNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "accountNumber" must be object, got %s.', get_debug_type($accountNumberRaw)),
                );
            }
            /** @var array<string, mixed> $accountNumberRawTyped */
            $accountNumberRawTyped = $accountNumberRaw;
            $accountNumber = Some::create(PartyAccountNumber::fromArray($accountNumberRawTyped));
        }
        if (array_key_exists('tins', $data) && $data['tins'] !== null) {
            $tinsRaw = $data['tins'];
            if (!(is_array($tinsRaw) && array_is_list($tinsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "tins" must be list, got %s.', get_debug_type($tinsRaw)),
                );
            }
            $tins = Some::create(array_map(static function (mixed $value): TaxpayerIdentification {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return TaxpayerIdentification::fromArray($valueTyped);
            }, $tinsRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['address' => true, 'contact' => true, 'accountNumber' => true, 'tins' => true],
        );
        if ($address === null) {
            throw new MalformedDataException('Required property "address" is missing from the document.');
        }
        if ($contact === null) {
            throw new MalformedDataException('Required property "contact" is missing from the document.');
        }

        return new self($address, $contact, $accountNumber, $tins, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['address'] = $normalizationTarget->model($this->address);
        $dataArray['contact'] = $normalizationTarget->model($this->contact);
        $accountNumberOption = $this->accountNumber;
        if ($accountNumberOption->isDefined()) {
            $accountNumber = $accountNumberOption->get();
            $dataArray['accountNumber'] = $normalizationTarget->model($accountNumber);
        }
        $tinsOption = $this->tins;
        if ($tinsOption->isDefined()) {
            $tins = $tinsOption->get();
            $values = [];
            foreach ($tins as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['tins'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): BrokerDetailBrokerBuilder
    {
        return new BrokerDetailBrokerBuilder(
            $this->address,
            $this->contact,
            $this->accountNumber,
            $this->tins,
            $this->additionalProperties,
        );
    }
}
