<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class ClearanceItemDetailContact implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $companyName
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $companyName, private array $additionalProperties)
    {
    }

    public static function builder(): ClearanceItemDetailContactBuilder
    {
        return new ClearanceItemDetailContactBuilder(None::create(), []);
    }

    /**
     * Legal name of the manufacturer of the commodity.
     *
     * @return Option<string>
     */
    public function getCompanyName(): Option
    {
        return $this->companyName;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $companyName = None::create();
        if (array_key_exists('companyName', $data) && $data['companyName'] !== null) {
            $companyNameRaw = $data['companyName'];
            if (!is_string($companyNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "companyName" must be string, got %s.', get_debug_type($companyNameRaw)),
                );
            }
            $companyName = Some::create($companyNameRaw);
        }
        $additionalProperties = array_diff_key($data, ['companyName' => true]);

        return new self($companyName, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $companyNameOption = $this->companyName;
        if ($companyNameOption->isDefined()) {
            $companyName = $companyNameOption->get();
            $dataArray['companyName'] = $companyName;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ClearanceItemDetailContactBuilder
    {
        return new ClearanceItemDetailContactBuilder($this->companyName, $this->additionalProperties);
    }
}
