<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum CODTransportationChargesDetailChargeLevelType: string
{
    case CURRENT_PACKAGE = 'CURRENT_PACKAGE';
    case SUM_OF_PACKAGES = 'SUM_OF_PACKAGES';
}
