<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class CommercialInvoice implements SelfNormalizingModel
{
    /**
     * @param Option<string>                                                                   $originatorName
     * @param Option<string>                                                                   $paymentTerms
     * @param Option<list<string>>                                                             $comments
     * @param Option<list<CustomerReference>>                                                  $customerReferences
     * @param Option<Money>                                                                    $taxesOrMiscellaneousCharge
     * @param Option<CommercialInvoiceTaxesOrMiscellaneousChargeType|UnknownEnumValue<string>> $taxesOrMiscellaneousChargeType
     * @param Option<Money>                                                                    $freightCharge
     * @param Option<Money>                                                                    $packingCosts
     * @param Option<Money>                                                                    $handlingCosts
     * @param Option<string>                                                                   $declarationStatement
     * @param Option<string>                                                                   $termsOfSale
     * @param Option<string>                                                                   $specialInstructions
     * @param Option<CommercialInvoiceShipmentPurpose|UnknownEnumValue<string>>                $shipmentPurpose
     * @param Option<ShipEmailDispositionDetail>                                               $emailNotificationDetail
     * @param array<int|string, mixed>                                                         $additionalProperties
     */
    public function __construct(
        private Option $originatorName,
        private Option $paymentTerms,
        private Option $comments,
        private Option $customerReferences,
        private Option $taxesOrMiscellaneousCharge,
        private Option $taxesOrMiscellaneousChargeType,
        private Option $freightCharge,
        private Option $packingCosts,
        private Option $handlingCosts,
        private Option $declarationStatement,
        private Option $termsOfSale,
        private Option $specialInstructions,
        private Option $shipmentPurpose,
        private Option $emailNotificationDetail,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): CommercialInvoiceBuilder
    {
        return new CommercialInvoiceBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The originatorName that will populate the Commercial Invoice (or Pro Forma).
     *
     * Example: originator name
     *
     * @return Option<string>
     */
    public function getOriginatorName(): Option
    {
        return $this->originatorName;
    }

    /**
     * The payment terms that will populate the Commercial Invoice (or Pro Forma). This field is
     * being supported for completeness only.
     *
     * Example: payment terms
     *
     * @return Option<string>
     */
    public function getPaymentTerms(): Option
    {
        return $this->paymentTerms;
    }

    /**
     * The comments that will populate the Commercial Invoice (or Pro Forma). Only the comments
     * specified in the first two indexes of the array will be printed on the invoice and other
     * comments would be ignored as the limitation is set for only two indexes. It considers the
     * comment which is in the first index as a Special Instructions, Hence the comment at first
     * index will be printed under special instructions and the other will be printed at comments
     * section in the Commercial Invoice Document.
     *
     * Example: comments
     *
     * @return Option<list<string>>
     */
    public function getComments(): Option
    {
        return $this->comments;
    }

    /**
     * These are additional customer reference data.
     *
     * Note: The groupPackageCount must be specified to retrieve customer references.
     *
     * @return Option<list<CustomerReference>>
     */
    public function getCustomerReferences(): Option
    {
        return $this->customerReferences;
    }

    /**
     * Indicate the taxes or miscellaneous charges(other than freight charges or insurance charges)
     * that are associated with the shipment.
     *
     * @return Option<Money>
     */
    public function getTaxesOrMiscellaneousCharge(): Option
    {
        return $this->taxesOrMiscellaneousCharge;
    }

    /**
     * Specifies the Taxes Or Miscellaneous Charge Type.
     *
     * Example: COMMISSIONS
     *
     * @return Option<CommercialInvoiceTaxesOrMiscellaneousChargeType|UnknownEnumValue<string>>
     */
    public function getTaxesOrMiscellaneousChargeType(): Option
    {
        return $this->taxesOrMiscellaneousChargeType;
    }

    /**
     * Indicates the freight charge added by the shipper/customer for shipping the package. Optional
     * to the customer.
     *
     * @return Option<Money>
     */
    public function getFreightCharge(): Option
    {
        return $this->freightCharge;
    }

    /**
     * Indicates the packing cost added by the shipper/customer for shipping the package. Optional
     * to the customer.
     *
     * @return Option<Money>
     */
    public function getPackingCosts(): Option
    {
        return $this->packingCosts;
    }

    /**
     * Indicates the packing cost added by the shipper/customer for shipping the package. Optional
     * to the customer.
     *
     * @return Option<Money>
     */
    public function getHandlingCosts(): Option
    {
        return $this->handlingCosts;
    }

    /**
     * For licensed/ECCN shipments, the Destination Control Statement is fixed and non-editable;
     * shippers who need a different statement must supply their own commercial invoice.
     *
     * Example: declarationStatement
     *
     * @return Option<string>
     */
    public function getDeclarationStatement(): Option
    {
        return $this->declarationStatement;
    }

    /**
     * The termsOfSale that will populate the Commercial Invoice (or Pro Forma). Max length is 3.
     *
     * Example: FCA
     *
     * @return Option<string>
     */
    public function getTermsOfSale(): Option
    {
        return $this->termsOfSale;
    }

    /**
     * These are special instructions that will be populated on the Commercial Invoice (or Pro
     * Forma).
     *
     * Example: specialInstructions
     *
     * @return Option<string>
     */
    public function getSpecialInstructions(): Option
    {
        return $this->specialInstructions;
    }

    /**
     * The reason for the shipment. Note: SOLD is not a valid purpose for a Proforma Invoice.
     *
     * Example: REPAIR_AND_RETURN
     *
     * @return Option<CommercialInvoiceShipmentPurpose|UnknownEnumValue<string>>
     */
    public function getShipmentPurpose(): Option
    {
        return $this->shipmentPurpose;
    }

    /**
     * These are email disposition details. Provides the type and email addresses of e-mail
     * recipients. If returnedDispositionDetail in labelSpecification is set as true then email will
     * be send with label and documents copy.
     *
     * @return Option<ShipEmailDispositionDetail>
     */
    public function getEmailNotificationDetail(): Option
    {
        return $this->emailNotificationDetail;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $originatorName = None::create();
        $paymentTerms = None::create();
        $comments = None::create();
        $customerReferences = None::create();
        $taxesOrMiscellaneousCharge = None::create();
        $taxesOrMiscellaneousChargeType = None::create();
        $freightCharge = None::create();
        $packingCosts = None::create();
        $handlingCosts = None::create();
        $declarationStatement = None::create();
        $termsOfSale = None::create();
        $specialInstructions = None::create();
        $shipmentPurpose = None::create();
        $emailNotificationDetail = None::create();
        if (array_key_exists('originatorName', $data) && $data['originatorName'] !== null) {
            $originatorNameRaw = $data['originatorName'];
            if (!is_string($originatorNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "originatorName" must be string, got %s.', get_debug_type($originatorNameRaw)),
                );
            }
            $originatorName = Some::create($originatorNameRaw);
        }
        if (array_key_exists('paymentTerms', $data) && $data['paymentTerms'] !== null) {
            $paymentTermsRaw = $data['paymentTerms'];
            if (!is_string($paymentTermsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "paymentTerms" must be string, got %s.', get_debug_type($paymentTermsRaw)),
                );
            }
            $paymentTerms = Some::create($paymentTermsRaw);
        }
        if (array_key_exists('comments', $data) && $data['comments'] !== null) {
            $commentsRaw = $data['comments'];
            if (!(is_array($commentsRaw) && array_is_list($commentsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "comments" must be list, got %s.', get_debug_type($commentsRaw)),
                );
            }
            $comments = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $commentsRaw));
        }
        if (array_key_exists('customerReferences', $data) && $data['customerReferences'] !== null) {
            $customerReferencesRaw = $data['customerReferences'];
            if (!(is_array($customerReferencesRaw) && array_is_list($customerReferencesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "customerReferences" must be list, got %s.',
                        get_debug_type($customerReferencesRaw),
                    ),
                );
            }
            $customerReferences = Some::create(array_map(static function (mixed $value_1): CustomerReference {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return CustomerReference::fromArray($value_1Typed);
            }, $customerReferencesRaw));
        }
        if (array_key_exists('taxesOrMiscellaneousCharge', $data) && $data['taxesOrMiscellaneousCharge'] !== null) {
            $taxesOrMiscellaneousChargeRaw = $data['taxesOrMiscellaneousCharge'];
            if (!is_array($taxesOrMiscellaneousChargeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "taxesOrMiscellaneousCharge" must be object, got %s.',
                        get_debug_type($taxesOrMiscellaneousChargeRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $taxesOrMiscellaneousChargeRawTyped */
            $taxesOrMiscellaneousChargeRawTyped = $taxesOrMiscellaneousChargeRaw;
            $taxesOrMiscellaneousCharge = Some::create(Money::fromArray($taxesOrMiscellaneousChargeRawTyped));
        }
        if (
            array_key_exists('taxesOrMiscellaneousChargeType', $data)
            && $data['taxesOrMiscellaneousChargeType'] !== null
        ) {
            $taxesOrMiscellaneousChargeTypeRaw = $data['taxesOrMiscellaneousChargeType'];
            if (!is_string($taxesOrMiscellaneousChargeTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "taxesOrMiscellaneousChargeType" must be string, got %s.',
                        get_debug_type($taxesOrMiscellaneousChargeTypeRaw),
                    ),
                );
            }
            $taxesOrMiscellaneousChargeType = Some::create(
                CommercialInvoiceTaxesOrMiscellaneousChargeType::tryFrom($taxesOrMiscellaneousChargeTypeRaw)
                    ?? UnknownEnumValue::of($taxesOrMiscellaneousChargeTypeRaw),
            );
        }
        if (array_key_exists('freightCharge', $data) && $data['freightCharge'] !== null) {
            $freightChargeRaw = $data['freightCharge'];
            if (!is_array($freightChargeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "freightCharge" must be object, got %s.', get_debug_type($freightChargeRaw)),
                );
            }
            /** @var array<string, mixed> $freightChargeRawTyped */
            $freightChargeRawTyped = $freightChargeRaw;
            $freightCharge = Some::create(Money::fromArray($freightChargeRawTyped));
        }
        if (array_key_exists('packingCosts', $data) && $data['packingCosts'] !== null) {
            $packingCostsRaw = $data['packingCosts'];
            if (!is_array($packingCostsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "packingCosts" must be object, got %s.', get_debug_type($packingCostsRaw)),
                );
            }
            /** @var array<string, mixed> $packingCostsRawTyped */
            $packingCostsRawTyped = $packingCostsRaw;
            $packingCosts = Some::create(Money::fromArray($packingCostsRawTyped));
        }
        if (array_key_exists('handlingCosts', $data) && $data['handlingCosts'] !== null) {
            $handlingCostsRaw = $data['handlingCosts'];
            if (!is_array($handlingCostsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "handlingCosts" must be object, got %s.', get_debug_type($handlingCostsRaw)),
                );
            }
            /** @var array<string, mixed> $handlingCostsRawTyped */
            $handlingCostsRawTyped = $handlingCostsRaw;
            $handlingCosts = Some::create(Money::fromArray($handlingCostsRawTyped));
        }
        if (array_key_exists('declarationStatement', $data) && $data['declarationStatement'] !== null) {
            $declarationStatementRaw = $data['declarationStatement'];
            if (!is_string($declarationStatementRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "declarationStatement" must be string, got %s.',
                        get_debug_type($declarationStatementRaw),
                    ),
                );
            }
            $declarationStatement = Some::create($declarationStatementRaw);
        }
        if (array_key_exists('termsOfSale', $data) && $data['termsOfSale'] !== null) {
            $termsOfSaleRaw = $data['termsOfSale'];
            if (!is_string($termsOfSaleRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "termsOfSale" must be string, got %s.', get_debug_type($termsOfSaleRaw)),
                );
            }
            $termsOfSale = Some::create($termsOfSaleRaw);
        }
        if (array_key_exists('specialInstructions', $data) && $data['specialInstructions'] !== null) {
            $specialInstructionsRaw = $data['specialInstructions'];
            if (!is_string($specialInstructionsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "specialInstructions" must be string, got %s.',
                        get_debug_type($specialInstructionsRaw),
                    ),
                );
            }
            $specialInstructions = Some::create($specialInstructionsRaw);
        }
        if (array_key_exists('shipmentPurpose', $data) && $data['shipmentPurpose'] !== null) {
            $shipmentPurposeRaw = $data['shipmentPurpose'];
            if (!is_string($shipmentPurposeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipmentPurpose" must be string, got %s.', get_debug_type($shipmentPurposeRaw)),
                );
            }
            $shipmentPurpose = Some::create(
                CommercialInvoiceShipmentPurpose::tryFrom($shipmentPurposeRaw)
                    ?? UnknownEnumValue::of($shipmentPurposeRaw),
            );
        }
        if (array_key_exists('emailNotificationDetail', $data) && $data['emailNotificationDetail'] !== null) {
            $emailNotificationDetailRaw = $data['emailNotificationDetail'];
            if (!is_array($emailNotificationDetailRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "emailNotificationDetail" must be object, got %s.',
                        get_debug_type($emailNotificationDetailRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $emailNotificationDetailRawTyped */
            $emailNotificationDetailRawTyped = $emailNotificationDetailRaw;
            $emailNotificationDetail = Some::create(
                ShipEmailDispositionDetail::fromArray($emailNotificationDetailRawTyped),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'originatorName' => true,
                'paymentTerms' => true,
                'comments' => true,
                'customerReferences' => true,
                'taxesOrMiscellaneousCharge' => true,
                'taxesOrMiscellaneousChargeType' => true,
                'freightCharge' => true,
                'packingCosts' => true,
                'handlingCosts' => true,
                'declarationStatement' => true,
                'termsOfSale' => true,
                'specialInstructions' => true,
                'shipmentPurpose' => true,
                'emailNotificationDetail' => true,
            ],
        );

        return new self(
            $originatorName,
            $paymentTerms,
            $comments,
            $customerReferences,
            $taxesOrMiscellaneousCharge,
            $taxesOrMiscellaneousChargeType,
            $freightCharge,
            $packingCosts,
            $handlingCosts,
            $declarationStatement,
            $termsOfSale,
            $specialInstructions,
            $shipmentPurpose,
            $emailNotificationDetail,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $originatorNameOption = $this->originatorName;
        if ($originatorNameOption->isDefined()) {
            $originatorName = $originatorNameOption->get();
            $dataArray['originatorName'] = $originatorName;
        }
        $paymentTermsOption = $this->paymentTerms;
        if ($paymentTermsOption->isDefined()) {
            $paymentTerms = $paymentTermsOption->get();
            $dataArray['paymentTerms'] = $paymentTerms;
        }
        $commentsOption = $this->comments;
        if ($commentsOption->isDefined()) {
            $comments = $commentsOption->get();
            $values = [];
            foreach ($comments as $value) {
                $values[] = $value;
            }
            $dataArray['comments'] = $values;
        }
        $customerReferencesOption = $this->customerReferences;
        if ($customerReferencesOption->isDefined()) {
            $customerReferences = $customerReferencesOption->get();
            $values_1 = [];
            foreach ($customerReferences as $value_1) {
                $values_1[] = $normalizationTarget->model($value_1);
            }
            $dataArray['customerReferences'] = $values_1;
        }
        $taxesOrMiscellaneousChargeOption = $this->taxesOrMiscellaneousCharge;
        if ($taxesOrMiscellaneousChargeOption->isDefined()) {
            $taxesOrMiscellaneousCharge = $taxesOrMiscellaneousChargeOption->get();
            $dataArray['taxesOrMiscellaneousCharge'] = $normalizationTarget->model($taxesOrMiscellaneousCharge);
        }
        $taxesOrMiscellaneousChargeTypeOption = $this->taxesOrMiscellaneousChargeType;
        if ($taxesOrMiscellaneousChargeTypeOption->isDefined()) {
            $taxesOrMiscellaneousChargeType = $taxesOrMiscellaneousChargeTypeOption->get();
            $dataArray['taxesOrMiscellaneousChargeType'] = $taxesOrMiscellaneousChargeType->value;
        }
        $freightChargeOption = $this->freightCharge;
        if ($freightChargeOption->isDefined()) {
            $freightCharge = $freightChargeOption->get();
            $dataArray['freightCharge'] = $normalizationTarget->model($freightCharge);
        }
        $packingCostsOption = $this->packingCosts;
        if ($packingCostsOption->isDefined()) {
            $packingCosts = $packingCostsOption->get();
            $dataArray['packingCosts'] = $normalizationTarget->model($packingCosts);
        }
        $handlingCostsOption = $this->handlingCosts;
        if ($handlingCostsOption->isDefined()) {
            $handlingCosts = $handlingCostsOption->get();
            $dataArray['handlingCosts'] = $normalizationTarget->model($handlingCosts);
        }
        $declarationStatementOption = $this->declarationStatement;
        if ($declarationStatementOption->isDefined()) {
            $declarationStatement = $declarationStatementOption->get();
            $dataArray['declarationStatement'] = $declarationStatement;
        }
        $termsOfSaleOption = $this->termsOfSale;
        if ($termsOfSaleOption->isDefined()) {
            $termsOfSale = $termsOfSaleOption->get();
            $dataArray['termsOfSale'] = $termsOfSale;
        }
        $specialInstructionsOption = $this->specialInstructions;
        if ($specialInstructionsOption->isDefined()) {
            $specialInstructions = $specialInstructionsOption->get();
            $dataArray['specialInstructions'] = $specialInstructions;
        }
        $shipmentPurposeOption = $this->shipmentPurpose;
        if ($shipmentPurposeOption->isDefined()) {
            $shipmentPurpose = $shipmentPurposeOption->get();
            $dataArray['shipmentPurpose'] = $shipmentPurpose->value;
        }
        $emailNotificationDetailOption = $this->emailNotificationDetail;
        if ($emailNotificationDetailOption->isDefined()) {
            $emailNotificationDetail = $emailNotificationDetailOption->get();
            $dataArray['emailNotificationDetail'] = $normalizationTarget->model($emailNotificationDetail);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): CommercialInvoiceBuilder
    {
        return new CommercialInvoiceBuilder(
            $this->originatorName,
            $this->paymentTerms,
            $this->comments,
            $this->customerReferences,
            $this->taxesOrMiscellaneousCharge,
            $this->taxesOrMiscellaneousChargeType,
            $this->freightCharge,
            $this->packingCosts,
            $this->handlingCosts,
            $this->declarationStatement,
            $this->termsOfSale,
            $this->specialInstructions,
            $this->shipmentPurpose,
            $this->emailNotificationDetail,
            $this->additionalProperties,
        );
    }
}
