<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class CompletedHazardousShipmentDetail implements SelfNormalizingModel
{
    /**
     * @param Option<CompletedHazardousSummaryDetail> $hazardousSummaryDetail
     * @param Option<AdrLicenseDetail>                $adrLicense
     * @param Option<ShipmentDryIceDetail>            $dryIceDetail
     * @param array<int|string, mixed>                $additionalProperties
     */
    public function __construct(
        private Option $hazardousSummaryDetail,
        private Option $adrLicense,
        private Option $dryIceDetail,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): CompletedHazardousShipmentDetailBuilder
    {
        return new CompletedHazardousShipmentDetailBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Specifies Completed Hazardous Summary Detail.
     *
     * @return Option<CompletedHazardousSummaryDetail>
     */
    public function getHazardousSummaryDetail(): Option
    {
        return $this->hazardousSummaryDetail;
    }

    /**
     * Specifies the details around the ADR license required for shipping.
     *
     * @return Option<AdrLicenseDetail>
     */
    public function getAdrLicense(): Option
    {
        return $this->adrLicense;
    }

    /**
     * Specifies the shipment level totals of dry ice data across all packages.
     *
     * @return Option<ShipmentDryIceDetail>
     */
    public function getDryIceDetail(): Option
    {
        return $this->dryIceDetail;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $hazardousSummaryDetail = None::create();
        $adrLicense = None::create();
        $dryIceDetail = None::create();
        if (array_key_exists('hazardousSummaryDetail', $data) && $data['hazardousSummaryDetail'] !== null) {
            $hazardousSummaryDetailRaw = $data['hazardousSummaryDetail'];
            if (!is_array($hazardousSummaryDetailRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "hazardousSummaryDetail" must be object, got %s.',
                        get_debug_type($hazardousSummaryDetailRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $hazardousSummaryDetailRawTyped */
            $hazardousSummaryDetailRawTyped = $hazardousSummaryDetailRaw;
            $hazardousSummaryDetail = Some::create(
                CompletedHazardousSummaryDetail::fromArray($hazardousSummaryDetailRawTyped),
            );
        }
        if (array_key_exists('adrLicense', $data) && $data['adrLicense'] !== null) {
            $adrLicenseRaw = $data['adrLicense'];
            if (!is_array($adrLicenseRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "adrLicense" must be object, got %s.', get_debug_type($adrLicenseRaw)),
                );
            }
            /** @var array<string, mixed> $adrLicenseRawTyped */
            $adrLicenseRawTyped = $adrLicenseRaw;
            $adrLicense = Some::create(AdrLicenseDetail::fromArray($adrLicenseRawTyped));
        }
        if (array_key_exists('dryIceDetail', $data) && $data['dryIceDetail'] !== null) {
            $dryIceDetailRaw = $data['dryIceDetail'];
            if (!is_array($dryIceDetailRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dryIceDetail" must be object, got %s.', get_debug_type($dryIceDetailRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $dryIceDetailRawTyped */
            $dryIceDetailRawTyped = $dryIceDetailRaw;
            $dryIceDetail = Some::create(ShipmentDryIceDetail::fromArray($dryIceDetailRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['hazardousSummaryDetail' => true, 'adrLicense' => true, 'dryIceDetail' => true],
        );

        return new self($hazardousSummaryDetail, $adrLicense, $dryIceDetail, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $hazardousSummaryDetailOption = $this->hazardousSummaryDetail;
        if ($hazardousSummaryDetailOption->isDefined()) {
            $hazardousSummaryDetail = $hazardousSummaryDetailOption->get();
            $dataArray['hazardousSummaryDetail'] = $normalizationTarget->model($hazardousSummaryDetail);
        }
        $adrLicenseOption = $this->adrLicense;
        if ($adrLicenseOption->isDefined()) {
            $adrLicense = $adrLicenseOption->get();
            $dataArray['adrLicense'] = $normalizationTarget->model($adrLicense);
        }
        $dryIceDetailOption = $this->dryIceDetail;
        if ($dryIceDetailOption->isDefined()) {
            $dryIceDetail = $dryIceDetailOption->get();
            $dataArray['dryIceDetail'] = $normalizationTarget->model($dryIceDetail);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): CompletedHazardousShipmentDetailBuilder
    {
        return new CompletedHazardousShipmentDetailBuilder(
            $this->hazardousSummaryDetail,
            $this->adrLicense,
            $this->dryIceDetail,
            $this->additionalProperties,
        );
    }
}
