<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class ContactAndAddressVerify implements SelfNormalizingModel
{
    /**
     * @param Option<ContactVerify>    $contact
     * @param Option<Address1>         $address
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $contact, private Option $address, private array $additionalProperties)
    {
    }

    public static function builder(): ContactAndAddressVerifyBuilder
    {
        return new ContactAndAddressVerifyBuilder(None::create(), None::create(), []);
    }

    /**
     * Indicate the contact details of the shipper.
     *
     * @return Option<ContactVerify>
     */
    public function getContact(): Option
    {
        return $this->contact;
    }

    /**
     * This is detailed information on physical location. May be used as an actual physical address
     * (place to which one could go), or as a container of address parts which should be handled as
     * a unit (such as a city-state-ZIP combination within the U.S.).
     *
     * @return Option<Address1>
     */
    public function getAddress(): Option
    {
        return $this->address;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $contact = None::create();
        $address = None::create();
        if (array_key_exists('contact', $data) && $data['contact'] !== null) {
            $contactRaw = $data['contact'];
            if (!is_array($contactRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "contact" must be object, got %s.', get_debug_type($contactRaw)),
                );
            }
            /** @var array<string, mixed> $contactRawTyped */
            $contactRawTyped = $contactRaw;
            $contact = Some::create(ContactVerify::fromArray($contactRawTyped));
        }
        if (array_key_exists('address', $data) && $data['address'] !== null) {
            $addressRaw = $data['address'];
            if (!is_array($addressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "address" must be object, got %s.', get_debug_type($addressRaw)),
                );
            }
            /** @var array<string, mixed> $addressRawTyped */
            $addressRawTyped = $addressRaw;
            $address = Some::create(Address1::fromArray($addressRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['contact' => true, 'address' => true]);

        return new self($contact, $address, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $contactOption = $this->contact;
        if ($contactOption->isDefined()) {
            $contact = $contactOption->get();
            $dataArray['contact'] = $normalizationTarget->model($contact);
        }
        $addressOption = $this->address;
        if ($addressOption->isDefined()) {
            $address = $addressOption->get();
            $dataArray['address'] = $normalizationTarget->model($address);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ContactAndAddressVerifyBuilder
    {
        return new ContactAndAddressVerifyBuilder($this->contact, $this->address, $this->additionalProperties);
    }
}
