<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ContactAndAddress}.
 */
final class ContactAndAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<Contact1>         $contact
     * @param Option<Address1>         $address
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $contact, private Option $address, private array $additionalProperties)
    {
    }

    /**
     * Indicate the contact details for this shipment.
     */
    public function setContact(Contact1 $contact): self
    {
        $this->contact = Some::create($contact);

        return $this;
    }

    /**
     * This is detailed information on physical location. May be used as an actual physical address
     * (place to which one could go), or as a container of address parts which should be handled as
     * a unit (such as a city-state-ZIP combination within the U.S.).
     */
    public function setAddress(Address1 $address): self
    {
        $this->address = Some::create($address);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ContactAndAddress
    {
        return new ContactAndAddress($this->contact, $this->address, $this->additionalProperties);
    }
}
