<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class CreateShipmentRating implements SelfNormalizingModel
{
    /**
     * @param Option<string>                               $actualRateType
     * @param Option<list<ShipmentRateDetail>>             $shipmentRateDetails
     * @param Option<Money1>                               $totalNetTransportationAndPickupCharge
     * @param Option<Money1>                               $totalNetFedExTransportationAndPickupCharge
     * @param Option<CreateShipmentRatingPickupRateDetail> $pickupRateDetail
     * @param array<int|string, mixed>                     $additionalProperties
     */
    public function __construct(
        private Option $actualRateType,
        private Option $shipmentRateDetails,
        private Option $totalNetTransportationAndPickupCharge,
        private Option $totalNetFedExTransportationAndPickupCharge,
        private Option $pickupRateDetail,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): CreateShipmentRatingBuilder
    {
        return new CreateShipmentRatingBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * This rate type identifies which entry in the following array is considered as presenting the
     * "actual" rates for the shipment.
     *
     * Example: PAYOR_LIST_SHIPMENT
     *
     * @return Option<string>
     */
    public function getActualRateType(): Option
    {
        return $this->actualRateType;
    }

    /**
     * Each element of this field provides shipment-level rate totals for a specific rate type.
     *
     * @return Option<list<ShipmentRateDetail>>
     */
    public function getShipmentRateDetails(): Option
    {
        return $this->shipmentRateDetails;
    }

    /**
     * Sum of totalNetCharge from pickupRateDetail and shipmentRateDetail. This charge will be
     * populated regardless of pickup.
     *
     * @return Option<Money1>
     */
    public function getTotalNetTransportationAndPickupCharge(): Option
    {
        return $this->totalNetTransportationAndPickupCharge;
    }

    /**
     * Sum of totalNetFedExCharge from pickupRateDetail and shipmentRateDetail. This charge will be
     * populated regardless of a pickup.
     *
     * @return Option<Money1>
     */
    public function getTotalNetFedExTransportationAndPickupCharge(): Option
    {
        return $this->totalNetFedExTransportationAndPickupCharge;
    }

    /**
     * Charges associated with a scheduled shipment pickup.
     *
     * @return Option<CreateShipmentRatingPickupRateDetail>
     */
    public function getPickupRateDetail(): Option
    {
        return $this->pickupRateDetail;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $actualRateType = None::create();
        $shipmentRateDetails = None::create();
        $totalNetTransportationAndPickupCharge = None::create();
        $totalNetFedExTransportationAndPickupCharge = None::create();
        $pickupRateDetail = None::create();
        if (array_key_exists('actualRateType', $data) && $data['actualRateType'] !== null) {
            $actualRateTypeRaw = $data['actualRateType'];
            if (!is_string($actualRateTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "actualRateType" must be string, got %s.', get_debug_type($actualRateTypeRaw)),
                );
            }
            $actualRateType = Some::create($actualRateTypeRaw);
        }
        if (array_key_exists('shipmentRateDetails', $data) && $data['shipmentRateDetails'] !== null) {
            $shipmentRateDetailsRaw = $data['shipmentRateDetails'];
            if (!(is_array($shipmentRateDetailsRaw) && array_is_list($shipmentRateDetailsRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipmentRateDetails" must be list, got %s.',
                        get_debug_type($shipmentRateDetailsRaw),
                    ),
                );
            }
            $shipmentRateDetails = Some::create(array_map(static function (mixed $value): ShipmentRateDetail {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return ShipmentRateDetail::fromArray($valueTyped);
            }, $shipmentRateDetailsRaw));
        }
        if (
            array_key_exists('totalNetTransportationAndPickupCharge', $data)
            && $data['totalNetTransportationAndPickupCharge'] !== null
        ) {
            $totalNetTransportationAndPickupChargeRaw = $data['totalNetTransportationAndPickupCharge'];
            if (!is_array($totalNetTransportationAndPickupChargeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "totalNetTransportationAndPickupCharge" must be object, got %s.',
                        get_debug_type($totalNetTransportationAndPickupChargeRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $totalNetTransportationAndPickupChargeRawTyped */
            $totalNetTransportationAndPickupChargeRawTyped = $totalNetTransportationAndPickupChargeRaw;
            $totalNetTransportationAndPickupCharge = Some::create(
                Money1::fromArray($totalNetTransportationAndPickupChargeRawTyped),
            );
        }
        if (
            array_key_exists('totalNetFedExTransportationAndPickupCharge', $data)
            && $data['totalNetFedExTransportationAndPickupCharge'] !== null
        ) {
            $totalNetFedExTransportationAndPickupChargeRaw = $data['totalNetFedExTransportationAndPickupCharge'];
            if (!is_array($totalNetFedExTransportationAndPickupChargeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "totalNetFedExTransportationAndPickupCharge" must be object, got %s.',
                        get_debug_type($totalNetFedExTransportationAndPickupChargeRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $totalNetFedExTransportationAndPickupChargeRawTyped */
            $totalNetFedExTransportationAndPickupChargeRawTyped = $totalNetFedExTransportationAndPickupChargeRaw;
            $totalNetFedExTransportationAndPickupCharge = Some::create(
                Money1::fromArray($totalNetFedExTransportationAndPickupChargeRawTyped),
            );
        }
        if (array_key_exists('pickupRateDetail', $data) && $data['pickupRateDetail'] !== null) {
            $pickupRateDetailRaw = $data['pickupRateDetail'];
            if (!is_array($pickupRateDetailRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "pickupRateDetail" must be object, got %s.',
                        get_debug_type($pickupRateDetailRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $pickupRateDetailRawTyped */
            $pickupRateDetailRawTyped = $pickupRateDetailRaw;
            $pickupRateDetail = Some::create(
                CreateShipmentRatingPickupRateDetail::fromArray($pickupRateDetailRawTyped),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'actualRateType' => true,
                'shipmentRateDetails' => true,
                'totalNetTransportationAndPickupCharge' => true,
                'totalNetFedExTransportationAndPickupCharge' => true,
                'pickupRateDetail' => true,
            ],
        );

        return new self(
            $actualRateType,
            $shipmentRateDetails,
            $totalNetTransportationAndPickupCharge,
            $totalNetFedExTransportationAndPickupCharge,
            $pickupRateDetail,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $actualRateTypeOption = $this->actualRateType;
        if ($actualRateTypeOption->isDefined()) {
            $actualRateType = $actualRateTypeOption->get();
            $dataArray['actualRateType'] = $actualRateType;
        }
        $shipmentRateDetailsOption = $this->shipmentRateDetails;
        if ($shipmentRateDetailsOption->isDefined()) {
            $shipmentRateDetails = $shipmentRateDetailsOption->get();
            $values = [];
            foreach ($shipmentRateDetails as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['shipmentRateDetails'] = $values;
        }
        $totalNetTransportationAndPickupChargeOption = $this->totalNetTransportationAndPickupCharge;
        if ($totalNetTransportationAndPickupChargeOption->isDefined()) {
            $totalNetTransportationAndPickupCharge = $totalNetTransportationAndPickupChargeOption->get();
            $dataArray['totalNetTransportationAndPickupCharge'] = $normalizationTarget->model(
                $totalNetTransportationAndPickupCharge,
            );
        }
        $totalNetFedExTransportationAndPickupChargeOption = $this->totalNetFedExTransportationAndPickupCharge;
        if ($totalNetFedExTransportationAndPickupChargeOption->isDefined()) {
            $totalNetFedExTransportationAndPickupCharge = $totalNetFedExTransportationAndPickupChargeOption->get();
            $dataArray['totalNetFedExTransportationAndPickupCharge'] = $normalizationTarget->model(
                $totalNetFedExTransportationAndPickupCharge,
            );
        }
        $pickupRateDetailOption = $this->pickupRateDetail;
        if ($pickupRateDetailOption->isDefined()) {
            $pickupRateDetail = $pickupRateDetailOption->get();
            $dataArray['pickupRateDetail'] = $normalizationTarget->model($pickupRateDetail);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): CreateShipmentRatingBuilder
    {
        return new CreateShipmentRatingBuilder(
            $this->actualRateType,
            $this->shipmentRateDetails,
            $this->totalNetTransportationAndPickupCharge,
            $this->totalNetFedExTransportationAndPickupCharge,
            $this->pickupRateDetail,
            $this->additionalProperties,
        );
    }
}
