<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum CustomerImageUsageId: string
{
    case IMAGE_1 = 'IMAGE_1';
    case IMAGE_2 = 'IMAGE_2';
    case IMAGE_3 = 'IMAGE_3';
    case IMAGE_4 = 'IMAGE_4';
    case IMAGE_5 = 'IMAGE_5';
}
