<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see CustomerSpecifiedLabelDetail}.
 */
final class CustomerSpecifiedLabelDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<CustomerSpecifiedLabelDetailMaskedDataItem|UnknownEnumValue<string>>> $maskedData
     * @param Option<list<RegulatoryLabelContentDetail>>                                        $regulatoryLabels
     * @param Option<list<AdditionalLabelsDetail>>                                              $additionalLabels
     * @param Option<DocTabContent>                                                             $docTabContent
     * @param array<int|string, mixed>                                                          $additionalProperties
     */
    public function __construct(
        private Option $maskedData,
        private Option $regulatoryLabels,
        private Option $additionalLabels,
        private Option $docTabContent,
        private array $additionalProperties,
    ) {
    }

    /**
     * Controls which data/sections will be suppressed.
     *
     * Example: TOTAL_WEIGHT
     *
     * @param list<CustomerSpecifiedLabelDetailMaskedDataItem> $maskedData
     */
    public function setMaskedData(array $maskedData): self
    {
        $this->maskedData = Some::create($maskedData);

        return $this;
    }

    /**
     * Specify how the regulatory details to be provided on the labels.
     *
     * @param list<RegulatoryLabelContentDetail> $regulatoryLabels
     */
    public function setRegulatoryLabels(array $regulatoryLabels): self
    {
        $this->regulatoryLabels = Some::create($regulatoryLabels);

        return $this;
    }

    /**
     * Specify how the additional details to be provided on the labels.
     *
     * @param list<AdditionalLabelsDetail> $additionalLabels
     */
    public function setAdditionalLabels(array $additionalLabels): self
    {
        $this->additionalLabels = Some::create($additionalLabels);

        return $this;
    }

    /**
     * Specifies details of doc tab content.It is only applicable only with imageType as ZPLII.
     */
    public function setDocTabContent(DocTabContent $docTabContent): self
    {
        $this->docTabContent = Some::create($docTabContent);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): CustomerSpecifiedLabelDetail
    {
        return new CustomerSpecifiedLabelDetail(
            $this->maskedData,
            $this->regulatoryLabels,
            $this->additionalLabels,
            $this->docTabContent,
            $this->additionalProperties,
        );
    }
}
