<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class CustomerReference implements SelfNormalizingModel
{
    /**
     * @param Option<CustomerReferenceCustomerReferenceType|UnknownEnumValue<string>> $customerReferenceType
     * @param Option<string>                                                          $value
     * @param array<int|string, mixed>                                                $additionalProperties
     */
    public function __construct(
        private Option $customerReferenceType,
        private Option $value,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): CustomerReferenceBuilder
    {
        return new CustomerReferenceBuilder(None::create(), None::create(), []);
    }

    /**
     * This is a customer reference type. Note: Use type Type, RMA_ASSOCIATION and value as the RMA
     * Number to associate Ground Call Tag shipments to the outbound shipment.
     *
     * Example: DEPARTMENT_NUMBER
     *
     * @return Option<CustomerReferenceCustomerReferenceType|UnknownEnumValue<string>>
     */
    public function getCustomerReferenceType(): Option
    {
        return $this->customerReferenceType;
    }

    /**
     * This is a customer reference type value.
     *
     * Example: 3686 <ul><li>The P_O_NUMBER value must be specified in customerReferences under
     * requestedPackageLineItems</li><li>The INVOICE_NUMBER value that is printed on the
     * FedEx-supplied invoice must be specified in customerReferences under commercialInvoice. Value
     * defined in this section will print on the label that is attached to the package</li><li>The
     * RMA value sent by the customer is returned on the label in human readable form but also as a
     * barcode. RMA_ASSOCIATION only prints on the label as a barcode for a Return
     * shipment.</ul>NOTE:<ul><li> INTRACOUNTRY_REGULATORY_REFERENCE is applicable only in
     * Intra-Brazil.</li><li> Maximum length varies for value field depending on
     * customerReferenceType.</li></ul> Maximum length for value is as follows:
     * <ul><li>CUSTOMER_REFERENCE - 40(Express), 30(Ground)</li><li>DEPARTMENT_NUMBER -
     * 30</li><li>INVOICE_NUMBER - 30</li><li>P_O_NUMBER -
     * 30</li><li>INTRACOUNTRY_REGULATORY_REFERENCE - 30</li><li>RMA_ASSOCIATION - 20</li>
     *
     * @return Option<string>
     */
    public function getValue(): Option
    {
        return $this->value;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $customerReferenceType = None::create();
        $value = None::create();
        if (array_key_exists('customerReferenceType', $data) && $data['customerReferenceType'] !== null) {
            $customerReferenceTypeRaw = $data['customerReferenceType'];
            if (!is_string($customerReferenceTypeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "customerReferenceType" must be string, got %s.',
                        get_debug_type($customerReferenceTypeRaw),
                    ),
                );
            }
            $customerReferenceType = Some::create(
                CustomerReferenceCustomerReferenceType::tryFrom($customerReferenceTypeRaw)
                    ?? UnknownEnumValue::of($customerReferenceTypeRaw),
            );
        }
        if (array_key_exists('value', $data) && $data['value'] !== null) {
            $valueRaw = $data['value'];
            if (!is_string($valueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "value" must be string, got %s.', get_debug_type($valueRaw)),
                );
            }
            $value = Some::create($valueRaw);
        }
        $additionalProperties = array_diff_key($data, ['customerReferenceType' => true, 'value' => true]);

        return new self($customerReferenceType, $value, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $customerReferenceTypeOption = $this->customerReferenceType;
        if ($customerReferenceTypeOption->isDefined()) {
            $customerReferenceType = $customerReferenceTypeOption->get();
            $dataArray['customerReferenceType'] = $customerReferenceType->value;
        }
        $valueOption = $this->value;
        if ($valueOption->isDefined()) {
            $value = $valueOption->get();
            $dataArray['value'] = $value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): CustomerReferenceBuilder
    {
        return new CustomerReferenceBuilder($this->customerReferenceType, $this->value, $this->additionalProperties);
    }
}
