<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum DangerousGoodsDetailOptionsItem: string
{
    case HAZARDOUS_MATERIALS = 'HAZARDOUS_MATERIALS';
    case BATTERY = 'BATTERY';
    case ORM_D = 'ORM_D';
    case REPORTABLE_QUANTITIES = 'REPORTABLE_QUANTITIES';
    case SMALL_QUANTITY_EXCEPTION = 'SMALL_QUANTITY_EXCEPTION';
    case LIMITED_QUANTITIES_COMMODITIES = 'LIMITED_QUANTITIES_COMMODITIES';
}
