<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

/**
 * Builds a {@see DeliveryOnInvoiceAcceptanceDetailRecipientContact}.
 */
final class DeliveryOnInvoiceAcceptanceDetailRecipientContactBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $companyName,
        private string $personName,
        private string $phoneNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * Identifies the company this contact is associated with. Maximum length is 35.
     */
    public function setCompanyName(string $companyName): self
    {
        $this->companyName = $companyName;

        return $this;
    }

    /**
     * Identifies the contact person's name. Maximum length is 70.
     */
    public function setPersonName(string $personName): self
    {
        $this->personName = $personName;

        return $this;
    }

    /**
     * Identifies the phone number associated with this contact. Maximum length is 10.
     */
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): DeliveryOnInvoiceAcceptanceDetailRecipientContact
    {
        return new DeliveryOnInvoiceAcceptanceDetailRecipientContact(
            $this->companyName,
            $this->personName,
            $this->phoneNumber,
            $this->additionalProperties,
        );
    }
}
