<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class DeliveryOnInvoiceAcceptanceDetail implements SelfNormalizingModel
{
    /**
     * @param Option<DeliveryOnInvoiceAcceptanceDetailRecipient> $recipient
     * @param array<int|string, mixed>                           $additionalProperties
     */
    public function __construct(private Option $recipient, private array $additionalProperties)
    {
    }

    public static function builder(): DeliveryOnInvoiceAcceptanceDetailBuilder
    {
        return new DeliveryOnInvoiceAcceptanceDetailBuilder(None::create(), []);
    }

    /**
     * The descriptive data for the recipient of the shipment and the physical location for the
     * shipment destination.
     *
     * @return Option<DeliveryOnInvoiceAcceptanceDetailRecipient>
     */
    public function getRecipient(): Option
    {
        return $this->recipient;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $recipient = None::create();
        if (array_key_exists('recipient', $data) && $data['recipient'] !== null) {
            $recipientRaw = $data['recipient'];
            if (!is_array($recipientRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "recipient" must be object, got %s.', get_debug_type($recipientRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $recipientRawTyped */
            $recipientRawTyped = $recipientRaw;
            $recipient = Some::create(DeliveryOnInvoiceAcceptanceDetailRecipient::fromArray($recipientRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['recipient' => true]);

        return new self($recipient, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $recipientOption = $this->recipient;
        if ($recipientOption->isDefined()) {
            $recipient = $recipientOption->get();
            $dataArray['recipient'] = $normalizationTarget->model($recipient);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): DeliveryOnInvoiceAcceptanceDetailBuilder
    {
        return new DeliveryOnInvoiceAcceptanceDetailBuilder($this->recipient, $this->additionalProperties);
    }
}
