<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class DisclaimMessageSet implements SelfNormalizingModel
{
    /**
     * @param Option<DisclaimMessageSetDisclaimCode|UnknownEnumValue<string>> $disclaimCode
     * @param Option<string>                                                  $intendedUseCode
     * @param Option<string>                                                  $intendedUseDescription
     * @param array<int|string, mixed>                                        $additionalProperties
     */
    public function __construct(
        private Option $disclaimCode,
        private Option $intendedUseCode,
        private Option $intendedUseDescription,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DisclaimMessageSetBuilder
    {
        return new DisclaimMessageSetBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Code representing a specific declaration or filing condition.
     *
     * Maximum length is 1.
     *
     * Accepted values
     *
     * 1. A - Product is not regulated by CPSC (meaning no rule, ban, standard, or regulation
     *    requiring a certificate applies.)
     *
     * 2. B - Data is not required per CPSC guidance (enforcement discretion)
     *
     * Example: A
     *
     * @return Option<DisclaimMessageSetDisclaimCode|UnknownEnumValue<string>>
     */
    public function getDisclaimCode(): Option
    {
        return $this->disclaimCode;
    }

    /**
     * Standardized code describing the intended consumer use of the product.
     *
     * Maximum length is 16.
     *
     * Example: 245.001
     *
     * @return Option<string>
     */
    public function getIntendedUseCode(): Option
    {
        return $this->intendedUseCode;
    }

    /**
     * Plain-language description of the product’s intended use.
     *
     * Maximum length is 22.
     *
     * Example: Children’s plastic educational toy for ages 3+
     *
     * @return Option<string>
     */
    public function getIntendedUseDescription(): Option
    {
        return $this->intendedUseDescription;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $disclaimCode = None::create();
        $intendedUseCode = None::create();
        $intendedUseDescription = None::create();
        if (array_key_exists('disclaimCode', $data) && $data['disclaimCode'] !== null) {
            $disclaimCodeRaw = $data['disclaimCode'];
            if (!is_string($disclaimCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "disclaimCode" must be string, got %s.', get_debug_type($disclaimCodeRaw)),
                );
            }
            $disclaimCode = Some::create(
                DisclaimMessageSetDisclaimCode::tryFrom($disclaimCodeRaw) ?? UnknownEnumValue::of($disclaimCodeRaw),
            );
        }
        if (array_key_exists('intendedUseCode', $data) && $data['intendedUseCode'] !== null) {
            $intendedUseCodeRaw = $data['intendedUseCode'];
            if (!is_string($intendedUseCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "intendedUseCode" must be string, got %s.', get_debug_type($intendedUseCodeRaw)),
                );
            }
            $intendedUseCode = Some::create($intendedUseCodeRaw);
        }
        if (array_key_exists('intendedUseDescription', $data) && $data['intendedUseDescription'] !== null) {
            $intendedUseDescriptionRaw = $data['intendedUseDescription'];
            if (!is_string($intendedUseDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "intendedUseDescription" must be string, got %s.',
                        get_debug_type($intendedUseDescriptionRaw),
                    ),
                );
            }
            $intendedUseDescription = Some::create($intendedUseDescriptionRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['disclaimCode' => true, 'intendedUseCode' => true, 'intendedUseDescription' => true],
        );

        return new self($disclaimCode, $intendedUseCode, $intendedUseDescription, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $disclaimCodeOption = $this->disclaimCode;
        if ($disclaimCodeOption->isDefined()) {
            $disclaimCode = $disclaimCodeOption->get();
            $dataArray['disclaimCode'] = $disclaimCode->value;
        }
        $intendedUseCodeOption = $this->intendedUseCode;
        if ($intendedUseCodeOption->isDefined()) {
            $intendedUseCode = $intendedUseCodeOption->get();
            $dataArray['intendedUseCode'] = $intendedUseCode;
        }
        $intendedUseDescriptionOption = $this->intendedUseDescription;
        if ($intendedUseDescriptionOption->isDefined()) {
            $intendedUseDescription = $intendedUseDescriptionOption->get();
            $dataArray['intendedUseDescription'] = $intendedUseDescription;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): DisclaimMessageSetBuilder
    {
        return new DisclaimMessageSetBuilder(
            $this->disclaimCode,
            $this->intendedUseCode,
            $this->intendedUseDescription,
            $this->additionalProperties,
        );
    }
}
