<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum DocTabContentBarcodedSymbology: string
{
    case CODABAR = 'CODABAR';
    case CODE128 = 'CODE128';
    case CODE128_WIDEBAR = 'CODE128_WIDEBAR';
    case CODE128B = 'CODE128B';
    case CODE128C = 'CODE128C';
    case CODE39 = 'CODE39';
    case CODE93 = 'CODE93';
    case I2OF5 = 'I2OF5';
    case MANUAL = 'MANUAL';
    case PDF417 = 'PDF417';
    case POSTNET = 'POSTNET';
    case QR_CODE = 'QR_CODE';
    case UCC128 = 'UCC128';
}
