<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_int;
use function is_string;
use function sprintf;

final readonly class DocTabZoneSpecification implements SelfNormalizingModel
{
    /**
     * @param Option<int>                                                           $zoneNumber
     * @param Option<string>                                                        $header
     * @param Option<string>                                                        $dataField
     * @param Option<string>                                                        $literalValue
     * @param Option<DocTabZoneSpecificationJustification|UnknownEnumValue<string>> $justification
     * @param array<int|string, mixed>                                              $additionalProperties
     */
    public function __construct(
        private Option $zoneNumber,
        private Option $header,
        private Option $dataField,
        private Option $literalValue,
        private Option $justification,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): DocTabZoneSpecificationBuilder
    {
        return new DocTabZoneSpecificationBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * It is a non-negative integer that represents the portion of doc-tab in a label.
     *
     * Example: 1
     *
     * @return Option<int>
     */
    public function getZoneNumber(): Option
    {
        return $this->zoneNumber;
    }

    /**
     * Indicates the parameter name in the header for the doc tab zone. The maximum charater limit
     * is 7.
     *
     * Example: WHT
     *
     * @return Option<string>
     */
    public function getHeader(): Option
    {
        return $this->header;
    }

    /**
     * Indicate the path request/reply element to be printed on doc tab.
     *
     * Example: <ul><li> REQUEST/PACKAGE/weight/Value</li><li>
     * REQUEST/PACKAGE/InsuredValue/Amount</li><li>
     * REQUEST/SHIPMENT/SpecialServicesRequested/CodDetail/CodCollectionAmount/Amount</li><li>REQUEST/SHIPMENT/Shipper/Address/StreetLines</li><li>
     * TRANSACTION/CustomerTransactionId</li><li> REQUEST/SHIPMENT/TotalWeight/Value</li><li>
     * REQUEST/SHIPMENT/ShipTimestamp</li><li>
     * REQUEST/SHIPMENT/Recipient/Contact/PersonName</li><li>
     * REPLY/SHIPMENT/OperationalDetail/DeliveryDate</li><li>
     * REPLY/SHIPMENT/RATES/ACTUAL/totalBaseCharge/Amount</li><li>
     * REPLY/SHIPMENT/RATES/ACTUAL/totalFreightDiscounts/Amount</li><li>
     * REPLY/SHIPMENT/RATES/ACTUAL/totalSurcharges/Amount</li><li>
     * REPLY/SHIPMENT/RATES/ACTUAL/totalNetCharge/Amount</li><li>
     * REPLY/SHIPMENT/RATES/PAYOR_ACCOUNT_PACKAGE/totalSurcharges/Amount</li></ul>
     *
     * @return Option<string>
     */
    public function getDataField(): Option
    {
        return $this->dataField;
    }

    /**
     * Indicates the actual data to be printed in the label.
     *
     * @return Option<string>
     */
    public function getLiteralValue(): Option
    {
        return $this->literalValue;
    }

    /**
     * Indicates the justification format for the string.
     *
     * @return Option<DocTabZoneSpecificationJustification|UnknownEnumValue<string>>
     */
    public function getJustification(): Option
    {
        return $this->justification;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $zoneNumber = None::create();
        $header = None::create();
        $dataField = None::create();
        $literalValue = None::create();
        $justification = None::create();
        if (array_key_exists('zoneNumber', $data) && $data['zoneNumber'] !== null) {
            $zoneNumberRaw = $data['zoneNumber'];
            if (!is_int($zoneNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "zoneNumber" must be int, got %s.', get_debug_type($zoneNumberRaw)),
                );
            }
            $zoneNumber = Some::create($zoneNumberRaw);
        }
        if (array_key_exists('header', $data) && $data['header'] !== null) {
            $headerRaw = $data['header'];
            if (!is_string($headerRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "header" must be string, got %s.', get_debug_type($headerRaw)),
                );
            }
            $header = Some::create($headerRaw);
        }
        if (array_key_exists('dataField', $data) && $data['dataField'] !== null) {
            $dataFieldRaw = $data['dataField'];
            if (!is_string($dataFieldRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dataField" must be string, got %s.', get_debug_type($dataFieldRaw)),
                );
            }
            $dataField = Some::create($dataFieldRaw);
        }
        if (array_key_exists('literalValue', $data) && $data['literalValue'] !== null) {
            $literalValueRaw = $data['literalValue'];
            if (!is_string($literalValueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "literalValue" must be string, got %s.', get_debug_type($literalValueRaw)),
                );
            }
            $literalValue = Some::create($literalValueRaw);
        }
        if (array_key_exists('justification', $data) && $data['justification'] !== null) {
            $justificationRaw = $data['justification'];
            if (!is_string($justificationRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "justification" must be string, got %s.', get_debug_type($justificationRaw)),
                );
            }
            $justification = Some::create(
                DocTabZoneSpecificationJustification::tryFrom($justificationRaw)
                    ?? UnknownEnumValue::of($justificationRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'zoneNumber' => true,
                'header' => true,
                'dataField' => true,
                'literalValue' => true,
                'justification' => true,
            ],
        );

        return new self($zoneNumber, $header, $dataField, $literalValue, $justification, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $zoneNumberOption = $this->zoneNumber;
        if ($zoneNumberOption->isDefined()) {
            $zoneNumber = $zoneNumberOption->get();
            $dataArray['zoneNumber'] = $zoneNumber;
        }
        $headerOption = $this->header;
        if ($headerOption->isDefined()) {
            $header = $headerOption->get();
            $dataArray['header'] = $header;
        }
        $dataFieldOption = $this->dataField;
        if ($dataFieldOption->isDefined()) {
            $dataField = $dataFieldOption->get();
            $dataArray['dataField'] = $dataField;
        }
        $literalValueOption = $this->literalValue;
        if ($literalValueOption->isDefined()) {
            $literalValue = $literalValueOption->get();
            $dataArray['literalValue'] = $literalValue;
        }
        $justificationOption = $this->justification;
        if ($justificationOption->isDefined()) {
            $justification = $justificationOption->get();
            $dataArray['justification'] = $justification->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): DocTabZoneSpecificationBuilder
    {
        return new DocTabZoneSpecificationBuilder(
            $this->zoneNumber,
            $this->header,
            $this->dataField,
            $this->literalValue,
            $this->justification,
            $this->additionalProperties,
        );
    }
}
