<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see EdtCommodityTax}.
 */
final class EdtCommodityTaxBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $harmonizedCode
     * @param Option<EdtTaxDetail1>    $taxes
     * @param Option<Money1>           $total
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $harmonizedCode,
        private Option $taxes,
        private Option $total,
        private array $additionalProperties,
    ) {
    }

    /**
     * Harmonized code is used by customer to classify the product being shipped and define the
     * duties and taxes to be paid.
     */
    public function setHarmonizedCode(string $harmonizedCode): self
    {
        $this->harmonizedCode = Some::create($harmonizedCode);

        return $this;
    }

    /**
     * Estimated duties and taxes detail.
     */
    public function setTaxes(EdtTaxDetail1 $taxes): self
    {
        $this->taxes = Some::create($taxes);

        return $this;
    }

    /**
     * Total of Duties and taxes.
     */
    public function setTotal(Money1 $total): self
    {
        $this->total = Some::create($total);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): EdtCommodityTax
    {
        return new EdtCommodityTax($this->harmonizedCode, $this->taxes, $this->total, $this->additionalProperties);
    }
}
