<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class EdtTaxDetail1TaxRatesItem implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $value
     * @param Option<string>           $currency
     * @param Option<float>            $quantity
     * @param Option<string>           $unitOfMeasure
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $value,
        private Option $currency,
        private Option $quantity,
        private Option $unitOfMeasure,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): EdtTaxDetail1TaxRatesItemBuilder
    {
        return new EdtTaxDetail1TaxRatesItemBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /** @return Option<string> */
    public function getValue(): Option
    {
        return $this->value;
    }

    /** @return Option<string> */
    public function getCurrency(): Option
    {
        return $this->currency;
    }

    /** @return Option<float> */
    public function getQuantity(): Option
    {
        return $this->quantity;
    }

    /** @return Option<string> */
    public function getUnitOfMeasure(): Option
    {
        return $this->unitOfMeasure;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $value = None::create();
        $currency = None::create();
        $quantity = None::create();
        $unitOfMeasure = None::create();
        if (array_key_exists('quantity', $data) && is_int($data['quantity'])) {
            $data['quantity'] = (float) $data['quantity'];
        }
        if (array_key_exists('value', $data) && $data['value'] !== null) {
            $valueRaw = $data['value'];
            if (!is_string($valueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "value" must be string, got %s.', get_debug_type($valueRaw)),
                );
            }
            $value = Some::create($valueRaw);
        }
        if (array_key_exists('currency', $data) && $data['currency'] !== null) {
            $currencyRaw = $data['currency'];
            if (!is_string($currencyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "currency" must be string, got %s.', get_debug_type($currencyRaw)),
                );
            }
            $currency = Some::create($currencyRaw);
        }
        if (array_key_exists('quantity', $data) && $data['quantity'] !== null) {
            $quantityRaw = $data['quantity'];
            if (!(is_float($quantityRaw) || is_int($quantityRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "quantity" must be number, got %s.', get_debug_type($quantityRaw)),
                );
            }
            $quantity = Some::create((float) $quantityRaw);
        }
        if (array_key_exists('unitOfMeasure', $data) && $data['unitOfMeasure'] !== null) {
            $unitOfMeasureRaw = $data['unitOfMeasure'];
            if (!is_string($unitOfMeasureRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "unitOfMeasure" must be string, got %s.', get_debug_type($unitOfMeasureRaw)),
                );
            }
            $unitOfMeasure = Some::create($unitOfMeasureRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['value' => true, 'currency' => true, 'quantity' => true, 'unitOfMeasure' => true],
        );

        return new self($value, $currency, $quantity, $unitOfMeasure, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $valueOption = $this->value;
        if ($valueOption->isDefined()) {
            $value = $valueOption->get();
            $dataArray['value'] = $value;
        }
        $currencyOption = $this->currency;
        if ($currencyOption->isDefined()) {
            $currency = $currencyOption->get();
            $dataArray['currency'] = $currency;
        }
        $quantityOption = $this->quantity;
        if ($quantityOption->isDefined()) {
            $quantity = $quantityOption->get();
            $dataArray['quantity'] = $quantity;
        }
        $unitOfMeasureOption = $this->unitOfMeasure;
        if ($unitOfMeasureOption->isDefined()) {
            $unitOfMeasure = $unitOfMeasureOption->get();
            $dataArray['unitOfMeasure'] = $unitOfMeasure;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): EdtTaxDetail1TaxRatesItemBuilder
    {
        return new EdtTaxDetail1TaxRatesItemBuilder(
            $this->value,
            $this->currency,
            $this->quantity,
            $this->unitOfMeasure,
            $this->additionalProperties,
        );
    }
}
