<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class ErrorResponseVO404 implements SelfNormalizingModel
{
    /**
     * @param Option<string>            $transactionId
     * @param Option<list<CXSError404>> $errors
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $transactionId,
        private Option $errors,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ErrorResponseVO404Builder
    {
        return new ErrorResponseVO404Builder(None::create(), None::create(), []);
    }

    /**
     * The transaction ID is a special set of numbers that defines each transaction.
     *
     * Example: 624deea6-b709-470c-8c39-4b5511281492
     *
     * @return Option<string>
     */
    public function getTransactionId(): Option
    {
        return $this->transactionId;
    }

    /** @return Option<list<CXSError404>> */
    public function getErrors(): Option
    {
        return $this->errors;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $transactionId = None::create();
        $errors = None::create();
        if (array_key_exists('transactionId', $data) && $data['transactionId'] !== null) {
            $transactionIdRaw = $data['transactionId'];
            if (!is_string($transactionIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "transactionId" must be string, got %s.', get_debug_type($transactionIdRaw)),
                );
            }
            $transactionId = Some::create($transactionIdRaw);
        }
        if (array_key_exists('errors', $data) && $data['errors'] !== null) {
            $errorsRaw = $data['errors'];
            if (!(is_array($errorsRaw) && array_is_list($errorsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "errors" must be list, got %s.', get_debug_type($errorsRaw)),
                );
            }
            $errors = Some::create(array_map(static function (mixed $value): CXSError404 {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return CXSError404::fromArray($valueTyped);
            }, $errorsRaw));
        }
        $additionalProperties = array_diff_key($data, ['transactionId' => true, 'errors' => true]);

        return new self($transactionId, $errors, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $transactionIdOption = $this->transactionId;
        if ($transactionIdOption->isDefined()) {
            $transactionId = $transactionIdOption->get();
            $dataArray['transactionId'] = $transactionId;
        }
        $errorsOption = $this->errors;
        if ($errorsOption->isDefined()) {
            $errors = $errorsOption->get();
            $values = [];
            foreach ($errors as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['errors'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ErrorResponseVO404Builder
    {
        return new ErrorResponseVO404Builder($this->transactionId, $this->errors, $this->additionalProperties);
    }
}
