<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ErrorResponseVO403}.
 */
final class ErrorResponseVO403Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>            $transactionId
     * @param Option<list<CXSError403>> $errors
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $transactionId,
        private Option $errors,
        private array $additionalProperties,
    ) {
    }

    /**
     * The transaction ID is a special set of numbers that defines each transaction.
     *
     * Example: 624deea6-b709-470c-8c39-4b5511281492
     */
    public function setTransactionId(string $transactionId): self
    {
        $this->transactionId = Some::create($transactionId);

        return $this;
    }

    /** @param list<CXSError403> $errors */
    public function setErrors(array $errors): self
    {
        $this->errors = Some::create($errors);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ErrorResponseVO403
    {
        return new ErrorResponseVO403($this->transactionId, $this->errors, $this->additionalProperties);
    }
}
