<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ErrorResponseVO500}.
 */
final class ErrorResponseVO500Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>            $transactionId
     * @param Option<string>            $customerTransactionId
     * @param Option<list<CXSError500>> $errors
     * @param array<int|string, mixed>  $additionalProperties
     */
    public function __construct(
        private Option $transactionId,
        private Option $customerTransactionId,
        private Option $errors,
        private array $additionalProperties,
    ) {
    }

    /**
     * The transaction ID is a special set of numbers that defines each transaction.
     *
     * Example: 624deea6-b709-470c-8c39-4b5511281492
     */
    public function setTransactionId(string $transactionId): self
    {
        $this->transactionId = Some::create($transactionId);

        return $this;
    }

    /**
     * This element allows you to assign a unique identifier to your transaction. This element is
     * also returned in the reply and helps you match the request to the reply.
     *
     * Example: AnyCo_order123456789
     */
    public function setCustomerTransactionId(string $customerTransactionId): self
    {
        $this->customerTransactionId = Some::create($customerTransactionId);

        return $this;
    }

    /** @param list<CXSError500> $errors */
    public function setErrors(array $errors): self
    {
        $this->errors = Some::create($errors);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ErrorResponseVO500
    {
        return new ErrorResponseVO500(
            $this->transactionId,
            $this->customerTransactionId,
            $this->errors,
            $this->additionalProperties,
        );
    }
}
