<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_string;
use function sprintf;

final readonly class FullSchemaCancelShipment implements SelfNormalizingModel
{
    /**
     * @param Option<bool>                                                             $emailShipment
     * @param Option<string>                                                           $senderCountryCode
     * @param Option<FullSchemaCancelShipmentDeletionControl|UnknownEnumValue<string>> $deletionControl
     * @param Option<Version>                                                          $version
     * @param array<int|string, mixed>                                                 $additionalProperties
     */
    public function __construct(
        private ShipperAccountNumber $accountNumber,
        private string $trackingNumber,
        private Option $emailShipment,
        private Option $senderCountryCode,
        private Option $deletionControl,
        private Option $version,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        ShipperAccountNumber $accountNumber,
        string $trackingNumber,
    ): FullSchemaCancelShipmentBuilder {
        return new FullSchemaCancelShipmentBuilder(
            $accountNumber,
            $trackingNumber,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The account number (account value) associated with the shipment.
     */
    public function getAccountNumber(): ShipperAccountNumber
    {
        return $this->accountNumber;
    }

    /**
     * A boolean flag passed by Clients to indicate that whether a shipment is a EMAIL
     * shipment(Pending Shipment) or not. Once a shipment is confirmed, it can no longer be
     * cancelled by having this flag as True.
     *
     * @return Option<bool>
     */
    public function getEmailShipment(): Option
    {
        return $this->emailShipment;
    }

    /**
     * The two-letter sender Country code(Ex: US, CA, GB..etc).
     *
     * Example: US
     *
     * <a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     *
     * @return Option<string>
     */
    public function getSenderCountryCode(): Option
    {
        return $this->senderCountryCode;
    }

    /**
     * Specifies which packages in a shipment to be canceled<b>DELETE_ALL_PACKAGES</b> which will
     * cancel all tracking numbers associated to the shipment.
     *
     * @return Option<FullSchemaCancelShipmentDeletionControl|UnknownEnumValue<string>>
     */
    public function getDeletionControl(): Option
    {
        return $this->deletionControl;
    }

    /**
     * This is an unique number assigned by FedEx to the packages for tracking.
     *
     * Example: "794953555571"
     */
    public function getTrackingNumber(): string
    {
        return $this->trackingNumber;
    }

    /** @return Option<Version> */
    public function getVersion(): Option
    {
        return $this->version;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $accountNumber = null;
        $emailShipment = None::create();
        $senderCountryCode = None::create();
        $deletionControl = None::create();
        $trackingNumber = null;
        $version = None::create();
        if (array_key_exists('accountNumber', $data)) {
            $accountNumberRaw = $data['accountNumber'];
            if (!is_array($accountNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "accountNumber" must be object, got %s.', get_debug_type($accountNumberRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $accountNumberRawTyped */
            $accountNumberRawTyped = $accountNumberRaw;
            $accountNumber = ShipperAccountNumber::fromArray($accountNumberRawTyped);
        }
        if (array_key_exists('emailShipment', $data) && $data['emailShipment'] !== null) {
            $emailShipmentRaw = $data['emailShipment'];
            if (!is_bool($emailShipmentRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "emailShipment" must be bool, got %s.', get_debug_type($emailShipmentRaw)),
                );
            }
            $emailShipment = Some::create($emailShipmentRaw);
        }
        if (array_key_exists('senderCountryCode', $data) && $data['senderCountryCode'] !== null) {
            $senderCountryCodeRaw = $data['senderCountryCode'];
            if (!is_string($senderCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "senderCountryCode" must be string, got %s.',
                        get_debug_type($senderCountryCodeRaw),
                    ),
                );
            }
            $senderCountryCode = Some::create($senderCountryCodeRaw);
        }
        if (array_key_exists('deletionControl', $data) && $data['deletionControl'] !== null) {
            $deletionControlRaw = $data['deletionControl'];
            if (!is_string($deletionControlRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deletionControl" must be string, got %s.', get_debug_type($deletionControlRaw)),
                );
            }
            $deletionControl = Some::create(
                FullSchemaCancelShipmentDeletionControl::tryFrom($deletionControlRaw)
                    ?? UnknownEnumValue::of($deletionControlRaw),
            );
        }
        if (array_key_exists('trackingNumber', $data)) {
            $trackingNumberRaw = $data['trackingNumber'];
            if (!is_string($trackingNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "trackingNumber" must be string, got %s.', get_debug_type($trackingNumberRaw)),
                );
            }
            $trackingNumber = $trackingNumberRaw;
        }
        if (array_key_exists('version', $data) && $data['version'] !== null) {
            $versionRaw = $data['version'];
            if (!is_array($versionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "version" must be object, got %s.', get_debug_type($versionRaw)),
                );
            }
            /** @var array<string, mixed> $versionRawTyped */
            $versionRawTyped = $versionRaw;
            $version = Some::create(Version::fromArray($versionRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'accountNumber' => true,
                'emailShipment' => true,
                'senderCountryCode' => true,
                'deletionControl' => true,
                'trackingNumber' => true,
                'version' => true,
            ],
        );
        if ($accountNumber === null) {
            throw new MalformedDataException('Required property "accountNumber" is missing from the document.');
        }
        if ($trackingNumber === null) {
            throw new MalformedDataException('Required property "trackingNumber" is missing from the document.');
        }

        return new self(
            $accountNumber,
            $trackingNumber,
            $emailShipment,
            $senderCountryCode,
            $deletionControl,
            $version,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['accountNumber'] = $normalizationTarget->model($this->accountNumber);
        $emailShipmentOption = $this->emailShipment;
        if ($emailShipmentOption->isDefined()) {
            $emailShipment = $emailShipmentOption->get();
            $dataArray['emailShipment'] = $emailShipment;
        }
        $senderCountryCodeOption = $this->senderCountryCode;
        if ($senderCountryCodeOption->isDefined()) {
            $senderCountryCode = $senderCountryCodeOption->get();
            $dataArray['senderCountryCode'] = $senderCountryCode;
        }
        $deletionControlOption = $this->deletionControl;
        if ($deletionControlOption->isDefined()) {
            $deletionControl = $deletionControlOption->get();
            $dataArray['deletionControl'] = $deletionControl->value;
        }
        $dataArray['trackingNumber'] = $this->trackingNumber;
        $versionOption = $this->version;
        if ($versionOption->isDefined()) {
            $version = $versionOption->get();
            $dataArray['version'] = $normalizationTarget->model($version);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): FullSchemaCancelShipmentBuilder
    {
        return new FullSchemaCancelShipmentBuilder(
            $this->accountNumber,
            $this->trackingNumber,
            $this->emailShipment,
            $this->senderCountryCode,
            $this->deletionControl,
            $this->version,
            $this->additionalProperties,
        );
    }
}
