<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_bool;
use function is_string;
use function sprintf;

final readonly class HazardousCommodityPackingDetail01 implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $packingInstructions
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private bool $cargoAircraftOnly,
        private Option $packingInstructions,
        private array $additionalProperties,
    ) {
    }

    public static function builder(bool $cargoAircraftOnly): HazardousCommodityPackingDetail01Builder
    {
        return new HazardousCommodityPackingDetail01Builder($cargoAircraftOnly, None::create(), []);
    }

    /**
     * Coded specification for how commodity is to be packed.
     *
     * Example: packing Instructions
     *
     * @return Option<string>
     */
    public function getPackingInstructions(): Option
    {
        return $this->packingInstructions;
    }

    /**
     * A Boolean value that, when True, specifies the mode of shipment transportation should be
     * Cargo Aircraft for Dangerous Goods.
     *
     * Note: An identifier DGD-CAO is added in AWB for cargo aircraft shipments.Example: true
     */
    public function getCargoAircraftOnly(): bool
    {
        return $this->cargoAircraftOnly;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $packingInstructions = None::create();
        $cargoAircraftOnly = null;
        if (array_key_exists('packingInstructions', $data) && $data['packingInstructions'] !== null) {
            $packingInstructionsRaw = $data['packingInstructions'];
            if (!is_string($packingInstructionsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "packingInstructions" must be string, got %s.',
                        get_debug_type($packingInstructionsRaw),
                    ),
                );
            }
            $packingInstructions = Some::create($packingInstructionsRaw);
        }
        if (array_key_exists('cargoAircraftOnly', $data)) {
            $cargoAircraftOnlyRaw = $data['cargoAircraftOnly'];
            if (!is_bool($cargoAircraftOnlyRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "cargoAircraftOnly" must be bool, got %s.',
                        get_debug_type($cargoAircraftOnlyRaw),
                    ),
                );
            }
            $cargoAircraftOnly = $cargoAircraftOnlyRaw;
        }
        $additionalProperties = array_diff_key($data, ['packingInstructions' => true, 'cargoAircraftOnly' => true]);
        if ($cargoAircraftOnly === null) {
            throw new MalformedDataException('Required property "cargoAircraftOnly" is missing from the document.');
        }

        return new self($cargoAircraftOnly, $packingInstructions, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $packingInstructionsOption = $this->packingInstructions;
        if ($packingInstructionsOption->isDefined()) {
            $packingInstructions = $packingInstructionsOption->get();
            $dataArray['packingInstructions'] = $packingInstructions;
        }
        $dataArray['cargoAircraftOnly'] = $this->cargoAircraftOnly;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): HazardousCommodityPackingDetail01Builder
    {
        return new HazardousCommodityPackingDetail01Builder(
            $this->cargoAircraftOnly,
            $this->packingInstructions,
            $this->additionalProperties,
        );
    }
}
