<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see HazardousCommodityDescription01}.
 */
final class HazardousCommodityDescription01Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param HazardousCommodityDescription01PackingGroup|UnknownEnumValue<string>                        $packingGroup
     * @param Option<int>                                                                                 $sequenceNumber
     * @param Option<list<HazardousCommodityDescription01ProcessingOptionsItem|UnknownEnumValue<string>>> $processingOptions
     * @param Option<list<string>>                                                                        $subsidiaryClasses
     * @param Option<string>                                                                              $labelText
     * @param Option<string>                                                                              $technicalName
     * @param Option<HazardousCommodityPackingDetail01>                                                   $packingDetails
     * @param Option<string>                                                                              $authorization
     * @param Option<float>                                                                               $percentage
     * @param Option<string>                                                                              $id
     * @param Option<string>                                                                              $properShippingName
     * @param Option<string>                                                                              $hazardClass
     * @param array<int|string, mixed>                                                                    $additionalProperties
     */
    public function __construct(
        private bool $reportableQuantity,
        private HazardousCommodityDescription01PackingGroup|UnknownEnumValue $packingGroup,
        private Option $sequenceNumber,
        private Option $processingOptions,
        private Option $subsidiaryClasses,
        private Option $labelText,
        private Option $technicalName,
        private Option $packingDetails,
        private Option $authorization,
        private Option $percentage,
        private Option $id,
        private Option $properShippingName,
        private Option $hazardClass,
        private array $additionalProperties,
    ) {
    }

    /**
     * Reportable Quantity.
     */
    public function setReportableQuantity(bool $reportableQuantity): self
    {
        $this->reportableQuantity = $reportableQuantity;

        return $this;
    }

    /**
     * Identifies DOT packing group for a hazardous commodity.
     */
    public function setPackingGroup(HazardousCommodityDescription01PackingGroup $packingGroup): self
    {
        $this->packingGroup = $packingGroup;

        return $this;
    }

    /**
     * Required.
     *
     * Specify the sequence number.
     *
     * Example: 9812
     */
    public function setSequenceNumber(int $sequenceNumber): self
    {
        $this->sequenceNumber = Some::create($sequenceNumber);

        return $this;
    }

    /**
     * Indicates any special processing options to be applied to the description of the dangerous
     * goods commodity.
     *
     * Example: ["INCLUDE_SPECIAL_PROVISIONS"]
     *
     * @param list<HazardousCommodityDescription01ProcessingOptionsItem> $processingOptions
     */
    public function setProcessingOptions(array $processingOptions): self
    {
        $this->processingOptions = Some::create($processingOptions);

        return $this;
    }

    /**
     * Required.
     *
     * Indicates list of subsidiary classes
     *
     * Example: ["Subsidiary Classes"]
     *
     * @param list<string> $subsidiaryClasses
     */
    public function setSubsidiaryClasses(array $subsidiaryClasses): self
    {
        $this->subsidiaryClasses = Some::create($subsidiaryClasses);

        return $this;
    }

    /**
     * Specifies the text for the label.
     */
    public function setLabelText(string $labelText): self
    {
        $this->labelText = Some::create($labelText);

        return $this;
    }

    /**
     * Specifies the technical name for the hazardous material.
     */
    public function setTechnicalName(string $technicalName): self
    {
        $this->technicalName = Some::create($technicalName);

        return $this;
    }

    /**
     * Specifies documentation and limits for validation of an individual packing group/category. DG
     * Data Upload Mode: Required (IATA), Optional (Other), DG Full Validation Mode: Required
     * (IATA), Optional (Other),.
     */
    public function setPackingDetails(HazardousCommodityPackingDetail01 $packingDetails): self
    {
        $this->packingDetails = Some::create($packingDetails);

        return $this;
    }

    /**
     * Information related to quantity limitations and operator or state variations as may be
     * applicable to the dangerous goods commodity.
     */
    public function setAuthorization(string $authorization): self
    {
        $this->authorization = Some::create($authorization);

        return $this;
    }

    /**
     * Percentage.
     *
     * Example: 12.45
     */
    public function setPercentage(float $percentage): self
    {
        $this->percentage = Some::create($percentage);

        return $this;
    }

    /**
     * ID.
     *
     * Example: 123
     */
    public function setId(string $id): self
    {
        $this->id = Some::create($id);

        return $this;
    }

    /**
     * The proper shipping name as defined by the regulation. The name can also include qualifying
     * words.
     *
     * Example: properShippingName
     */
    public function setProperShippingName(string $properShippingName): self
    {
        $this->properShippingName = Some::create($properShippingName);

        return $this;
    }

    /**
     * Specifies the hazard class for the commodity.
     *
     * Example: hazard Class
     */
    public function setHazardClass(string $hazardClass): self
    {
        $this->hazardClass = Some::create($hazardClass);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): HazardousCommodityDescription01
    {
        return new HazardousCommodityDescription01(
            $this->reportableQuantity,
            $this->packingGroup,
            $this->sequenceNumber,
            $this->processingOptions,
            $this->subsidiaryClasses,
            $this->labelText,
            $this->technicalName,
            $this->packingDetails,
            $this->authorization,
            $this->percentage,
            $this->id,
            $this->properShippingName,
            $this->hazardClass,
            $this->additionalProperties,
        );
    }
}
