<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see HazardousCommodityInnerReceptacleDetail01}.
 */
final class HazardousCommodityInnerReceptacleDetail01Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<HazardousCommodityQuantityDetail002> $quantity
     * @param array<int|string, mixed>                    $additionalProperties
     */
    public function __construct(private Option $quantity, private array $additionalProperties)
    {
    }

    /**
     * Indicates the Hazardous Commodity Quantity Detail.
     */
    public function setQuantity(HazardousCommodityQuantityDetail002 $quantity): self
    {
        $this->quantity = Some::create($quantity);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): HazardousCommodityInnerReceptacleDetail01
    {
        return new HazardousCommodityInnerReceptacleDetail01($this->quantity, $this->additionalProperties);
    }
}
