<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class HazardousCommodityOptionDetail implements SelfNormalizingModel
{
    /**
     * @param Option<HazardousCommodityOptionDetailLabelTextOption|UnknownEnumValue<string>> $labelTextOption
     * @param Option<string>                                                                 $customerSuppliedLabelText
     * @param array<int|string, mixed>                                                       $additionalProperties
     */
    public function __construct(
        private Option $labelTextOption,
        private Option $customerSuppliedLabelText,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): HazardousCommodityOptionDetailBuilder
    {
        return new HazardousCommodityOptionDetailBuilder(None::create(), None::create(), []);
    }

    /**
     * Provides the label text option.
     *
     * @return Option<HazardousCommodityOptionDetailLabelTextOption|UnknownEnumValue<string>>
     */
    public function getLabelTextOption(): Option
    {
        return $this->labelTextOption;
    }

    /**
     * DG Data Upload Mode:- Optional.
     *
     * DG Full Validation Mode: Optional
     *
     * Text used in labeling the commodity under control of the LabelTextOption field
     *
     * @return Option<string>
     */
    public function getCustomerSuppliedLabelText(): Option
    {
        return $this->customerSuppliedLabelText;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $labelTextOption = None::create();
        $customerSuppliedLabelText = None::create();
        if (array_key_exists('labelTextOption', $data) && $data['labelTextOption'] !== null) {
            $labelTextOptionRaw = $data['labelTextOption'];
            if (!is_string($labelTextOptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "labelTextOption" must be string, got %s.', get_debug_type($labelTextOptionRaw)),
                );
            }
            $labelTextOption = Some::create(
                HazardousCommodityOptionDetailLabelTextOption::tryFrom($labelTextOptionRaw)
                    ?? UnknownEnumValue::of($labelTextOptionRaw),
            );
        }
        if (array_key_exists('customerSuppliedLabelText', $data) && $data['customerSuppliedLabelText'] !== null) {
            $customerSuppliedLabelTextRaw = $data['customerSuppliedLabelText'];
            if (!is_string($customerSuppliedLabelTextRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "customerSuppliedLabelText" must be string, got %s.',
                        get_debug_type($customerSuppliedLabelTextRaw),
                    ),
                );
            }
            $customerSuppliedLabelText = Some::create($customerSuppliedLabelTextRaw);
        }
        $additionalProperties = array_diff_key($data, ['labelTextOption' => true, 'customerSuppliedLabelText' => true]);

        return new self($labelTextOption, $customerSuppliedLabelText, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $labelTextOptionOption = $this->labelTextOption;
        if ($labelTextOptionOption->isDefined()) {
            $labelTextOption = $labelTextOptionOption->get();
            $dataArray['labelTextOption'] = $labelTextOption->value;
        }
        $customerSuppliedLabelTextOption = $this->customerSuppliedLabelText;
        if ($customerSuppliedLabelTextOption->isDefined()) {
            $customerSuppliedLabelText = $customerSuppliedLabelTextOption->get();
            $dataArray['customerSuppliedLabelText'] = $customerSuppliedLabelText;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): HazardousCommodityOptionDetailBuilder
    {
        return new HazardousCommodityOptionDetailBuilder(
            $this->labelTextOption,
            $this->customerSuppliedLabelText,
            $this->additionalProperties,
        );
    }
}
