<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class HazardousCommodityContent001 implements SelfNormalizingModel
{
    /**
     * @param Option<HazardousCommodityQuantityDetail>                $quantity
     * @param Option<list<HazardousCommodityInnerReceptacleDetail01>> $innerReceptacles
     * @param Option<HazardousCommodityOptionDetail01>                $options
     * @param Option<HazardousCommodityDescription01>                 $description
     * @param array<int|string, mixed>                                $additionalProperties
     */
    public function __construct(
        private Option $quantity,
        private Option $innerReceptacles,
        private Option $options,
        private Option $description,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): HazardousCommodityContent001Builder
    {
        return new HazardousCommodityContent001Builder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specify the Hazardous commodity quantity details.
     *
     * @return Option<HazardousCommodityQuantityDetail>
     */
    public function getQuantity(): Option
    {
        return $this->quantity;
    }

    /**
     * Specifies the inner receptacles within the container.
     *
     * @return Option<list<HazardousCommodityInnerReceptacleDetail01>>
     */
    public function getInnerReceptacles(): Option
    {
        return $this->innerReceptacles;
    }

    /**
     * Indicates details of hazardous commodity option detail.
     *
     * @return Option<HazardousCommodityOptionDetail01>
     */
    public function getOptions(): Option
    {
        return $this->options;
    }

    /**
     * Required.
     *
     * Details of hazardous commodity description.
     *
     * @return Option<HazardousCommodityDescription01>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $quantity = None::create();
        $innerReceptacles = None::create();
        $options = None::create();
        $description = None::create();
        if (array_key_exists('quantity', $data) && $data['quantity'] !== null) {
            $quantityRaw = $data['quantity'];
            if (!is_array($quantityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "quantity" must be object, got %s.', get_debug_type($quantityRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $quantityRawTyped */
            $quantityRawTyped = $quantityRaw;
            $quantity = Some::create(HazardousCommodityQuantityDetail::fromArray($quantityRawTyped));
        }
        if (array_key_exists('innerReceptacles', $data) && $data['innerReceptacles'] !== null) {
            $innerReceptaclesRaw = $data['innerReceptacles'];
            if (!(is_array($innerReceptaclesRaw) && array_is_list($innerReceptaclesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "innerReceptacles" must be list, got %s.', get_debug_type($innerReceptaclesRaw)),
                );
            }
            $innerReceptacles = Some::create(
                array_map(static function (mixed $value): HazardousCommodityInnerReceptacleDetail01 {
                    if (!is_array($value)) {
                        throw new MalformedDataException(
                            sprintf('Array item must be object, got %s.', get_debug_type($value)),
                        );
                    }
                    /** @var array<string, mixed> $valueTyped */
                    $valueTyped = $value;

                    return HazardousCommodityInnerReceptacleDetail01::fromArray($valueTyped);
                }, $innerReceptaclesRaw),
            );
        }
        if (array_key_exists('options', $data) && $data['options'] !== null) {
            $optionsRaw = $data['options'];
            if (!is_array($optionsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "options" must be object, got %s.', get_debug_type($optionsRaw)),
                );
            }
            /** @var array<string, mixed> $optionsRawTyped */
            $optionsRawTyped = $optionsRaw;
            $options = Some::create(HazardousCommodityOptionDetail01::fromArray($optionsRawTyped));
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_array($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be object, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $descriptionRawTyped */
            $descriptionRawTyped = $descriptionRaw;
            $description = Some::create(HazardousCommodityDescription01::fromArray($descriptionRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['quantity' => true, 'innerReceptacles' => true, 'options' => true, 'description' => true],
        );

        return new self($quantity, $innerReceptacles, $options, $description, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $quantityOption = $this->quantity;
        if ($quantityOption->isDefined()) {
            $quantity = $quantityOption->get();
            $dataArray['quantity'] = $normalizationTarget->model($quantity);
        }
        $innerReceptaclesOption = $this->innerReceptacles;
        if ($innerReceptaclesOption->isDefined()) {
            $innerReceptacles = $innerReceptaclesOption->get();
            $values = [];
            foreach ($innerReceptacles as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['innerReceptacles'] = $values;
        }
        $optionsOption = $this->options;
        if ($optionsOption->isDefined()) {
            $options = $optionsOption->get();
            $dataArray['options'] = $normalizationTarget->model($options);
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $normalizationTarget->model($description);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): HazardousCommodityContent001Builder
    {
        return new HazardousCommodityContent001Builder(
            $this->quantity,
            $this->innerReceptacles,
            $this->options,
            $this->description,
            $this->additionalProperties,
        );
    }
}
