<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum HazardousCommodityDescription01PackingGroup: string
{
    case DEFAULT = 'DEFAULT';
    case I = 'I';
    case II = 'II';
    case III = 'III';
}
