<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum InternationalControlledExportDetailType: string
{
    case DEA_036 = 'DEA_036';
    case DEA_236 = 'DEA_236';
    case DSP_05 = 'DSP_05';
    case DSP_61 = 'DSP_61';
    case DSP_73 = 'DSP_73';
    case DSP_85 = 'DSP_85';
    case DSP_LICENSE_AGREEMENT = 'DSP_LICENSE_AGREEMENT';
    case WAREHOUSE_WITHDRAWAL = 'WAREHOUSE_WITHDRAWAL';
    case FROM_FOREIGN_TRADE_ZONE = 'FROM_FOREIGN_TRADE_ZONE';
    case DEA_486 = 'DEA_486';
    case DSP_94 = 'DSP_94';
}
