<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum LabelSpecificationImageType: string
{
    case ZPLII = 'ZPLII';
    case EPL2 = 'EPL2';
    case PDF = 'PDF';
    case PNG = 'PNG';
}
