<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see LabelSpecification}.
 */
final class LabelSpecificationBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param LabelSpecificationLabelStockType|UnknownEnumValue<string>                   $labelStockType
     * @param LabelSpecificationImageType|UnknownEnumValue<string>                        $imageType
     * @param Option<LabelSpecificationLabelFormatType|UnknownEnumValue<string>>          $labelFormatType
     * @param Option<LabelSpecificationLabelOrder|UnknownEnumValue<string>>               $labelOrder
     * @param Option<CustomerSpecifiedLabelDetail>                                        $customerSpecifiedDetail
     * @param Option<ContactAndAddress>                                                   $printedLabelOrigin
     * @param Option<LabelSpecificationLabelRotation|UnknownEnumValue<string>>            $labelRotation
     * @param Option<LabelSpecificationLabelPrintingOrientation|UnknownEnumValue<string>> $labelPrintingOrientation
     * @param Option<string>                                                              $returnedDispositionDetail
     * @param Option<int>                                                                 $resolution
     * @param array<int|string, mixed>                                                    $additionalProperties
     */
    public function __construct(
        private LabelSpecificationLabelStockType|UnknownEnumValue $labelStockType,
        private LabelSpecificationImageType|UnknownEnumValue $imageType,
        private Option $labelFormatType,
        private Option $labelOrder,
        private Option $customerSpecifiedDetail,
        private Option $printedLabelOrigin,
        private Option $labelRotation,
        private Option $labelPrintingOrientation,
        private Option $returnedDispositionDetail,
        private Option $resolution,
        private array $additionalProperties,
    ) {
    }

    /**
     * Label Stock Type.
     *
     * Example: PAPER_7X475
     */
    public function setLabelStockType(LabelSpecificationLabelStockType $labelStockType): self
    {
        $this->labelStockType = $labelStockType;

        return $this;
    }

    /**
     * Specifies the image type of this shipping document.
     *
     * Example:PDF
     */
    public function setImageType(LabelSpecificationImageType $imageType): self
    {
        $this->imageType = $imageType;

        return $this;
    }

    /**
     * Specifies the label Format Type.
     *
     * Example: COMMON2D
     */
    public function setLabelFormatType(LabelSpecificationLabelFormatType $labelFormatType): self
    {
        $this->labelFormatType = Some::create($labelFormatType);

        return $this;
    }

    /**
     * This is the order of the Shipping label/documents to be generated.
     */
    public function setLabelOrder(LabelSpecificationLabelOrder $labelOrder): self
    {
        $this->labelOrder = Some::create($labelOrder);

        return $this;
    }

    /**
     * This object allows the control of label content for customization.
     */
    public function setCustomerSpecifiedDetail(CustomerSpecifiedLabelDetail $customerSpecifiedDetail): self
    {
        $this->customerSpecifiedDetail = Some::create($customerSpecifiedDetail);

        return $this;
    }

    /**
     * Specifies the contact and address details of a location.
     */
    public function setPrintedLabelOrigin(ContactAndAddress $printedLabelOrigin): self
    {
        $this->printedLabelOrigin = Some::create($printedLabelOrigin);

        return $this;
    }

    /**
     * This is applicable only to documents produced on thermal printers with roll stock.
     */
    public function setLabelRotation(LabelSpecificationLabelRotation $labelRotation): self
    {
        $this->labelRotation = Some::create($labelRotation);

        return $this;
    }

    /**
     * This is applicable only to documents produced on thermal printers with roll stock.
     */
    public function setLabelPrintingOrientation(
        LabelSpecificationLabelPrintingOrientation $labelPrintingOrientation,
    ): self {
        $this->labelPrintingOrientation = Some::create($labelPrintingOrientation);

        return $this;
    }

    /**
     * Specifies a particular way in which a kind of shipping document is to be produced and
     * provided.
     *
     * Example:RETURNED
     */
    public function setReturnedDispositionDetail(string $returnedDispositionDetail): self
    {
        $this->returnedDispositionDetail = Some::create($returnedDispositionDetail);

        return $this;
    }

    /**
     * Specifies the image resolution in DPI (Dots Per Inch). Valid values are 203 & 300. If not
     * provided or for any other value, system will default it to 203.Note: 300 DPI resolution is
     * only allowed for ZPLII image type.
     */
    public function setResolution(int $resolution): self
    {
        $this->resolution = Some::create($resolution);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LabelSpecification
    {
        return new LabelSpecification(
            $this->labelStockType,
            $this->imageType,
            $this->labelFormatType,
            $this->labelOrder,
            $this->customerSpecifiedDetail,
            $this->printedLabelOrigin,
            $this->labelRotation,
            $this->labelPrintingOrientation,
            $this->returnedDispositionDetail,
            $this->resolution,
            $this->additionalProperties,
        );
    }
}
