<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class LicenseOrPermitDetail implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $number
     * @param Option<string>           $effectiveDate
     * @param Option<string>           $expirationDate
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $number,
        private Option $effectiveDate,
        private Option $expirationDate,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): LicenseOrPermitDetailBuilder
    {
        return new LicenseOrPermitDetailBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * Specifies license or permit detail number.
     *
     * Example: 12345
     *
     * @return Option<string>
     */
    public function getNumber(): Option
    {
        return $this->number;
    }

    /**
     * Specifies the effective date of the license.
     *
     * The format is [YYYY-MM-DD].
     *
     * Example: 2019-08-09
     *
     * @return Option<string>
     */
    public function getEffectiveDate(): Option
    {
        return $this->effectiveDate;
    }

    /**
     * Specifies the expiration date of the license.
     *
     * The format is [YYYY-MM-DD].
     *
     * Example: 2019-04-09
     *
     * @return Option<string>
     */
    public function getExpirationDate(): Option
    {
        return $this->expirationDate;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $number = None::create();
        $effectiveDate = None::create();
        $expirationDate = None::create();
        if (array_key_exists('number', $data) && $data['number'] !== null) {
            $numberRaw = $data['number'];
            if (!is_string($numberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "number" must be string, got %s.', get_debug_type($numberRaw)),
                );
            }
            $number = Some::create($numberRaw);
        }
        if (array_key_exists('effectiveDate', $data) && $data['effectiveDate'] !== null) {
            $effectiveDateRaw = $data['effectiveDate'];
            if (!is_string($effectiveDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "effectiveDate" must be string, got %s.', get_debug_type($effectiveDateRaw)),
                );
            }
            $effectiveDate = Some::create($effectiveDateRaw);
        }
        if (array_key_exists('expirationDate', $data) && $data['expirationDate'] !== null) {
            $expirationDateRaw = $data['expirationDate'];
            if (!is_string($expirationDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "expirationDate" must be string, got %s.', get_debug_type($expirationDateRaw)),
                );
            }
            $expirationDate = Some::create($expirationDateRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['number' => true, 'effectiveDate' => true, 'expirationDate' => true],
        );

        return new self($number, $effectiveDate, $expirationDate, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $numberOption = $this->number;
        if ($numberOption->isDefined()) {
            $number = $numberOption->get();
            $dataArray['number'] = $number;
        }
        $effectiveDateOption = $this->effectiveDate;
        if ($effectiveDateOption->isDefined()) {
            $effectiveDate = $effectiveDateOption->get();
            $dataArray['effectiveDate'] = $effectiveDate;
        }
        $expirationDateOption = $this->expirationDate;
        if ($expirationDateOption->isDefined()) {
            $expirationDate = $expirationDateOption->get();
            $dataArray['expirationDate'] = $expirationDate;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): LicenseOrPermitDetailBuilder
    {
        return new LicenseOrPermitDetailBuilder(
            $this->number,
            $this->effectiveDate,
            $this->expirationDate,
            $this->additionalProperties,
        );
    }
}
