<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see LicenseOrPermitDetail}.
 */
final class LicenseOrPermitDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $number
     * @param Option<string>           $effectiveDate
     * @param Option<string>           $expirationDate
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $number,
        private Option $effectiveDate,
        private Option $expirationDate,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specifies license or permit detail number.
     *
     * Example: 12345
     */
    public function setNumber(string $number): self
    {
        $this->number = Some::create($number);

        return $this;
    }

    /**
     * Specifies the effective date of the license.
     *
     * The format is [YYYY-MM-DD].
     *
     * Example: 2019-08-09
     */
    public function setEffectiveDate(string $effectiveDate): self
    {
        $this->effectiveDate = Some::create($effectiveDate);

        return $this;
    }

    /**
     * Specifies the expiration date of the license.
     *
     * The format is [YYYY-MM-DD].
     *
     * Example: 2019-04-09
     */
    public function setExpirationDate(string $expirationDate): self
    {
        $this->expirationDate = Some::create($expirationDate);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): LicenseOrPermitDetail
    {
        return new LicenseOrPermitDetail(
            $this->number,
            $this->effectiveDate,
            $this->expirationDate,
            $this->additionalProperties,
        );
    }
}
