<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see Message}.
 */
final class MessageBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                 $code
     * @param Option<string>                 $text
     * @param Option<list<MessageParameter>> $parameters
     * @param Option<string>                 $localizedText
     * @param array<int|string, mixed>       $additionalProperties
     */
    public function __construct(
        private Option $code,
        private Option $text,
        private Option $parameters,
        private Option $localizedText,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specifies the message code for the tag created.
     *
     * Example: code
     */
    public function setCode(string $code): self
    {
        $this->code = Some::create($code);

        return $this;
    }

    /**
     * Specifies the text message for the tag created.
     *
     * Example: Text
     */
    public function setText(string $text): self
    {
        $this->text = Some::create($text);

        return $this;
    }

    /**
     * Specifies the message parameters list.
     *
     * @param list<MessageParameter> $parameters
     */
    public function setParameters(array $parameters): self
    {
        $this->parameters = Some::create($parameters);

        return $this;
    }

    /**
     * Specifies the message ID and value.
     *
     * Example: localizedText
     */
    public function setLocalizedText(string $localizedText): self
    {
        $this->localizedText = Some::create($localizedText);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Message
    {
        return new Message(
            $this->code,
            $this->text,
            $this->parameters,
            $this->localizedText,
            $this->additionalProperties,
        );
    }
}
