<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Money1 implements SelfNormalizingModel
{
    /**
     * @param Money1Value|UnknownEnumValue<string> $value
     * @param Option<string>                       $currency
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private Money1Value|UnknownEnumValue $value,
        private Option $currency,
        private array $additionalProperties,
    ) {
    }

    public static function builder(Money1Value $value): Money1Builder
    {
        return new Money1Builder($value, None::create(), []);
    }

    /**
     * Three-character currency code (e.g. USD, CAD, EUR, JPY, etc.).
     *
     * <a href="/developer-portal/en-us/reference-guide.html#currencycodes" target="_blank">Click
     * here to see Currency Codes</a>
     *
     * @return Option<string>
     */
    public function getCurrency(): Option
    {
        return $this->currency;
    }

    /**
     * Specify the value.
     *
     * @return Money1Value|UnknownEnumValue<string>
     */
    public function getValue(): Money1Value|UnknownEnumValue
    {
        return $this->value;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $currency = None::create();
        $value = null;
        if (array_key_exists('currency', $data) && $data['currency'] !== null) {
            $currencyRaw = $data['currency'];
            if (!is_string($currencyRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "currency" must be string, got %s.', get_debug_type($currencyRaw)),
                );
            }
            $currency = Some::create($currencyRaw);
        }
        if (array_key_exists('value', $data)) {
            $valueRaw = $data['value'];
            if (!is_string($valueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "value" must be string, got %s.', get_debug_type($valueRaw)),
                );
            }
            $value = Money1Value::tryFrom($valueRaw) ?? UnknownEnumValue::of($valueRaw);
        }
        $additionalProperties = array_diff_key($data, ['currency' => true, 'value' => true]);
        if ($value === null) {
            throw new MalformedDataException('Required property "value" is missing from the document.');
        }

        return new self($value, $currency, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $currencyOption = $this->currency;
        if ($currencyOption->isDefined()) {
            $currency = $currencyOption->get();
            $dataArray['currency'] = $currency;
        }
        $dataArray['value'] = $this->value->value;
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): Money1Builder
    {
        return new Money1Builder($this->value, $this->currency, $this->additionalProperties);
    }
}
