<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see OperationalInstructions}.
 */
final class OperationalInstructionsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<int>              $number
     * @param Option<string>           $content
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $number, private Option $content, private array $additionalProperties)
    {
    }

    /**
     * Specifies the number of operational instructions returned for this shipment.
     *
     * Example: 17
     */
    public function setNumber(int $number): self
    {
        $this->number = Some::create($number);

        return $this;
    }

    /**
     * This is an operational instruction printed or available on the shipping document.
     *
     * Example: SECURED
     */
    public function setContent(string $content): self
    {
        $this->content = Some::create($content);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): OperationalInstructions
    {
        return new OperationalInstructions($this->number, $this->content, $this->additionalProperties);
    }
}
