<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class PackageBarcodes implements SelfNormalizingModel
{
    /**
     * @param Option<list<BinaryBarcode>> $binaryBarcodes
     * @param Option<list<StringBarcode>> $stringBarcodes
     * @param array<int|string, mixed>    $additionalProperties
     */
    public function __construct(
        private Option $binaryBarcodes,
        private Option $stringBarcodes,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): PackageBarcodesBuilder
    {
        return new PackageBarcodesBuilder(None::create(), None::create(), []);
    }

    /**
     * This is binary-style barcodes used for the package identification.
     *
     * @return Option<list<BinaryBarcode>>
     */
    public function getBinaryBarcodes(): Option
    {
        return $this->binaryBarcodes;
    }

    /**
     * This is string-style barcodes used for package identification.
     *
     * @return Option<list<StringBarcode>>
     */
    public function getStringBarcodes(): Option
    {
        return $this->stringBarcodes;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $binaryBarcodes = None::create();
        $stringBarcodes = None::create();
        if (array_key_exists('binaryBarcodes', $data) && $data['binaryBarcodes'] !== null) {
            $binaryBarcodesRaw = $data['binaryBarcodes'];
            if (!(is_array($binaryBarcodesRaw) && array_is_list($binaryBarcodesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "binaryBarcodes" must be list, got %s.', get_debug_type($binaryBarcodesRaw)),
                );
            }
            $binaryBarcodes = Some::create(array_map(static function (mixed $value): BinaryBarcode {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return BinaryBarcode::fromArray($valueTyped);
            }, $binaryBarcodesRaw));
        }
        if (array_key_exists('stringBarcodes', $data) && $data['stringBarcodes'] !== null) {
            $stringBarcodesRaw = $data['stringBarcodes'];
            if (!(is_array($stringBarcodesRaw) && array_is_list($stringBarcodesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "stringBarcodes" must be list, got %s.', get_debug_type($stringBarcodesRaw)),
                );
            }
            $stringBarcodes = Some::create(array_map(static function (mixed $value_1): StringBarcode {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return StringBarcode::fromArray($value_1Typed);
            }, $stringBarcodesRaw));
        }
        $additionalProperties = array_diff_key($data, ['binaryBarcodes' => true, 'stringBarcodes' => true]);

        return new self($binaryBarcodes, $stringBarcodes, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $binaryBarcodesOption = $this->binaryBarcodes;
        if ($binaryBarcodesOption->isDefined()) {
            $binaryBarcodes = $binaryBarcodesOption->get();
            $values = [];
            foreach ($binaryBarcodes as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['binaryBarcodes'] = $values;
        }
        $stringBarcodesOption = $this->stringBarcodes;
        if ($stringBarcodesOption->isDefined()) {
            $stringBarcodes = $stringBarcodesOption->get();
            $values_1 = [];
            foreach ($stringBarcodes as $value_1) {
                $values_1[] = $normalizationTarget->model($value_1);
            }
            $dataArray['stringBarcodes'] = $values_1;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PackageBarcodesBuilder
    {
        return new PackageBarcodesBuilder($this->binaryBarcodes, $this->stringBarcodes, $this->additionalProperties);
    }
}
