<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see PackageRating}.
 */
final class PackageRatingBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<float>                   $effectiveNetDiscount
     * @param Option<string>                  $actualRateType
     * @param Option<list<PackageRateDetail>> $packageRateDetails
     * @param array<int|string, mixed>        $additionalProperties
     */
    public function __construct(
        private Option $effectiveNetDiscount,
        private Option $actualRateType,
        private Option $packageRateDetails,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is the difference between the list and account net charge.
     *
     * Example: 0.0
     */
    public function setEffectiveNetDiscount(float $effectiveNetDiscount): self
    {
        $this->effectiveNetDiscount = Some::create($effectiveNetDiscount);

        return $this;
    }

    /**
     * This is the actual rate type. It identifies which entry in the following array is considered
     * as presenting the actual rates for the package.
     *
     * Example: PAYOR_ACCOUNT_PACKAGE
     */
    public function setActualRateType(string $actualRateType): self
    {
        $this->actualRateType = Some::create($actualRateType);

        return $this;
    }

    /**
     * Data for a package's rates, as calculated per a specific rate type.
     *
     * @param list<PackageRateDetail> $packageRateDetails
     */
    public function setPackageRateDetails(array $packageRateDetails): self
    {
        $this->packageRateDetails = Some::create($packageRateDetails);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PackageRating
    {
        return new PackageRating(
            $this->effectiveNetDiscount,
            $this->actualRateType,
            $this->packageRateDetails,
            $this->additionalProperties,
        );
    }
}
