<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class PackageCODDetail implements SelfNormalizingModel
{
    /**
     * @param Option<Money>            $codCollectionAmount
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $codCollectionAmount, private array $additionalProperties)
    {
    }

    public static function builder(): PackageCODDetailBuilder
    {
        return new PackageCODDetailBuilder(None::create(), []);
    }

    /**
     * Indicate the COD collection amount.
     *
     * @return Option<Money>
     */
    public function getCodCollectionAmount(): Option
    {
        return $this->codCollectionAmount;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $codCollectionAmount = None::create();
        if (array_key_exists('codCollectionAmount', $data) && $data['codCollectionAmount'] !== null) {
            $codCollectionAmountRaw = $data['codCollectionAmount'];
            if (!is_array($codCollectionAmountRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "codCollectionAmount" must be object, got %s.',
                        get_debug_type($codCollectionAmountRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $codCollectionAmountRawTyped */
            $codCollectionAmountRawTyped = $codCollectionAmountRaw;
            $codCollectionAmount = Some::create(Money::fromArray($codCollectionAmountRawTyped));
        }
        $additionalProperties = array_diff_key($data, ['codCollectionAmount' => true]);

        return new self($codCollectionAmount, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $codCollectionAmountOption = $this->codCollectionAmount;
        if ($codCollectionAmountOption->isDefined()) {
            $codCollectionAmount = $codCollectionAmountOption->get();
            $dataArray['codCollectionAmount'] = $normalizationTarget->model($codCollectionAmount);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PackageCODDetailBuilder
    {
        return new PackageCODDetailBuilder($this->codCollectionAmount, $this->additionalProperties);
    }
}
