<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see PackageBarcodes}.
 */
final class PackageBarcodesBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<BinaryBarcode>> $binaryBarcodes
     * @param Option<list<StringBarcode>> $stringBarcodes
     * @param array<int|string, mixed>    $additionalProperties
     */
    public function __construct(
        private Option $binaryBarcodes,
        private Option $stringBarcodes,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is binary-style barcodes used for the package identification.
     *
     * @param list<BinaryBarcode> $binaryBarcodes
     */
    public function setBinaryBarcodes(array $binaryBarcodes): self
    {
        $this->binaryBarcodes = Some::create($binaryBarcodes);

        return $this;
    }

    /**
     * This is string-style barcodes used for package identification.
     *
     * @param list<StringBarcode> $stringBarcodes
     */
    public function setStringBarcodes(array $stringBarcodes): self
    {
        $this->stringBarcodes = Some::create($stringBarcodes);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PackageBarcodes
    {
        return new PackageBarcodes($this->binaryBarcodes, $this->stringBarcodes, $this->additionalProperties);
    }
}
