<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see PartyAddress2}.
 */
final class PartyAddress2Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param list<string>             $streetLines
     * @param Option<string>           $stateOrProvinceCode
     * @param Option<string>           $postalCode
     * @param Option<bool>             $residential
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private array $streetLines,
        private string $city,
        private string $countryCode,
        private Option $stateOrProvinceCode,
        private Option $postalCode,
        private Option $residential,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is the Combination of number, street name, etc. At least one line is required for a
     * valid physical address. Empty lines should not be included. Max Length is 35.
     *
     * Note - For FedEx Ground Economy, a maximum of 30 characters will be printed on the label,
     * excess characters will be truncated.
     *
     * @param list<string> $streetLines
     */
    public function setStreetLines(array $streetLines): self
    {
        $this->streetLines = $streetLines;

        return $this;
    }

    /**
     * The name of city, town of the recipient.Max length is 35.
     *
     * Example: Beverly Hills
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * This is the two-letter country code.
     *
     * Maximum length is 2.
     *
     * Example: US
     *
     * <a onclick='loadDocReference("countrycodes")'>click here to see Country codes</a>
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * It is used to identify the principal subdivisions (e.g., provinces or states) of countries.
     * The Format and presence of this field may vary depending on the country. Note: For specific
     * countries, such as the United States and Canada, and Puerto Rico, there is a two-character
     * state, province, codes limit . Example: TX.
     */
    public function setStateOrProvinceCode(string $stateOrProvinceCode): self
    {
        $this->stateOrProvinceCode = Some::create($stateOrProvinceCode);

        return $this;
    }

    /**
     * This is the postal code.
     *
     * Note: This is Optional for non postal-aware countries. Maximum length is 10.
     *
     * Example: 65247
     *
     * <a onclick='loadDocReference("postalawarecountries")'>click here to see Postal aware
     * countries</a>
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * Indicates whether this address is residential (as opposed to commercial).
     *
     * Example: false
     */
    public function setResidential(bool $residential): self
    {
        $this->residential = Some::create($residential);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PartyAddress2
    {
        return new PartyAddress2(
            $this->streetLines,
            $this->city,
            $this->countryCode,
            $this->stateOrProvinceCode,
            $this->postalCode,
            $this->residential,
            $this->additionalProperties,
        );
    }
}
