<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see Party1}.
 */
final class Party1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<PartyAddress>                 $address
     * @param Option<PartyAccountNumber>           $accountNumber
     * @param Option<list<TaxpayerIdentification>> $tins
     * @param array<int|string, mixed>             $additionalProperties
     */
    public function __construct(
        private PartyContact $contact,
        private Option $address,
        private Option $accountNumber,
        private Option $tins,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicate the contact details for this shipment.
     */
    public function setContact(PartyContact $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    /**
     * This is detailed information on physical location. May be used as an actual physical address
     * (place to which one could go), or as a container of address parts which should be handled as
     * a unit (such as a city-state-ZIP combination within the US).
     */
    public function setAddress(PartyAddress $address): self
    {
        $this->address = Some::create($address);

        return $this;
    }

    /**
     * This is FedEx Account number details.
     */
    public function setAccountNumber(PartyAccountNumber $accountNumber): self
    {
        $this->accountNumber = Some::create($accountNumber);

        return $this;
    }

    /**
     * This is the tax identification number details.
     *
     * @param list<TaxpayerIdentification> $tins
     */
    public function setTins(array $tins): self
    {
        $this->tins = Some::create($tins);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Party1
    {
        return new Party1(
            $this->contact,
            $this->address,
            $this->accountNumber,
            $this->tins,
            $this->additionalProperties,
        );
    }
}
