<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class PartyContact1 implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $personName
     * @param Option<string>           $emailAddress
     * @param Option<string>           $phoneExtension
     * @param Option<string>           $phoneNumber
     * @param Option<string>           $companyName
     * @param Option<string>           $faxNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $personName,
        private Option $emailAddress,
        private Option $phoneExtension,
        private Option $phoneNumber,
        private Option $companyName,
        private Option $faxNumber,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): PartyContact1Builder
    {
        return new PartyContact1Builder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specify contact name. First 35 chars will be printed on the label, excess characters will be
     * truncated.
     *
     * Example: John Taylor
     *
     * @return Option<string>
     */
    public function getPersonName(): Option
    {
        return $this->personName;
    }

    /**
     * Specify contact email address. Maximum length is 80.
     *
     * Example: sample@company.com
     *
     * @return Option<string>
     */
    public function getEmailAddress(): Option
    {
        return $this->emailAddress;
    }

    /**
     * Specify contact phone extension. Maximum length is 6.
     *
     * Example: 1234
     *
     * @return Option<string>
     */
    public function getPhoneExtension(): Option
    {
        return $this->phoneExtension;
    }

    /**
     * Specify contact phone number.
     *
     * Minimum length is 1 and supports maximum of 15 for certain countries using longer phone
     * numbers.
     *
     * Note: For US and CA, a phone number must have exactly 10 digits, plus an optional leading
     * country code of '1' or '+1'.
     *
     * Example: 918xxxxx890
     *
     * @return Option<string>
     */
    public function getPhoneNumber(): Option
    {
        return $this->phoneNumber;
    }

    /**
     * Specify contact company name.
     *
     * Recommended length is 35.
     *
     * Note: There's no specific validation of the company name.
     *
     * @return Option<string>
     */
    public function getCompanyName(): Option
    {
        return $this->companyName;
    }

    /**
     * Specify contact person's fax number. Maximum length is 15.
     *
     * @return Option<string>
     */
    public function getFaxNumber(): Option
    {
        return $this->faxNumber;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $personName = None::create();
        $emailAddress = None::create();
        $phoneExtension = None::create();
        $phoneNumber = None::create();
        $companyName = None::create();
        $faxNumber = None::create();
        if (array_key_exists('personName', $data) && $data['personName'] !== null) {
            $personNameRaw = $data['personName'];
            if (!is_string($personNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "personName" must be string, got %s.', get_debug_type($personNameRaw)),
                );
            }
            $personName = Some::create($personNameRaw);
        }
        if (array_key_exists('emailAddress', $data) && $data['emailAddress'] !== null) {
            $emailAddressRaw = $data['emailAddress'];
            if (!is_string($emailAddressRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "emailAddress" must be string, got %s.', get_debug_type($emailAddressRaw)),
                );
            }
            $emailAddress = Some::create($emailAddressRaw);
        }
        if (array_key_exists('phoneExtension', $data) && $data['phoneExtension'] !== null) {
            $phoneExtensionRaw = $data['phoneExtension'];
            if (!is_string($phoneExtensionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "phoneExtension" must be string, got %s.', get_debug_type($phoneExtensionRaw)),
                );
            }
            $phoneExtension = Some::create($phoneExtensionRaw);
        }
        if (array_key_exists('phoneNumber', $data) && $data['phoneNumber'] !== null) {
            $phoneNumberRaw = $data['phoneNumber'];
            if (!is_string($phoneNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "phoneNumber" must be string, got %s.', get_debug_type($phoneNumberRaw)),
                );
            }
            $phoneNumber = Some::create($phoneNumberRaw);
        }
        if (array_key_exists('companyName', $data) && $data['companyName'] !== null) {
            $companyNameRaw = $data['companyName'];
            if (!is_string($companyNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "companyName" must be string, got %s.', get_debug_type($companyNameRaw)),
                );
            }
            $companyName = Some::create($companyNameRaw);
        }
        if (array_key_exists('faxNumber', $data) && $data['faxNumber'] !== null) {
            $faxNumberRaw = $data['faxNumber'];
            if (!is_string($faxNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "faxNumber" must be string, got %s.', get_debug_type($faxNumberRaw)),
                );
            }
            $faxNumber = Some::create($faxNumberRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'personName' => true,
                'emailAddress' => true,
                'phoneExtension' => true,
                'phoneNumber' => true,
                'companyName' => true,
                'faxNumber' => true,
            ],
        );

        return new self(
            $personName,
            $emailAddress,
            $phoneExtension,
            $phoneNumber,
            $companyName,
            $faxNumber,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $personNameOption = $this->personName;
        if ($personNameOption->isDefined()) {
            $personName = $personNameOption->get();
            $dataArray['personName'] = $personName;
        }
        $emailAddressOption = $this->emailAddress;
        if ($emailAddressOption->isDefined()) {
            $emailAddress = $emailAddressOption->get();
            $dataArray['emailAddress'] = $emailAddress;
        }
        $phoneExtensionOption = $this->phoneExtension;
        if ($phoneExtensionOption->isDefined()) {
            $phoneExtension = $phoneExtensionOption->get();
            $dataArray['phoneExtension'] = $phoneExtension;
        }
        $phoneNumberOption = $this->phoneNumber;
        if ($phoneNumberOption->isDefined()) {
            $phoneNumber = $phoneNumberOption->get();
            $dataArray['phoneNumber'] = $phoneNumber;
        }
        $companyNameOption = $this->companyName;
        if ($companyNameOption->isDefined()) {
            $companyName = $companyNameOption->get();
            $dataArray['companyName'] = $companyName;
        }
        $faxNumberOption = $this->faxNumber;
        if ($faxNumberOption->isDefined()) {
            $faxNumber = $faxNumberOption->get();
            $dataArray['faxNumber'] = $faxNumber;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PartyContact1Builder
    {
        return new PartyContact1Builder(
            $this->personName,
            $this->emailAddress,
            $this->phoneExtension,
            $this->phoneNumber,
            $this->companyName,
            $this->faxNumber,
            $this->additionalProperties,
        );
    }
}
