<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class Payor implements SelfNormalizingModel
{
    /** @param array<int|string, mixed> $additionalProperties */
    public function __construct(private ResponsiblePartyParty $responsibleParty, private array $additionalProperties)
    {
    }

    public static function builder(ResponsiblePartyParty $responsibleParty): PayorBuilder
    {
        return new PayorBuilder($responsibleParty, []);
    }

    /**
     * Indicate the payer Information responsible for paying for the shipment.
     *
     * Note: ResponsibleParty accountNumber is required for ACCOUNT based services.
     */
    public function getResponsibleParty(): ResponsiblePartyParty
    {
        return $this->responsibleParty;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $responsibleParty = null;
        if (array_key_exists('responsibleParty', $data)) {
            $responsiblePartyRaw = $data['responsibleParty'];
            if (!is_array($responsiblePartyRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "responsibleParty" must be object, got %s.',
                        get_debug_type($responsiblePartyRaw),
                    ),
                );
            }
            /** @var non-empty-array<string, mixed> $responsiblePartyRawTyped */
            $responsiblePartyRawTyped = $responsiblePartyRaw;
            $responsibleParty = ResponsiblePartyParty::fromArray($responsiblePartyRawTyped);
        }
        $additionalProperties = array_diff_key($data, ['responsibleParty' => true]);
        if ($responsibleParty === null) {
            throw new MalformedDataException('Required property "responsibleParty" is missing from the document.');
        }

        return new self($responsibleParty, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['responsibleParty'] = $normalizationTarget->model($this->responsibleParty);
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): PayorBuilder
    {
        return new PayorBuilder($this->responsibleParty, $this->additionalProperties);
    }
}
