<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use DateTime;
use DateTimeInterface;
use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class PickupDetail implements SelfNormalizingModel
{
    /**
     * @param Option<DateTimeInterface>                                $readyPickupDateTime
     * @param Option<DateTimeInterface>                                $latestPickupDateTime
     * @param Option<string>                                           $courierInstructions
     * @param Option<PickupRequestType|UnknownEnumValue<string>>       $requestType
     * @param Option<PickupRequestSourceType|UnknownEnumValue<string>> $requestSource
     * @param array<int|string, mixed>                                 $additionalProperties
     */
    public function __construct(
        private Option $readyPickupDateTime,
        private Option $latestPickupDateTime,
        private Option $courierInstructions,
        private Option $requestType,
        private Option $requestSource,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): PickupDetailBuilder
    {
        return new PickupDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Pickup ready date in YYYY-MM-DD format, Required when requestType is 'FUTURE_DAY'.
     *
     * @return Option<DateTimeInterface>
     */
    public function getReadyPickupDateTime(): Option
    {
        return $this->readyPickupDateTime;
    }

    /**
     * Latest pickup date in YYYY-MM-DD format,Required when requestType is 'FUTURE_DAY'.
     *
     * @return Option<DateTimeInterface>
     */
    public function getLatestPickupDateTime(): Option
    {
        return $this->latestPickupDateTime;
    }

    /**
     * Special instructions for the courier.
     *
     * @return Option<string>
     */
    public function getCourierInstructions(): Option
    {
        return $this->courierInstructions;
    }

    /**
     * Type of pickup request.
     *
     * Example:FUTURE_DAY
     *
     * @return Option<PickupRequestType|UnknownEnumValue<string>>
     */
    public function getRequestType(): Option
    {
        return $this->requestType;
    }

    /**
     * Source of the pickup request.
     *
     * @return Option<PickupRequestSourceType|UnknownEnumValue<string>>
     */
    public function getRequestSource(): Option
    {
        return $this->requestSource;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $readyPickupDateTime = None::create();
        $latestPickupDateTime = None::create();
        $courierInstructions = None::create();
        $requestType = None::create();
        $requestSource = None::create();
        if (array_key_exists('readyPickupDateTime', $data) && $data['readyPickupDateTime'] !== null) {
            $readyPickupDateTimeRaw = $data['readyPickupDateTime'];
            if (!is_string($readyPickupDateTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "readyPickupDateTime" must be string, got %s.',
                        get_debug_type($readyPickupDateTimeRaw),
                    ),
                );
            }
            $date = DateTime::createFromFormat('Y-m-d', $readyPickupDateTimeRaw);
            if (false === $date || false !== DateTime::getLastErrors()) {
                throw new MalformedDataException('Invalid date format, expected: Y-m-d');
            }
            $readyPickupDateTime = Some::create($date->setTime(0, 0, 0));
        }
        if (array_key_exists('latestPickupDateTime', $data) && $data['latestPickupDateTime'] !== null) {
            $latestPickupDateTimeRaw = $data['latestPickupDateTime'];
            if (!is_string($latestPickupDateTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "latestPickupDateTime" must be string, got %s.',
                        get_debug_type($latestPickupDateTimeRaw),
                    ),
                );
            }
            $date_1 = DateTime::createFromFormat('Y-m-d', $latestPickupDateTimeRaw);
            if (false === $date_1 || false !== DateTime::getLastErrors()) {
                throw new MalformedDataException('Invalid date format, expected: Y-m-d');
            }
            $latestPickupDateTime = Some::create($date_1->setTime(0, 0, 0));
        }
        if (array_key_exists('courierInstructions', $data) && $data['courierInstructions'] !== null) {
            $courierInstructionsRaw = $data['courierInstructions'];
            if (!is_string($courierInstructionsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "courierInstructions" must be string, got %s.',
                        get_debug_type($courierInstructionsRaw),
                    ),
                );
            }
            $courierInstructions = Some::create($courierInstructionsRaw);
        }
        if (array_key_exists('requestType', $data) && $data['requestType'] !== null) {
            $requestTypeRaw = $data['requestType'];
            if (!is_string($requestTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "requestType" must be string, got %s.', get_debug_type($requestTypeRaw)),
                );
            }
            $requestType = Some::create(
                PickupRequestType::tryFrom($requestTypeRaw) ?? UnknownEnumValue::of($requestTypeRaw),
            );
        }
        if (array_key_exists('requestSource', $data) && $data['requestSource'] !== null) {
            $requestSourceRaw = $data['requestSource'];
            if (!is_string($requestSourceRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "requestSource" must be string, got %s.', get_debug_type($requestSourceRaw)),
                );
            }
            $requestSource = Some::create(
                PickupRequestSourceType::tryFrom($requestSourceRaw) ?? UnknownEnumValue::of($requestSourceRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'readyPickupDateTime' => true,
                'latestPickupDateTime' => true,
                'courierInstructions' => true,
                'requestType' => true,
                'requestSource' => true,
            ],
        );

        return new self(
            $readyPickupDateTime,
            $latestPickupDateTime,
            $courierInstructions,
            $requestType,
            $requestSource,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $readyPickupDateTimeOption = $this->readyPickupDateTime;
        if ($readyPickupDateTimeOption->isDefined()) {
            $readyPickupDateTime = $readyPickupDateTimeOption->get();
            $dataArray['readyPickupDateTime'] = $readyPickupDateTime->format('Y-m-d');
        }
        $latestPickupDateTimeOption = $this->latestPickupDateTime;
        if ($latestPickupDateTimeOption->isDefined()) {
            $latestPickupDateTime = $latestPickupDateTimeOption->get();
            $dataArray['latestPickupDateTime'] = $latestPickupDateTime->format('Y-m-d');
        }
        $courierInstructionsOption = $this->courierInstructions;
        if ($courierInstructionsOption->isDefined()) {
            $courierInstructions = $courierInstructionsOption->get();
            $dataArray['courierInstructions'] = $courierInstructions;
        }
        $requestTypeOption = $this->requestType;
        if ($requestTypeOption->isDefined()) {
            $requestType = $requestTypeOption->get();
            $dataArray['requestType'] = $requestType->value;
        }
        $requestSourceOption = $this->requestSource;
        if ($requestSourceOption->isDefined()) {
            $requestSource = $requestSourceOption->get();
            $dataArray['requestSource'] = $requestSource->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): PickupDetailBuilder
    {
        return new PickupDetailBuilder(
            $this->readyPickupDateTime,
            $this->latestPickupDateTime,
            $this->courierInstructions,
            $this->requestType,
            $this->requestSource,
            $this->additionalProperties,
        );
    }
}
