<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see PriorityAlertDetail}.
 */
final class PriorityAlertDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<string>>     $enhancementTypes
     * @param Option<list<string>>     $content
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $enhancementTypes,
        private Option $content,
        private array $additionalProperties,
    ) {
    }

    /**
     * The types of all enhancement for the Priority Alert.
     *
     * Example: PRIORITY_ALERT_PLUS
     *
     * @param list<string> $enhancementTypes
     */
    public function setEnhancementTypes(array $enhancementTypes): self
    {
        $this->enhancementTypes = Some::create($enhancementTypes);

        return $this;
    }

    /**
     * Specifies Content for the Priority Alert Detail.
     *
     * Example:string
     *
     * @param list<string> $content
     */
    public function setContent(array $content): self
    {
        $this->content = Some::create($content);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): PriorityAlertDetail
    {
        return new PriorityAlertDetail($this->enhancementTypes, $this->content, $this->additionalProperties);
    }
}
