<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ProductName}.
 */
final class ProductNameBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $type
     * @param Option<string>           $encoding
     * @param Option<string>           $value
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $type,
        private Option $encoding,
        private Option $value,
        private array $additionalProperties,
    ) {
    }

    /**
     * The type of name (long, medium, short, etc.) to which this value refers.
     *
     * Example: long
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /**
     * The character encoding used to represent this product name.
     *
     * Example: UTF-8
     */
    public function setEncoding(string $encoding): self
    {
        $this->encoding = Some::create($encoding);

        return $this;
    }

    /**
     * Specifies the value of the Product.
     *
     * Example: F-2
     */
    public function setValue(string $value): self
    {
        $this->value = Some::create($value);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ProductName
    {
        return new ProductName($this->type, $this->encoding, $this->value, $this->additionalProperties);
    }
}
