<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum RegulatoryDetailProductIdType: string
{
    case SKU = 'SKU';
    case MODEL_NUMBER = 'MODEL_NUMBER';
    case SERIAL_NUMBER = 'SERIAL_NUMBER';
    case ALTERNATE_ID = 'ALTERNATE_ID';
    case GTIN = 'GTIN';
    case UPC = 'UPC';
}
