<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see RegulatoryLabelContentDetail}.
 */
final class RegulatoryLabelContentDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<RegulatoryLabelContentDetailGenerationOptions|UnknownEnumValue<string>> $generationOptions
     * @param Option<RegulatoryLabelContentDetailType|UnknownEnumValue<string>>              $type
     * @param array<int|string, mixed>                                                       $additionalProperties
     */
    public function __construct(
        private Option $generationOptions,
        private Option $type,
        private array $additionalProperties,
    ) {
    }

    /**
     * Specify the regulatory content preference to be displayed on the label.
     */
    public function setGenerationOptions(RegulatoryLabelContentDetailGenerationOptions $generationOptions): self
    {
        $this->generationOptions = Some::create($generationOptions);

        return $this;
    }

    /**
     * Specify the type of regulatory content to be added on the label.
     */
    public function setType(RegulatoryLabelContentDetailType $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RegulatoryLabelContentDetail
    {
        return new RegulatoryLabelContentDetail($this->generationOptions, $this->type, $this->additionalProperties);
    }
}
