<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see RegulatoryDetailInfo}.
 */
final class RegulatoryDetailInfoBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<DisclaimMessageSet>  $disclaimMessageSet
     * @param Option<ReferenceMessageSet> $referenceMessageSet
     * @param Option<string>              $standardManufacturerProductId
     * @param Option<string>              $nonStandardManufacturerProductId
     * @param Option<string>              $merchantProductId
     * @param array<int|string, mixed>    $additionalProperties
     */
    public function __construct(
        private Option $disclaimMessageSet,
        private Option $referenceMessageSet,
        private Option $standardManufacturerProductId,
        private Option $nonStandardManufacturerProductId,
        private Option $merchantProductId,
        private array $additionalProperties,
    ) {
    }

    /**
     * Additional declaration information related to product use classification or exemption
     * handling.
     */
    public function setDisclaimMessageSet(DisclaimMessageSet $disclaimMessageSet): self
    {
        $this->disclaimMessageSet = Some::create($disclaimMessageSet);

        return $this;
    }

    /**
     * Registry-based CPSC eFiling reference information for repeat shipments.
     */
    public function setReferenceMessageSet(ReferenceMessageSet $referenceMessageSet): self
    {
        $this->referenceMessageSet = Some::create($referenceMessageSet);

        return $this;
    }

    /**
     * Manufacturer Standard Product Identifier per commodity - Assigned by a global industry
     * standard body with a barcode when the manufacturer’s product meets global standards from a
     * governing body. The barcode is the same for every retailer selling the exact
     * product.</br>Maximum length is 70.
     *
     * Example: GTIN 00000006
     */
    public function setStandardManufacturerProductId(string $standardManufacturerProductId): self
    {
        $this->standardManufacturerProductId = Some::create($standardManufacturerProductId);

        return $this;
    }

    /**
     * Manufacturer Non-Standard Product Identifier per commodity - A manufacturer or product
     * supplier’s unique product code, provided to sellers who must supply it for customs
     * declaration.</br>Maximum length is 70.
     *
     * Example: SH123456-L
     */
    public function setNonStandardManufacturerProductId(string $nonStandardManufacturerProductId): self
    {
        $this->nonStandardManufacturerProductId = Some::create($nonStandardManufacturerProductId);

        return $this;
    }

    /**
     * Merchant Product Identifier (shipper SKU/item ID) per commodity - The merchant’s unique code
     * to identify goods, usually the SKU, item code or product code.</br>Maximum length is 70.
     *
     * Example: 12345
     */
    public function setMerchantProductId(string $merchantProductId): self
    {
        $this->merchantProductId = Some::create($merchantProductId);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RegulatoryDetailInfo
    {
        return new RegulatoryDetailInfo(
            $this->disclaimMessageSet,
            $this->referenceMessageSet,
            $this->standardManufacturerProductId,
            $this->nonStandardManufacturerProductId,
            $this->merchantProductId,
            $this->additionalProperties,
        );
    }
}
