<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_int;
use function is_string;
use function sprintf;

final readonly class RegulatoryProhibition implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $derivedHarmonizedCode
     * @param Option<Message>          $advisory
     * @param Option<int>              $commodityIndex
     * @param Option<string>           $source
     * @param Option<list<string>>     $categories
     * @param Option<string>           $type
     * @param Option<RegulatoryWaiver> $waiver
     * @param Option<string>           $status
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $derivedHarmonizedCode,
        private Option $advisory,
        private Option $commodityIndex,
        private Option $source,
        private Option $categories,
        private Option $type,
        private Option $waiver,
        private Option $status,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): RegulatoryProhibitionBuilder
    {
        return new RegulatoryProhibitionBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Indicates the derived harmonized code value.
     *
     * Example: 01
     *
     * @return Option<string>
     */
    public function getDerivedHarmonizedCode(): Option
    {
        return $this->derivedHarmonizedCode;
    }

    /**
     * Specifies the advisory details.
     *
     * @return Option<Message>
     */
    public function getAdvisory(): Option
    {
        return $this->advisory;
    }

    /**
     * Indicates one based index identifying the associated commodity.
     *
     * Example: 12
     *
     * @return Option<int>
     */
    public function getCommodityIndex(): Option
    {
        return $this->commodityIndex;
    }

    /**
     * Indicates the prohibition source type.
     *
     * Example: source
     *
     * @return Option<string>
     */
    public function getSource(): Option
    {
        return $this->source;
    }

    /**
     * Indicate the shipment rule type.
     *
     * Example: ["categories"]
     *
     * @return Option<list<string>>
     */
    public function getCategories(): Option
    {
        return $this->categories;
    }

    /**
     * Indicates the prohibition type.
     *
     * Example: type
     *
     * @return Option<string>
     */
    public function getType(): Option
    {
        return $this->type;
    }

    /**
     * Indicates the regulatory waiver.
     *
     * @return Option<RegulatoryWaiver>
     */
    public function getWaiver(): Option
    {
        return $this->waiver;
    }

    /**
     * Indicates the prohibitory status.
     *
     * Example: status
     *
     * @return Option<string>
     */
    public function getStatus(): Option
    {
        return $this->status;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $derivedHarmonizedCode = None::create();
        $advisory = None::create();
        $commodityIndex = None::create();
        $source = None::create();
        $categories = None::create();
        $type = None::create();
        $waiver = None::create();
        $status = None::create();
        if (array_key_exists('derivedHarmonizedCode', $data) && $data['derivedHarmonizedCode'] !== null) {
            $derivedHarmonizedCodeRaw = $data['derivedHarmonizedCode'];
            if (!is_string($derivedHarmonizedCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "derivedHarmonizedCode" must be string, got %s.',
                        get_debug_type($derivedHarmonizedCodeRaw),
                    ),
                );
            }
            $derivedHarmonizedCode = Some::create($derivedHarmonizedCodeRaw);
        }
        if (array_key_exists('advisory', $data) && $data['advisory'] !== null) {
            $advisoryRaw = $data['advisory'];
            if (!is_array($advisoryRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "advisory" must be object, got %s.', get_debug_type($advisoryRaw)),
                );
            }
            /** @var array<string, mixed> $advisoryRawTyped */
            $advisoryRawTyped = $advisoryRaw;
            $advisory = Some::create(Message::fromArray($advisoryRawTyped));
        }
        if (array_key_exists('commodityIndex', $data) && $data['commodityIndex'] !== null) {
            $commodityIndexRaw = $data['commodityIndex'];
            if (!is_int($commodityIndexRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "commodityIndex" must be int, got %s.', get_debug_type($commodityIndexRaw)),
                );
            }
            $commodityIndex = Some::create($commodityIndexRaw);
        }
        if (array_key_exists('source', $data) && $data['source'] !== null) {
            $sourceRaw = $data['source'];
            if (!is_string($sourceRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "source" must be string, got %s.', get_debug_type($sourceRaw)),
                );
            }
            $source = Some::create($sourceRaw);
        }
        if (array_key_exists('categories', $data) && $data['categories'] !== null) {
            $categoriesRaw = $data['categories'];
            if (!(is_array($categoriesRaw) && array_is_list($categoriesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "categories" must be list, got %s.', get_debug_type($categoriesRaw)),
                );
            }
            $categories = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $categoriesRaw));
        }
        if (array_key_exists('type', $data) && $data['type'] !== null) {
            $typeRaw = $data['type'];
            if (!is_string($typeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "type" must be string, got %s.', get_debug_type($typeRaw)),
                );
            }
            $type = Some::create($typeRaw);
        }
        if (array_key_exists('waiver', $data) && $data['waiver'] !== null) {
            $waiverRaw = $data['waiver'];
            if (!is_array($waiverRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "waiver" must be object, got %s.', get_debug_type($waiverRaw)),
                );
            }
            /** @var array<string, mixed> $waiverRawTyped */
            $waiverRawTyped = $waiverRaw;
            $waiver = Some::create(RegulatoryWaiver::fromArray($waiverRawTyped));
        }
        if (array_key_exists('status', $data) && $data['status'] !== null) {
            $statusRaw = $data['status'];
            if (!is_string($statusRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "status" must be string, got %s.', get_debug_type($statusRaw)),
                );
            }
            $status = Some::create($statusRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'derivedHarmonizedCode' => true,
                'advisory' => true,
                'commodityIndex' => true,
                'source' => true,
                'categories' => true,
                'type' => true,
                'waiver' => true,
                'status' => true,
            ],
        );

        return new self(
            $derivedHarmonizedCode,
            $advisory,
            $commodityIndex,
            $source,
            $categories,
            $type,
            $waiver,
            $status,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $derivedHarmonizedCodeOption = $this->derivedHarmonizedCode;
        if ($derivedHarmonizedCodeOption->isDefined()) {
            $derivedHarmonizedCode = $derivedHarmonizedCodeOption->get();
            $dataArray['derivedHarmonizedCode'] = $derivedHarmonizedCode;
        }
        $advisoryOption = $this->advisory;
        if ($advisoryOption->isDefined()) {
            $advisory = $advisoryOption->get();
            $dataArray['advisory'] = $normalizationTarget->model($advisory);
        }
        $commodityIndexOption = $this->commodityIndex;
        if ($commodityIndexOption->isDefined()) {
            $commodityIndex = $commodityIndexOption->get();
            $dataArray['commodityIndex'] = $commodityIndex;
        }
        $sourceOption = $this->source;
        if ($sourceOption->isDefined()) {
            $source = $sourceOption->get();
            $dataArray['source'] = $source;
        }
        $categoriesOption = $this->categories;
        if ($categoriesOption->isDefined()) {
            $categories = $categoriesOption->get();
            $values = [];
            foreach ($categories as $value) {
                $values[] = $value;
            }
            $dataArray['categories'] = $values;
        }
        $typeOption = $this->type;
        if ($typeOption->isDefined()) {
            $type = $typeOption->get();
            $dataArray['type'] = $type;
        }
        $waiverOption = $this->waiver;
        if ($waiverOption->isDefined()) {
            $waiver = $waiverOption->get();
            $dataArray['waiver'] = $normalizationTarget->model($waiver);
        }
        $statusOption = $this->status;
        if ($statusOption->isDefined()) {
            $status = $statusOption->get();
            $dataArray['status'] = $status;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): RegulatoryProhibitionBuilder
    {
        return new RegulatoryProhibitionBuilder(
            $this->derivedHarmonizedCode,
            $this->advisory,
            $this->commodityIndex,
            $this->source,
            $this->categories,
            $this->type,
            $this->waiver,
            $this->status,
            $this->additionalProperties,
        );
    }
}
