<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see RegulatoryProhibition}.
 */
final class RegulatoryProhibitionBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $derivedHarmonizedCode
     * @param Option<Message>          $advisory
     * @param Option<int>              $commodityIndex
     * @param Option<string>           $source
     * @param Option<list<string>>     $categories
     * @param Option<string>           $type
     * @param Option<RegulatoryWaiver> $waiver
     * @param Option<string>           $status
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $derivedHarmonizedCode,
        private Option $advisory,
        private Option $commodityIndex,
        private Option $source,
        private Option $categories,
        private Option $type,
        private Option $waiver,
        private Option $status,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicates the derived harmonized code value.
     *
     * Example: 01
     */
    public function setDerivedHarmonizedCode(string $derivedHarmonizedCode): self
    {
        $this->derivedHarmonizedCode = Some::create($derivedHarmonizedCode);

        return $this;
    }

    /**
     * Specifies the advisory details.
     */
    public function setAdvisory(Message $advisory): self
    {
        $this->advisory = Some::create($advisory);

        return $this;
    }

    /**
     * Indicates one based index identifying the associated commodity.
     *
     * Example: 12
     */
    public function setCommodityIndex(int $commodityIndex): self
    {
        $this->commodityIndex = Some::create($commodityIndex);

        return $this;
    }

    /**
     * Indicates the prohibition source type.
     *
     * Example: source
     */
    public function setSource(string $source): self
    {
        $this->source = Some::create($source);

        return $this;
    }

    /**
     * Indicate the shipment rule type.
     *
     * Example: ["categories"]
     *
     * @param list<string> $categories
     */
    public function setCategories(array $categories): self
    {
        $this->categories = Some::create($categories);

        return $this;
    }

    /**
     * Indicates the prohibition type.
     *
     * Example: type
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /**
     * Indicates the regulatory waiver.
     */
    public function setWaiver(RegulatoryWaiver $waiver): self
    {
        $this->waiver = Some::create($waiver);

        return $this;
    }

    /**
     * Indicates the prohibitory status.
     *
     * Example: status
     */
    public function setStatus(string $status): self
    {
        $this->status = Some::create($status);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RegulatoryProhibition
    {
        return new RegulatoryProhibition(
            $this->derivedHarmonizedCode,
            $this->advisory,
            $this->commodityIndex,
            $this->source,
            $this->categories,
            $this->type,
            $this->waiver,
            $this->status,
            $this->additionalProperties,
        );
    }
}
