<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class RetrieveDateRange implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $begins
     * @param Option<string>           $ends
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $begins, private Option $ends, private array $additionalProperties)
    {
    }

    public static function builder(): RetrieveDateRangeBuilder
    {
        return new RetrieveDateRangeBuilder(None::create(), None::create(), []);
    }

    /**
     * Indicates the start date.
     *
     * @return Option<string>
     */
    public function getBegins(): Option
    {
        return $this->begins;
    }

    /**
     * Indicates the end date.
     *
     * @return Option<string>
     */
    public function getEnds(): Option
    {
        return $this->ends;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $begins = None::create();
        $ends = None::create();
        if (array_key_exists('begins', $data) && $data['begins'] !== null) {
            $beginsRaw = $data['begins'];
            if (!is_string($beginsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "begins" must be string, got %s.', get_debug_type($beginsRaw)),
                );
            }
            $begins = Some::create($beginsRaw);
        }
        if (array_key_exists('ends', $data) && $data['ends'] !== null) {
            $endsRaw = $data['ends'];
            if (!is_string($endsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "ends" must be string, got %s.', get_debug_type($endsRaw)),
                );
            }
            $ends = Some::create($endsRaw);
        }
        $additionalProperties = array_diff_key($data, ['begins' => true, 'ends' => true]);

        return new self($begins, $ends, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $beginsOption = $this->begins;
        if ($beginsOption->isDefined()) {
            $begins = $beginsOption->get();
            $dataArray['begins'] = $begins;
        }
        $endsOption = $this->ends;
        if ($endsOption->isDefined()) {
            $ends = $endsOption->get();
            $dataArray['ends'] = $ends;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): RetrieveDateRangeBuilder
    {
        return new RetrieveDateRangeBuilder($this->begins, $this->ends, $this->additionalProperties);
    }
}
