<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see RetrieveDateRange}.
 */
final class RetrieveDateRangeBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $begins
     * @param Option<string>           $ends
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $begins, private Option $ends, private array $additionalProperties)
    {
    }

    /**
     * Indicates the start date.
     */
    public function setBegins(string $begins): self
    {
        $this->begins = Some::create($begins);

        return $this;
    }

    /**
     * Indicates the end date.
     */
    public function setEnds(string $ends): self
    {
        $this->ends = Some::create($ends);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): RetrieveDateRange
    {
        return new RetrieveDateRange($this->begins, $this->ends, $this->additionalProperties);
    }
}
