<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum ReturnShipmentDetailReturnType: string
{
    case PENDING = 'PENDING';
    case PRINT_RETURN_LABEL = 'PRINT_RETURN_LABEL';
}
