<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ReturnAssociationDetail}.
 */
final class ReturnAssociationDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $shipDatestamp
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $trackingNumber,
        private Option $shipDatestamp,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is the tracking number associated with this package.
     *
     * Example: 49XXX0000XXX20032835
     */
    public function setTrackingNumber(string $trackingNumber): self
    {
        $this->trackingNumber = $trackingNumber;

        return $this;
    }

    /**
     * This is the ship date for the outbound shipment associated with a return shipment. The format
     * is YYYY-MM-DD.
     *
     * Example: 2019-10-01
     */
    public function setShipDatestamp(string $shipDatestamp): self
    {
        $this->shipDatestamp = Some::create($shipDatestamp);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ReturnAssociationDetail
    {
        return new ReturnAssociationDetail($this->trackingNumber, $this->shipDatestamp, $this->additionalProperties);
    }
}
