<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ShipEmailDispositionDetail}.
 */
final class ShipEmailDispositionDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $emailAddress
     * @param Option<string>           $type
     * @param Option<string>           $recipientType
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $emailAddress,
        private Option $type,
        private Option $recipientType,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is email Address.
     *
     * Example: xxxx@xxx.com
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->emailAddress = Some::create($emailAddress);

        return $this;
    }

    /**
     * Specify the email status.
     *
     * Example: EMAILED
     */
    public function setType(string $type): self
    {
        $this->type = Some::create($type);

        return $this;
    }

    /**
     * Specify the recipient Type.
     *
     * Example: SHIPPER/BROKER
     */
    public function setRecipientType(string $recipientType): self
    {
        $this->recipientType = Some::create($recipientType);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipEmailDispositionDetail
    {
        return new ShipEmailDispositionDetail(
            $this->emailAddress,
            $this->type,
            $this->recipientType,
            $this->additionalProperties,
        );
    }
}
