<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ShipmentOperationalDetail}.
 */
final class ShipmentOperationalDetailBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $originServiceArea
     * @param Option<string>           $serviceCode
     * @param Option<string>           $airportId
     * @param Option<string>           $postalCode
     * @param Option<string>           $scac
     * @param Option<string>           $deliveryDay
     * @param Option<string>           $originLocationId
     * @param Option<string>           $countryCode
     * @param Option<string>           $astraDescription
     * @param Option<int>              $originLocationNumber
     * @param Option<string>           $deliveryDate
     * @param Option<list<string>>     $deliveryEligibilities
     * @param Option<bool>             $ineligibleForMoneyBackGuarantee
     * @param Option<string>           $maximumTransitTime
     * @param Option<string>           $destinationLocationStateOrProvinceCode
     * @param Option<string>           $astraPlannedServiceLevel
     * @param Option<string>           $destinationLocationId
     * @param Option<string>           $transitTime
     * @param Option<string>           $stateOrProvinceCode
     * @param Option<int>              $destinationLocationNumber
     * @param Option<string>           $packagingCode
     * @param Option<string>           $commitDate
     * @param Option<string>           $publishedDeliveryTime
     * @param Option<string>           $ursaSuffixCode
     * @param Option<string>           $ursaPrefixCode
     * @param Option<string>           $destinationServiceArea
     * @param Option<string>           $commitDay
     * @param Option<string>           $customTransitTime
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $originServiceArea,
        private Option $serviceCode,
        private Option $airportId,
        private Option $postalCode,
        private Option $scac,
        private Option $deliveryDay,
        private Option $originLocationId,
        private Option $countryCode,
        private Option $astraDescription,
        private Option $originLocationNumber,
        private Option $deliveryDate,
        private Option $deliveryEligibilities,
        private Option $ineligibleForMoneyBackGuarantee,
        private Option $maximumTransitTime,
        private Option $destinationLocationStateOrProvinceCode,
        private Option $astraPlannedServiceLevel,
        private Option $destinationLocationId,
        private Option $transitTime,
        private Option $stateOrProvinceCode,
        private Option $destinationLocationNumber,
        private Option $packagingCode,
        private Option $commitDate,
        private Option $publishedDeliveryTime,
        private Option $ursaSuffixCode,
        private Option $ursaPrefixCode,
        private Option $destinationServiceArea,
        private Option $commitDay,
        private Option $customTransitTime,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicates the origin service area.
     *
     * Example: A1
     */
    public function setOriginServiceArea(string $originServiceArea): self
    {
        $this->originServiceArea = Some::create($originServiceArea);

        return $this;
    }

    /**
     * Indicates the service code.
     *
     * Example: 010
     */
    public function setServiceCode(string $serviceCode): self
    {
        $this->serviceCode = Some::create($serviceCode);

        return $this;
    }

    /**
     * Indicates the airport identifier.
     *
     * Example: DFW
     */
    public function setAirportId(string $airportId): self
    {
        $this->airportId = Some::create($airportId);

        return $this;
    }

    /**
     * Specifies the postal code.
     *
     * Example: 38010
     *
     * <a onclick='loadDocReference("postalawarecountries")'>click here to see Postal aware
     * countries</a>
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * Indicates standard carrier alpha code.
     */
    public function setScac(string $scac): self
    {
        $this->scac = Some::create($scac);

        return $this;
    }

    /**
     * Specifies expected/estimated day of week of the delivery.
     *
     * Example: TUE
     */
    public function setDeliveryDay(string $deliveryDay): self
    {
        $this->deliveryDay = Some::create($deliveryDay);

        return $this;
    }

    /**
     * This is the origin Location identifier.
     *
     * Example: 678
     */
    public function setOriginLocationId(string $originLocationId): self
    {
        $this->originLocationId = Some::create($originLocationId);

        return $this;
    }

    /**
     * Indicate the two-letter country code.
     *
     * Example: US
     *
     * <a onclick='loadDocReference("countrycodes")'>click here to see Country codes</a>
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = Some::create($countryCode);

        return $this;
    }

    /**
     * Specifies astra description.
     *
     * Example: SMART POST
     */
    public function setAstraDescription(string $astraDescription): self
    {
        $this->astraDescription = Some::create($astraDescription);

        return $this;
    }

    /**
     * Specifies origin location number.
     *
     * Example: 243
     */
    public function setOriginLocationNumber(int $originLocationNumber): self
    {
        $this->originLocationNumber = Some::create($originLocationNumber);

        return $this;
    }

    /**
     * Specifies delivery date for the shipment. The format is [YYYY-MM-DD].
     *
     * Example: 2001-04-05
     */
    public function setDeliveryDate(string $deliveryDate): self
    {
        $this->deliveryDate = Some::create($deliveryDate);

        return $this;
    }

    /**
     * FedEx Ground delivery features for which this shipment may be eligible.
     *
     * Example: ["deliveryEligibilities"]
     *
     * @param list<string> $deliveryEligibilities
     */
    public function setDeliveryEligibilities(array $deliveryEligibilities): self
    {
        $this->deliveryEligibilities = Some::create($deliveryEligibilities);

        return $this;
    }

    /**
     * Indicates that this shipment is not eligible for money back guarantee.
     */
    public function setIneligibleForMoneyBackGuarantee(bool $ineligibleForMoneyBackGuarantee): self
    {
        $this->ineligibleForMoneyBackGuarantee = Some::create($ineligibleForMoneyBackGuarantee);

        return $this;
    }

    /**
     * Maximum expected transit time.
     *
     * Example: SEVEN_DAYS
     */
    public function setMaximumTransitTime(string $maximumTransitTime): self
    {
        $this->maximumTransitTime = Some::create($maximumTransitTime);

        return $this;
    }

    /**
     * This is the state or province code of the shipment destination location, and is not
     * necessarily the same as the postal state.
     *
     * Example: GA
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>click here to see State or Province
     * Code</a>
     */
    public function setDestinationLocationStateOrProvinceCode(string $destinationLocationStateOrProvinceCode): self
    {
        $this->destinationLocationStateOrProvinceCode = Some::create($destinationLocationStateOrProvinceCode);

        return $this;
    }

    /**
     * Text describing planned delivery.
     *
     * Example: TUE - 15 OCT 10:30A
     */
    public function setAstraPlannedServiceLevel(string $astraPlannedServiceLevel): self
    {
        $this->astraPlannedServiceLevel = Some::create($astraPlannedServiceLevel);

        return $this;
    }

    /**
     * Specifies the FedEx Destination Location Identifier.
     *
     * Example: DALA
     */
    public function setDestinationLocationId(string $destinationLocationId): self
    {
        $this->destinationLocationId = Some::create($destinationLocationId);

        return $this;
    }

    /**
     * Standard transit time per origin, destination, and service.
     *
     * Example: TWO_DAYS
     */
    public function setTransitTime(string $transitTime): self
    {
        $this->transitTime = Some::create($transitTime);

        return $this;
    }

    /**
     * This is a placeholder for State or Province code.State code is required for US, CA, PR and
     * not required for other countries. Conditional.
     *
     * Example: CA
     *
     * <a onclick='loadDocReference("canadaprovincecodes")'>click here to see State or Province
     * Code</a>
     */
    public function setStateOrProvinceCode(string $stateOrProvinceCode): self
    {
        $this->stateOrProvinceCode = Some::create($stateOrProvinceCode);

        return $this;
    }

    /**
     * Indicates destination location number.
     *
     * Example: 876
     */
    public function setDestinationLocationNumber(int $destinationLocationNumber): self
    {
        $this->destinationLocationNumber = Some::create($destinationLocationNumber);

        return $this;
    }

    /**
     * Indicates packaging code.
     *
     * Example: 03
     */
    public function setPackagingCode(string $packagingCode): self
    {
        $this->packagingCode = Some::create($packagingCode);

        return $this;
    }

    /**
     * This is committed date of delivery.
     *
     * Example: 2019-10-15
     */
    public function setCommitDate(string $commitDate): self
    {
        $this->commitDate = Some::create($commitDate);

        return $this;
    }

    /**
     * This is delivery time, as published in Service Guide.
     *
     * Example: 10:30A
     */
    public function setPublishedDeliveryTime(string $publishedDeliveryTime): self
    {
        $this->publishedDeliveryTime = Some::create($publishedDeliveryTime);

        return $this;
    }

    /**
     * This is ursa suffix code.
     *
     * Example: Ga
     */
    public function setUrsaSuffixCode(string $ursaSuffixCode): self
    {
        $this->ursaSuffixCode = Some::create($ursaSuffixCode);

        return $this;
    }

    /**
     * This is ursa prefix code.
     *
     * Example: XH
     */
    public function setUrsaPrefixCode(string $ursaPrefixCode): self
    {
        $this->ursaPrefixCode = Some::create($ursaPrefixCode);

        return $this;
    }

    /**
     * Specifies destination service area.
     *
     * Example: A1
     */
    public function setDestinationServiceArea(string $destinationServiceArea): self
    {
        $this->destinationServiceArea = Some::create($destinationServiceArea);

        return $this;
    }

    /**
     * Committed day of week of delivery.
     *
     * Example: TUE
     */
    public function setCommitDay(string $commitDay): self
    {
        $this->commitDay = Some::create($commitDay);

        return $this;
    }

    /**
     * Transit time based on customer eligibility.
     *
     * Example: ONE_DAY
     */
    public function setCustomTransitTime(string $customTransitTime): self
    {
        $this->customTransitTime = Some::create($customTransitTime);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ShipmentOperationalDetail
    {
        return new ShipmentOperationalDetail(
            $this->originServiceArea,
            $this->serviceCode,
            $this->airportId,
            $this->postalCode,
            $this->scac,
            $this->deliveryDay,
            $this->originLocationId,
            $this->countryCode,
            $this->astraDescription,
            $this->originLocationNumber,
            $this->deliveryDate,
            $this->deliveryEligibilities,
            $this->ineligibleForMoneyBackGuarantee,
            $this->maximumTransitTime,
            $this->destinationLocationStateOrProvinceCode,
            $this->astraPlannedServiceLevel,
            $this->destinationLocationId,
            $this->transitTime,
            $this->stateOrProvinceCode,
            $this->destinationLocationNumber,
            $this->packagingCode,
            $this->commitDate,
            $this->publishedDeliveryTime,
            $this->ursaSuffixCode,
            $this->ursaPrefixCode,
            $this->destinationServiceArea,
            $this->commitDay,
            $this->customTransitTime,
            $this->additionalProperties,
        );
    }
}
