<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see SHPCResponseVOGetOpenShipmentResults}.
 */
final class SHPCResponseVOGetOpenShipmentResultsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>                         $transactionId
     * @param Option<string>                         $customerTransactionId
     * @param Option<GetOpenShipmentResultsOutputVO> $output
     * @param array<int|string, mixed>               $additionalProperties
     */
    public function __construct(
        private Option $transactionId,
        private Option $customerTransactionId,
        private Option $output,
        private array $additionalProperties,
    ) {
    }

    /**
     * The transaction ID is a special set of numbers that defines each transaction.
     *
     * Example: 624xxxxx-b709-470c-8c39-4b55112xxxxx
     */
    public function setTransactionId(string $transactionId): self
    {
        $this->transactionId = Some::create($transactionId);

        return $this;
    }

    /**
     * This is a unique identifier to your transaction and helps you match the request to the reply.
     *
     * Example: AnyCo_order123456789
     */
    public function setCustomerTransactionId(string $customerTransactionId): self
    {
        $this->customerTransactionId = Some::create($customerTransactionId);

        return $this;
    }

    public function setOutput(GetOpenShipmentResultsOutputVO $output): self
    {
        $this->output = Some::create($output);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): SHPCResponseVOGetOpenShipmentResults
    {
        return new SHPCResponseVOGetOpenShipmentResults(
            $this->transactionId,
            $this->customerTransactionId,
            $this->output,
            $this->additionalProperties,
        );
    }
}
