<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see SHPCResponseVOShipShipment}.
 */
final class SHPCResponseVOShipShipmentBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>               $transactionId
     * @param Option<string>               $customerTransactionId
     * @param Option<ShipShipmentOutputVO> $output
     * @param array<int|string, mixed>     $additionalProperties
     */
    public function __construct(
        private Option $transactionId,
        private Option $customerTransactionId,
        private Option $output,
        private array $additionalProperties,
    ) {
    }

    /**
     * The transaction ID is a special set of numbers that defines each transaction.
     *
     * Example: 624deea6-b709-470c-8c39-4b5511281492
     */
    public function setTransactionId(string $transactionId): self
    {
        $this->transactionId = Some::create($transactionId);

        return $this;
    }

    /**
     * This element has a unique identifier added in your request, helps you match the request to
     * the reply.
     *
     * Example: XXXX_XXX123XXXXX
     */
    public function setCustomerTransactionId(string $customerTransactionId): self
    {
        $this->customerTransactionId = Some::create($customerTransactionId);

        return $this;
    }

    /**
     * This is the response received when a shipment is requested.
     */
    public function setOutput(ShipShipmentOutputVO $output): self
    {
        $this->output = Some::create($output);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): SHPCResponseVOShipShipment
    {
        return new SHPCResponseVOShipShipment(
            $this->transactionId,
            $this->customerTransactionId,
            $this->output,
            $this->additionalProperties,
        );
    }
}
