<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class Surcharge2 implements SelfNormalizingModel
{
    /**
     * @param Option<Surcharge2SurchargeType|UnknownEnumValue<string>> $surchargeType
     * @param Option<Surcharge2Level|UnknownEnumValue<string>>         $level
     * @param Option<string>                                           $description
     * @param Option<Money1>                                           $amount
     * @param array<int|string, mixed>                                 $additionalProperties
     */
    public function __construct(
        private Option $surchargeType,
        private Option $level,
        private Option $description,
        private Option $amount,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): Surcharge2Builder
    {
        return new Surcharge2Builder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /**
     * The type of surcharge.
     *
     * @return Option<Surcharge2SurchargeType|UnknownEnumValue<string>>
     */
    public function getSurchargeType(): Option
    {
        return $this->surchargeType;
    }

    /**
     * The level of surcharge.
     *
     * @return Option<Surcharge2Level|UnknownEnumValue<string>>
     */
    public function getLevel(): Option
    {
        return $this->level;
    }

    /**
     * The description of the surcharge.
     *
     * @return Option<string>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * Identifies the total amount of the shipment-level fees and taxes that are not based on
     * transportation charges or commodity-level estimated duties and taxes.
     *
     * @return Option<Money1>
     */
    public function getAmount(): Option
    {
        return $this->amount;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $surchargeType = None::create();
        $level = None::create();
        $description = None::create();
        $amount = None::create();
        if (array_key_exists('surchargeType', $data) && $data['surchargeType'] !== null) {
            $surchargeTypeRaw = $data['surchargeType'];
            if (!is_string($surchargeTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "surchargeType" must be string, got %s.', get_debug_type($surchargeTypeRaw)),
                );
            }
            $surchargeType = Some::create(
                Surcharge2SurchargeType::tryFrom($surchargeTypeRaw) ?? UnknownEnumValue::of($surchargeTypeRaw),
            );
        }
        if (array_key_exists('level', $data) && $data['level'] !== null) {
            $levelRaw = $data['level'];
            if (!is_string($levelRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "level" must be string, got %s.', get_debug_type($levelRaw)),
                );
            }
            $level = Some::create(Surcharge2Level::tryFrom($levelRaw) ?? UnknownEnumValue::of($levelRaw));
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_string($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be string, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            $description = Some::create($descriptionRaw);
        }
        if (array_key_exists('amount', $data) && $data['amount'] !== null) {
            $amountRaw = $data['amount'];
            if (!is_array($amountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "amount" must be object, got %s.', get_debug_type($amountRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $amountRawTyped */
            $amountRawTyped = $amountRaw;
            $amount = Some::create(Money1::fromArray($amountRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['surchargeType' => true, 'level' => true, 'description' => true, 'amount' => true],
        );

        return new self($surchargeType, $level, $description, $amount, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $surchargeTypeOption = $this->surchargeType;
        if ($surchargeTypeOption->isDefined()) {
            $surchargeType = $surchargeTypeOption->get();
            $dataArray['surchargeType'] = $surchargeType->value;
        }
        $levelOption = $this->level;
        if ($levelOption->isDefined()) {
            $level = $levelOption->get();
            $dataArray['level'] = $level->value;
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $description;
        }
        $amountOption = $this->amount;
        if ($amountOption->isDefined()) {
            $amount = $amountOption->get();
            $dataArray['amount'] = $normalizationTarget->model($amount);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): Surcharge2Builder
    {
        return new Surcharge2Builder(
            $this->surchargeType,
            $this->level,
            $this->description,
            $this->amount,
            $this->additionalProperties,
        );
    }
}
