<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class TaxpayerIdentification implements SelfNormalizingModel
{
    /**
     * @param TaxpayerIdentificationTinType|UnknownEnumValue<string> $tinType
     * @param Option<string>                                         $usage
     * @param Option<string>                                         $effectiveDate
     * @param Option<string>                                         $expirationDate
     * @param array<int|string, mixed>                               $additionalProperties
     */
    public function __construct(
        private string $number,
        private TaxpayerIdentificationTinType|UnknownEnumValue $tinType,
        private Option $usage,
        private Option $effectiveDate,
        private Option $expirationDate,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $number,
        TaxpayerIdentificationTinType $tinType,
    ): TaxpayerIdentificationBuilder {
        return new TaxpayerIdentificationBuilder($number, $tinType, None::create(), None::create(), None::create(), []);
    }

    /**
     * Specify tax ID number. Maximum length is 18.
     *
     * Example: 123567
     */
    public function getNumber(): string
    {
        return $this->number;
    }

    /**
     * Identifies the type of Tax Identification Number in Shipment processing.
     *
     * Example: FEDERAL
     *
     * @return TaxpayerIdentificationTinType|UnknownEnumValue<string>
     */
    public function getTinType(): TaxpayerIdentificationTinType|UnknownEnumValue
    {
        return $this->tinType;
    }

    /**
     * Identifies the usage of Tax Identification Number in Shipment processing.
     *
     * Example: usage
     *
     * @return Option<string>
     */
    public function getUsage(): Option
    {
        return $this->usage;
    }

    /**
     * Effective Date. FORMAT[YYYY-MM-DD].
     *
     * Example: 2024-06-13
     *
     * @return Option<string>
     */
    public function getEffectiveDate(): Option
    {
        return $this->effectiveDate;
    }

    /**
     * Expiration Date. FORMAT[YYYY-MM-DD].
     *
     * Example: 2024-06-13
     *
     * @return Option<string>
     */
    public function getExpirationDate(): Option
    {
        return $this->expirationDate;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $number = null;
        $tinType = null;
        $usage = None::create();
        $effectiveDate = None::create();
        $expirationDate = None::create();
        if (array_key_exists('number', $data)) {
            $numberRaw = $data['number'];
            if (!is_string($numberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "number" must be string, got %s.', get_debug_type($numberRaw)),
                );
            }
            $number = $numberRaw;
        }
        if (array_key_exists('tinType', $data)) {
            $tinTypeRaw = $data['tinType'];
            if (!is_string($tinTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "tinType" must be string, got %s.', get_debug_type($tinTypeRaw)),
                );
            }
            $tinType = TaxpayerIdentificationTinType::tryFrom($tinTypeRaw) ?? UnknownEnumValue::of($tinTypeRaw);
        }
        if (array_key_exists('usage', $data) && $data['usage'] !== null) {
            $usageRaw = $data['usage'];
            if (!is_string($usageRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "usage" must be string, got %s.', get_debug_type($usageRaw)),
                );
            }
            $usage = Some::create($usageRaw);
        }
        if (array_key_exists('effectiveDate', $data) && $data['effectiveDate'] !== null) {
            $effectiveDateRaw = $data['effectiveDate'];
            if (!is_string($effectiveDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "effectiveDate" must be string, got %s.', get_debug_type($effectiveDateRaw)),
                );
            }
            $effectiveDate = Some::create($effectiveDateRaw);
        }
        if (array_key_exists('expirationDate', $data) && $data['expirationDate'] !== null) {
            $expirationDateRaw = $data['expirationDate'];
            if (!is_string($expirationDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "expirationDate" must be string, got %s.', get_debug_type($expirationDateRaw)),
                );
            }
            $expirationDate = Some::create($expirationDateRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            ['number' => true, 'tinType' => true, 'usage' => true, 'effectiveDate' => true, 'expirationDate' => true],
        );
        if ($number === null) {
            throw new MalformedDataException('Required property "number" is missing from the document.');
        }
        if ($tinType === null) {
            throw new MalformedDataException('Required property "tinType" is missing from the document.');
        }

        return new self($number, $tinType, $usage, $effectiveDate, $expirationDate, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['number'] = $this->number;
        $dataArray['tinType'] = $this->tinType->value;
        $usageOption = $this->usage;
        if ($usageOption->isDefined()) {
            $usage = $usageOption->get();
            $dataArray['usage'] = $usage;
        }
        $effectiveDateOption = $this->effectiveDate;
        if ($effectiveDateOption->isDefined()) {
            $effectiveDate = $effectiveDateOption->get();
            $dataArray['effectiveDate'] = $effectiveDate;
        }
        $expirationDateOption = $this->expirationDate;
        if ($expirationDateOption->isDefined()) {
            $expirationDate = $expirationDateOption->get();
            $dataArray['expirationDate'] = $expirationDate;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): TaxpayerIdentificationBuilder
    {
        return new TaxpayerIdentificationBuilder(
            $this->number,
            $this->tinType,
            $this->usage,
            $this->effectiveDate,
            $this->expirationDate,
            $this->additionalProperties,
        );
    }
}
