<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see TrackingId}.
 */
final class TrackingIdBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $formId
     * @param Option<string>           $trackingIdType
     * @param Option<string>           $uspsApplicationId
     * @param Option<string>           $trackingNumber
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $formId,
        private Option $trackingIdType,
        private Option $uspsApplicationId,
        private Option $trackingNumber,
        private array $additionalProperties,
    ) {
    }

    /**
     * This is FedEx tracking Identifier associated with the package.
     *
     * Example: 8600
     */
    public function setFormId(string $formId): self
    {
        $this->formId = Some::create($formId);

        return $this;
    }

    /**
     * Specify the FedEx transportation type.
     *
     * Example: EXPRESS
     */
    public function setTrackingIdType(string $trackingIdType): self
    {
        $this->trackingIdType = Some::create($trackingIdType);

        return $this;
    }

    /**
     * Specify the USPS tracking Identifier associated with FedEx SmartPost shipment.
     *
     * Example: 92
     */
    public function setUspsApplicationId(string $uspsApplicationId): self
    {
        $this->uspsApplicationId = Some::create($uspsApplicationId);

        return $this;
    }

    /**
     * This is the number associated with the package that is used to track it.
     *
     * Example: 49XXX0000XXX20032835
     */
    public function setTrackingNumber(string $trackingNumber): self
    {
        $this->trackingNumber = Some::create($trackingNumber);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TrackingId
    {
        return new TrackingId(
            $this->formId,
            $this->trackingIdType,
            $this->uspsApplicationId,
            $this->trackingNumber,
            $this->additionalProperties,
        );
    }
}
