<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class TransactionDetailVO implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $transactionDetails
     * @param Option<string>           $transactionId
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $transactionDetails,
        private Option $transactionId,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): TransactionDetailVOBuilder
    {
        return new TransactionDetailVOBuilder(None::create(), None::create(), []);
    }

    /**
     * Includes data returned which governs data payload language/translations. The
     * TransactionDetail from the request is echoed back to the caller in the corresponding reply.
     *
     * Example: transactionDetails
     *
     * @return Option<string>
     */
    public function getTransactionDetails(): Option
    {
        return $this->transactionDetails;
    }

    /**
     * This element has a unique identifier added in your request, helps you match the request to
     * the reply. Maximum of 40 characters allowed.
     *
     * Example: XXXX_XXX123XXXXX.
     *
     * @return Option<string>
     */
    public function getTransactionId(): Option
    {
        return $this->transactionId;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $transactionDetails = None::create();
        $transactionId = None::create();
        if (array_key_exists('transactionDetails', $data) && $data['transactionDetails'] !== null) {
            $transactionDetailsRaw = $data['transactionDetails'];
            if (!is_string($transactionDetailsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "transactionDetails" must be string, got %s.',
                        get_debug_type($transactionDetailsRaw),
                    ),
                );
            }
            $transactionDetails = Some::create($transactionDetailsRaw);
        }
        if (array_key_exists('transactionId', $data) && $data['transactionId'] !== null) {
            $transactionIdRaw = $data['transactionId'];
            if (!is_string($transactionIdRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "transactionId" must be string, got %s.', get_debug_type($transactionIdRaw)),
                );
            }
            $transactionId = Some::create($transactionIdRaw);
        }
        $additionalProperties = array_diff_key($data, ['transactionDetails' => true, 'transactionId' => true]);

        return new self($transactionDetails, $transactionId, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $transactionDetailsOption = $this->transactionDetails;
        if ($transactionDetailsOption->isDefined()) {
            $transactionDetails = $transactionDetailsOption->get();
            $dataArray['transactionDetails'] = $transactionDetails;
        }
        $transactionIdOption = $this->transactionId;
        if ($transactionIdOption->isDefined()) {
            $transactionId = $transactionIdOption->get();
            $dataArray['transactionId'] = $transactionId;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): TransactionDetailVOBuilder
    {
        return new TransactionDetailVOBuilder(
            $this->transactionDetails,
            $this->transactionId,
            $this->additionalProperties,
        );
    }
}
