<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_string;
use function sprintf;

final readonly class UsmcaCertificationOfOriginDetail implements SelfNormalizingModel
{
    /**
     * @param Option<list<CustomerImageUsage>>                                                        $customerImageUsages
     * @param Option<ShippingDocumentFormat>                                                          $documentFormat
     * @param Option<UsmcaCertificationOfOriginDetailCertifierSpecification|UnknownEnumValue<string>> $certifierSpecification
     * @param Option<UsmcaCertificationOfOriginDetailImporterSpecification|UnknownEnumValue<string>>  $importerSpecification
     * @param Option<UsmcaCertificationOfOriginDetailProducerSpecification|UnknownEnumValue<string>>  $producerSpecification
     * @param Option<Party3>                                                                          $producer
     * @param Option<RetrieveDateRange>                                                               $blanketPeriod
     * @param Option<string>                                                                          $certifierJobTitle
     * @param array<int|string, mixed>                                                                $additionalProperties
     */
    public function __construct(
        private Option $customerImageUsages,
        private Option $documentFormat,
        private Option $certifierSpecification,
        private Option $importerSpecification,
        private Option $producerSpecification,
        private Option $producer,
        private Option $blanketPeriod,
        private Option $certifierJobTitle,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): UsmcaCertificationOfOriginDetailBuilder
    {
        return new UsmcaCertificationOfOriginDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Specifies the usage and identification of customer supplied images to be used on this
     * document.
     *
     * @return Option<list<CustomerImageUsage>>
     */
    public function getCustomerImageUsages(): Option
    {
        return $this->customerImageUsages;
    }

    /**
     * Specify the shipping document format.
     *
     * @return Option<ShippingDocumentFormat>
     */
    public function getDocumentFormat(): Option
    {
        return $this->documentFormat;
    }

    /**
     * This is certifier specification.
     *
     * @return Option<UsmcaCertificationOfOriginDetailCertifierSpecification|UnknownEnumValue<string>>
     */
    public function getCertifierSpecification(): Option
    {
        return $this->certifierSpecification;
    }

    /**
     * This is importer specification.
     *
     * @return Option<UsmcaCertificationOfOriginDetailImporterSpecification|UnknownEnumValue<string>>
     */
    public function getImporterSpecification(): Option
    {
        return $this->importerSpecification;
    }

    /**
     * This is producer specification.
     *
     * @return Option<UsmcaCertificationOfOriginDetailProducerSpecification|UnknownEnumValue<string>>
     */
    public function getProducerSpecification(): Option
    {
        return $this->producerSpecification;
    }

    /** @return Option<Party3> */
    public function getProducer(): Option
    {
        return $this->producer;
    }

    /**
     * Date Range for custom delivery request; only used if type is BETWEEN.
     *
     * @return Option<RetrieveDateRange>
     */
    public function getBlanketPeriod(): Option
    {
        return $this->blanketPeriod;
    }

    /**
     * Specify the job title of the certifier.
     *
     * @return Option<string>
     */
    public function getCertifierJobTitle(): Option
    {
        return $this->certifierJobTitle;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $customerImageUsages = None::create();
        $documentFormat = None::create();
        $certifierSpecification = None::create();
        $importerSpecification = None::create();
        $producerSpecification = None::create();
        $producer = None::create();
        $blanketPeriod = None::create();
        $certifierJobTitle = None::create();
        if (array_key_exists('customerImageUsages', $data) && $data['customerImageUsages'] !== null) {
            $customerImageUsagesRaw = $data['customerImageUsages'];
            if (!(is_array($customerImageUsagesRaw) && array_is_list($customerImageUsagesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "customerImageUsages" must be list, got %s.',
                        get_debug_type($customerImageUsagesRaw),
                    ),
                );
            }
            $customerImageUsages = Some::create(array_map(static function (mixed $value): CustomerImageUsage {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return CustomerImageUsage::fromArray($valueTyped);
            }, $customerImageUsagesRaw));
        }
        if (array_key_exists('documentFormat', $data) && $data['documentFormat'] !== null) {
            $documentFormatRaw = $data['documentFormat'];
            if (!is_array($documentFormatRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "documentFormat" must be object, got %s.', get_debug_type($documentFormatRaw)),
                );
            }
            /** @var array<string, mixed> $documentFormatRawTyped */
            $documentFormatRawTyped = $documentFormatRaw;
            $documentFormat = Some::create(ShippingDocumentFormat::fromArray($documentFormatRawTyped));
        }
        if (array_key_exists('certifierSpecification', $data) && $data['certifierSpecification'] !== null) {
            $certifierSpecificationRaw = $data['certifierSpecification'];
            if (!is_string($certifierSpecificationRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "certifierSpecification" must be string, got %s.',
                        get_debug_type($certifierSpecificationRaw),
                    ),
                );
            }
            $certifierSpecification = Some::create(
                UsmcaCertificationOfOriginDetailCertifierSpecification::tryFrom($certifierSpecificationRaw)
                    ?? UnknownEnumValue::of($certifierSpecificationRaw),
            );
        }
        if (array_key_exists('importerSpecification', $data) && $data['importerSpecification'] !== null) {
            $importerSpecificationRaw = $data['importerSpecification'];
            if (!is_string($importerSpecificationRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "importerSpecification" must be string, got %s.',
                        get_debug_type($importerSpecificationRaw),
                    ),
                );
            }
            $importerSpecification = Some::create(
                UsmcaCertificationOfOriginDetailImporterSpecification::tryFrom($importerSpecificationRaw)
                    ?? UnknownEnumValue::of($importerSpecificationRaw),
            );
        }
        if (array_key_exists('producerSpecification', $data) && $data['producerSpecification'] !== null) {
            $producerSpecificationRaw = $data['producerSpecification'];
            if (!is_string($producerSpecificationRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "producerSpecification" must be string, got %s.',
                        get_debug_type($producerSpecificationRaw),
                    ),
                );
            }
            $producerSpecification = Some::create(
                UsmcaCertificationOfOriginDetailProducerSpecification::tryFrom($producerSpecificationRaw)
                    ?? UnknownEnumValue::of($producerSpecificationRaw),
            );
        }
        if (array_key_exists('producer', $data) && $data['producer'] !== null) {
            $producerRaw = $data['producer'];
            if (!is_array($producerRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "producer" must be object, got %s.', get_debug_type($producerRaw)),
                );
            }
            /** @var array<string, mixed> $producerRawTyped */
            $producerRawTyped = $producerRaw;
            $producer = Some::create(Party3::fromArray($producerRawTyped));
        }
        if (array_key_exists('blanketPeriod', $data) && $data['blanketPeriod'] !== null) {
            $blanketPeriodRaw = $data['blanketPeriod'];
            if (!is_array($blanketPeriodRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "blanketPeriod" must be object, got %s.', get_debug_type($blanketPeriodRaw)),
                );
            }
            /** @var array<string, mixed> $blanketPeriodRawTyped */
            $blanketPeriodRawTyped = $blanketPeriodRaw;
            $blanketPeriod = Some::create(RetrieveDateRange::fromArray($blanketPeriodRawTyped));
        }
        if (array_key_exists('certifierJobTitle', $data) && $data['certifierJobTitle'] !== null) {
            $certifierJobTitleRaw = $data['certifierJobTitle'];
            if (!is_string($certifierJobTitleRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "certifierJobTitle" must be string, got %s.',
                        get_debug_type($certifierJobTitleRaw),
                    ),
                );
            }
            $certifierJobTitle = Some::create($certifierJobTitleRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'customerImageUsages' => true,
                'documentFormat' => true,
                'certifierSpecification' => true,
                'importerSpecification' => true,
                'producerSpecification' => true,
                'producer' => true,
                'blanketPeriod' => true,
                'certifierJobTitle' => true,
            ],
        );

        return new self(
            $customerImageUsages,
            $documentFormat,
            $certifierSpecification,
            $importerSpecification,
            $producerSpecification,
            $producer,
            $blanketPeriod,
            $certifierJobTitle,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $customerImageUsagesOption = $this->customerImageUsages;
        if ($customerImageUsagesOption->isDefined()) {
            $customerImageUsages = $customerImageUsagesOption->get();
            $values = [];
            foreach ($customerImageUsages as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['customerImageUsages'] = $values;
        }
        $documentFormatOption = $this->documentFormat;
        if ($documentFormatOption->isDefined()) {
            $documentFormat = $documentFormatOption->get();
            $dataArray['documentFormat'] = $normalizationTarget->model($documentFormat);
        }
        $certifierSpecificationOption = $this->certifierSpecification;
        if ($certifierSpecificationOption->isDefined()) {
            $certifierSpecification = $certifierSpecificationOption->get();
            $dataArray['certifierSpecification'] = $certifierSpecification->value;
        }
        $importerSpecificationOption = $this->importerSpecification;
        if ($importerSpecificationOption->isDefined()) {
            $importerSpecification = $importerSpecificationOption->get();
            $dataArray['importerSpecification'] = $importerSpecification->value;
        }
        $producerSpecificationOption = $this->producerSpecification;
        if ($producerSpecificationOption->isDefined()) {
            $producerSpecification = $producerSpecificationOption->get();
            $dataArray['producerSpecification'] = $producerSpecification->value;
        }
        $producerOption = $this->producer;
        if ($producerOption->isDefined()) {
            $producer = $producerOption->get();
            $dataArray['producer'] = $normalizationTarget->model($producer);
        }
        $blanketPeriodOption = $this->blanketPeriod;
        if ($blanketPeriodOption->isDefined()) {
            $blanketPeriod = $blanketPeriodOption->get();
            $dataArray['blanketPeriod'] = $normalizationTarget->model($blanketPeriod);
        }
        $certifierJobTitleOption = $this->certifierJobTitle;
        if ($certifierJobTitleOption->isDefined()) {
            $certifierJobTitle = $certifierJobTitleOption->get();
            $dataArray['certifierJobTitle'] = $certifierJobTitle;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): UsmcaCertificationOfOriginDetailBuilder
    {
        return new UsmcaCertificationOfOriginDetailBuilder(
            $this->customerImageUsages,
            $this->documentFormat,
            $this->certifierSpecification,
            $this->importerSpecification,
            $this->producerSpecification,
            $this->producer,
            $this->blanketPeriod,
            $this->certifierJobTitle,
            $this->additionalProperties,
        );
    }
}
