<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

enum UsmcaCommercialInvoiceCertificationOfOriginDetailProducerSpecification: string
{
    case AVAILABLE_UPON_REQUEST = 'AVAILABLE_UPON_REQUEST';
    case VARIOUS = 'VARIOUS';
    case SAME_AS_EXPORTER = 'SAME_AS_EXPORTER';
}
