<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_int;
use function is_string;
use function sprintf;

final readonly class ValidatedHazardousCommodityDescription implements SelfNormalizingModel
{
    /**
     * @param Option<int>              $sequenceNumber
     * @param Option<string>           $packingInstructions
     * @param Option<list<string>>     $subsidiaryClasses
     * @param Option<string>           $labelText
     * @param Option<string>           $tunnelRestrictionCode
     * @param Option<string>           $specialProvisions
     * @param Option<string>           $properShippingNameAndDescription
     * @param Option<string>           $technicalName
     * @param Option<string>           $symbols
     * @param Option<string>           $authorization
     * @param Option<list<string>>     $attributes
     * @param Option<string>           $id
     * @param Option<string>           $packingGroup
     * @param Option<string>           $properShippingName
     * @param Option<string>           $hazardClass
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $sequenceNumber,
        private Option $packingInstructions,
        private Option $subsidiaryClasses,
        private Option $labelText,
        private Option $tunnelRestrictionCode,
        private Option $specialProvisions,
        private Option $properShippingNameAndDescription,
        private Option $technicalName,
        private Option $symbols,
        private Option $authorization,
        private Option $attributes,
        private Option $id,
        private Option $packingGroup,
        private Option $properShippingName,
        private Option $hazardClass,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ValidatedHazardousCommodityDescriptionBuilder
    {
        return new ValidatedHazardousCommodityDescriptionBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * In conjunction with the regulatory identifier, this field uniquely identifies a specific
     * hazardous materials commodity.
     *
     * Example: 876
     *
     * @return Option<int>
     */
    public function getSequenceNumber(): Option
    {
        return $this->sequenceNumber;
    }

    /**
     * Specifies Packing Instructions.
     *
     * Example: packingInstructions
     *
     * @return Option<string>
     */
    public function getPackingInstructions(): Option
    {
        return $this->packingInstructions;
    }

    /**
     * Specifies subsidiary Classes.
     *
     * Example:["Subsidiary Classes"]
     *
     * @return Option<list<string>>
     */
    public function getSubsidiaryClasses(): Option
    {
        return $this->subsidiaryClasses;
    }

    /**
     * Specifies Hazard Label Text.
     *
     * Example: labelText
     *
     * @return Option<string>
     */
    public function getLabelText(): Option
    {
        return $this->labelText;
    }

    /**
     * There are five categories of tunnel categorization with A representing the least restrictive
     * and E as the most restrictive. Category A, as the least restrictive, will not be sign-posted.
     * Category E, the most restrictive, only allows the passage of UN2919, UN3291, UN3331, UN3359
     * and UN3373.
     *
     * Example: UN2919
     *
     * @return Option<string>
     */
    public function getTunnelRestrictionCode(): Option
    {
        return $this->tunnelRestrictionCode;
    }

    /**
     * Specifies Special Provisions if any.
     *
     * Example: specialProvisions
     *
     * @return Option<string>
     */
    public function getSpecialProvisions(): Option
    {
        return $this->specialProvisions;
    }

    /**
     * Fully-expanded descriptive text for a hazardous commodity.
     *
     * Example: properShippingNameAndDescription
     *
     * @return Option<string>
     */
    public function getProperShippingNameAndDescription(): Option
    {
        return $this->properShippingNameAndDescription;
    }

    /**
     * Specifies Technical Name.
     *
     * Example: technicalName
     *
     * @return Option<string>
     */
    public function getTechnicalName(): Option
    {
        return $this->technicalName;
    }

    /**
     * Specifies Symbols.
     *
     * Example: symbols
     *
     * @return Option<string>
     */
    public function getSymbols(): Option
    {
        return $this->symbols;
    }

    /**
     * Information related to quantity limitations and operator or state variations as may be
     * applicable to the dangerous goods commodity.
     *
     * @return Option<string>
     */
    public function getAuthorization(): Option
    {
        return $this->authorization;
    }

    /**
     * Specifies attributes.
     *
     * Example: ["attributes"]
     *
     * @return Option<list<string>>
     */
    public function getAttributes(): Option
    {
        return $this->attributes;
    }

    /**
     * Specifies the Identification.
     *
     * Example: 1234
     *
     * @return Option<string>
     */
    public function getId(): Option
    {
        return $this->id;
    }

    /**
     * Specifies packing Group.
     *
     * Example: Packing Group
     *
     * @return Option<string>
     */
    public function getPackingGroup(): Option
    {
        return $this->packingGroup;
    }

    /**
     * Specifies Proper Shipping Name.
     *
     * Example: Proper Shipping Name
     *
     * @return Option<string>
     */
    public function getProperShippingName(): Option
    {
        return $this->properShippingName;
    }

    /**
     * Specifies hazard class.
     *
     * Example: Hazard Class
     *
     * @return Option<string>
     */
    public function getHazardClass(): Option
    {
        return $this->hazardClass;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $sequenceNumber = None::create();
        $packingInstructions = None::create();
        $subsidiaryClasses = None::create();
        $labelText = None::create();
        $tunnelRestrictionCode = None::create();
        $specialProvisions = None::create();
        $properShippingNameAndDescription = None::create();
        $technicalName = None::create();
        $symbols = None::create();
        $authorization = None::create();
        $attributes = None::create();
        $id = None::create();
        $packingGroup = None::create();
        $properShippingName = None::create();
        $hazardClass = None::create();
        if (array_key_exists('sequenceNumber', $data) && $data['sequenceNumber'] !== null) {
            $sequenceNumberRaw = $data['sequenceNumber'];
            if (!is_int($sequenceNumberRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "sequenceNumber" must be int, got %s.', get_debug_type($sequenceNumberRaw)),
                );
            }
            $sequenceNumber = Some::create($sequenceNumberRaw);
        }
        if (array_key_exists('packingInstructions', $data) && $data['packingInstructions'] !== null) {
            $packingInstructionsRaw = $data['packingInstructions'];
            if (!is_string($packingInstructionsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "packingInstructions" must be string, got %s.',
                        get_debug_type($packingInstructionsRaw),
                    ),
                );
            }
            $packingInstructions = Some::create($packingInstructionsRaw);
        }
        if (array_key_exists('subsidiaryClasses', $data) && $data['subsidiaryClasses'] !== null) {
            $subsidiaryClassesRaw = $data['subsidiaryClasses'];
            if (!(is_array($subsidiaryClassesRaw) && array_is_list($subsidiaryClassesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "subsidiaryClasses" must be list, got %s.',
                        get_debug_type($subsidiaryClassesRaw),
                    ),
                );
            }
            $subsidiaryClasses = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $subsidiaryClassesRaw));
        }
        if (array_key_exists('labelText', $data) && $data['labelText'] !== null) {
            $labelTextRaw = $data['labelText'];
            if (!is_string($labelTextRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "labelText" must be string, got %s.', get_debug_type($labelTextRaw)),
                );
            }
            $labelText = Some::create($labelTextRaw);
        }
        if (array_key_exists('tunnelRestrictionCode', $data) && $data['tunnelRestrictionCode'] !== null) {
            $tunnelRestrictionCodeRaw = $data['tunnelRestrictionCode'];
            if (!is_string($tunnelRestrictionCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "tunnelRestrictionCode" must be string, got %s.',
                        get_debug_type($tunnelRestrictionCodeRaw),
                    ),
                );
            }
            $tunnelRestrictionCode = Some::create($tunnelRestrictionCodeRaw);
        }
        if (array_key_exists('specialProvisions', $data) && $data['specialProvisions'] !== null) {
            $specialProvisionsRaw = $data['specialProvisions'];
            if (!is_string($specialProvisionsRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "specialProvisions" must be string, got %s.',
                        get_debug_type($specialProvisionsRaw),
                    ),
                );
            }
            $specialProvisions = Some::create($specialProvisionsRaw);
        }
        if (
            array_key_exists('properShippingNameAndDescription', $data)
            && $data['properShippingNameAndDescription'] !== null
        ) {
            $properShippingNameAndDescriptionRaw = $data['properShippingNameAndDescription'];
            if (!is_string($properShippingNameAndDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "properShippingNameAndDescription" must be string, got %s.',
                        get_debug_type($properShippingNameAndDescriptionRaw),
                    ),
                );
            }
            $properShippingNameAndDescription = Some::create($properShippingNameAndDescriptionRaw);
        }
        if (array_key_exists('technicalName', $data) && $data['technicalName'] !== null) {
            $technicalNameRaw = $data['technicalName'];
            if (!is_string($technicalNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "technicalName" must be string, got %s.', get_debug_type($technicalNameRaw)),
                );
            }
            $technicalName = Some::create($technicalNameRaw);
        }
        if (array_key_exists('symbols', $data) && $data['symbols'] !== null) {
            $symbolsRaw = $data['symbols'];
            if (!is_string($symbolsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "symbols" must be string, got %s.', get_debug_type($symbolsRaw)),
                );
            }
            $symbols = Some::create($symbolsRaw);
        }
        if (array_key_exists('authorization', $data) && $data['authorization'] !== null) {
            $authorizationRaw = $data['authorization'];
            if (!is_string($authorizationRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "authorization" must be string, got %s.', get_debug_type($authorizationRaw)),
                );
            }
            $authorization = Some::create($authorizationRaw);
        }
        if (array_key_exists('attributes', $data) && $data['attributes'] !== null) {
            $attributesRaw = $data['attributes'];
            if (!(is_array($attributesRaw) && array_is_list($attributesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "attributes" must be list, got %s.', get_debug_type($attributesRaw)),
                );
            }
            $attributes = Some::create(array_map(static function (mixed $value_1): string {
                if (!is_string($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_1)),
                    );
                }

                return $value_1;
            }, $attributesRaw));
        }
        if (array_key_exists('id', $data) && $data['id'] !== null) {
            $idRaw = $data['id'];
            if (!is_string($idRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "id" must be string, got %s.', get_debug_type($idRaw)),
                );
            }
            $id = Some::create($idRaw);
        }
        if (array_key_exists('packingGroup', $data) && $data['packingGroup'] !== null) {
            $packingGroupRaw = $data['packingGroup'];
            if (!is_string($packingGroupRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "packingGroup" must be string, got %s.', get_debug_type($packingGroupRaw)),
                );
            }
            $packingGroup = Some::create($packingGroupRaw);
        }
        if (array_key_exists('properShippingName', $data) && $data['properShippingName'] !== null) {
            $properShippingNameRaw = $data['properShippingName'];
            if (!is_string($properShippingNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "properShippingName" must be string, got %s.',
                        get_debug_type($properShippingNameRaw),
                    ),
                );
            }
            $properShippingName = Some::create($properShippingNameRaw);
        }
        if (array_key_exists('hazardClass', $data) && $data['hazardClass'] !== null) {
            $hazardClassRaw = $data['hazardClass'];
            if (!is_string($hazardClassRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "hazardClass" must be string, got %s.', get_debug_type($hazardClassRaw)),
                );
            }
            $hazardClass = Some::create($hazardClassRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'sequenceNumber' => true,
                'packingInstructions' => true,
                'subsidiaryClasses' => true,
                'labelText' => true,
                'tunnelRestrictionCode' => true,
                'specialProvisions' => true,
                'properShippingNameAndDescription' => true,
                'technicalName' => true,
                'symbols' => true,
                'authorization' => true,
                'attributes' => true,
                'id' => true,
                'packingGroup' => true,
                'properShippingName' => true,
                'hazardClass' => true,
            ],
        );

        return new self(
            $sequenceNumber,
            $packingInstructions,
            $subsidiaryClasses,
            $labelText,
            $tunnelRestrictionCode,
            $specialProvisions,
            $properShippingNameAndDescription,
            $technicalName,
            $symbols,
            $authorization,
            $attributes,
            $id,
            $packingGroup,
            $properShippingName,
            $hazardClass,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $sequenceNumberOption = $this->sequenceNumber;
        if ($sequenceNumberOption->isDefined()) {
            $sequenceNumber = $sequenceNumberOption->get();
            $dataArray['sequenceNumber'] = $sequenceNumber;
        }
        $packingInstructionsOption = $this->packingInstructions;
        if ($packingInstructionsOption->isDefined()) {
            $packingInstructions = $packingInstructionsOption->get();
            $dataArray['packingInstructions'] = $packingInstructions;
        }
        $subsidiaryClassesOption = $this->subsidiaryClasses;
        if ($subsidiaryClassesOption->isDefined()) {
            $subsidiaryClasses = $subsidiaryClassesOption->get();
            $values = [];
            foreach ($subsidiaryClasses as $value) {
                $values[] = $value;
            }
            $dataArray['subsidiaryClasses'] = $values;
        }
        $labelTextOption = $this->labelText;
        if ($labelTextOption->isDefined()) {
            $labelText = $labelTextOption->get();
            $dataArray['labelText'] = $labelText;
        }
        $tunnelRestrictionCodeOption = $this->tunnelRestrictionCode;
        if ($tunnelRestrictionCodeOption->isDefined()) {
            $tunnelRestrictionCode = $tunnelRestrictionCodeOption->get();
            $dataArray['tunnelRestrictionCode'] = $tunnelRestrictionCode;
        }
        $specialProvisionsOption = $this->specialProvisions;
        if ($specialProvisionsOption->isDefined()) {
            $specialProvisions = $specialProvisionsOption->get();
            $dataArray['specialProvisions'] = $specialProvisions;
        }
        $properShippingNameAndDescriptionOption = $this->properShippingNameAndDescription;
        if ($properShippingNameAndDescriptionOption->isDefined()) {
            $properShippingNameAndDescription = $properShippingNameAndDescriptionOption->get();
            $dataArray['properShippingNameAndDescription'] = $properShippingNameAndDescription;
        }
        $technicalNameOption = $this->technicalName;
        if ($technicalNameOption->isDefined()) {
            $technicalName = $technicalNameOption->get();
            $dataArray['technicalName'] = $technicalName;
        }
        $symbolsOption = $this->symbols;
        if ($symbolsOption->isDefined()) {
            $symbols = $symbolsOption->get();
            $dataArray['symbols'] = $symbols;
        }
        $authorizationOption = $this->authorization;
        if ($authorizationOption->isDefined()) {
            $authorization = $authorizationOption->get();
            $dataArray['authorization'] = $authorization;
        }
        $attributesOption = $this->attributes;
        if ($attributesOption->isDefined()) {
            $attributes = $attributesOption->get();
            $values_1 = [];
            foreach ($attributes as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['attributes'] = $values_1;
        }
        $idOption = $this->id;
        if ($idOption->isDefined()) {
            $id = $idOption->get();
            $dataArray['id'] = $id;
        }
        $packingGroupOption = $this->packingGroup;
        if ($packingGroupOption->isDefined()) {
            $packingGroup = $packingGroupOption->get();
            $dataArray['packingGroup'] = $packingGroup;
        }
        $properShippingNameOption = $this->properShippingName;
        if ($properShippingNameOption->isDefined()) {
            $properShippingName = $properShippingNameOption->get();
            $dataArray['properShippingName'] = $properShippingName;
        }
        $hazardClassOption = $this->hazardClass;
        if ($hazardClassOption->isDefined()) {
            $hazardClass = $hazardClassOption->get();
            $dataArray['hazardClass'] = $hazardClass;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ValidatedHazardousCommodityDescriptionBuilder
    {
        return new ValidatedHazardousCommodityDescriptionBuilder(
            $this->sequenceNumber,
            $this->packingInstructions,
            $this->subsidiaryClasses,
            $this->labelText,
            $this->tunnelRestrictionCode,
            $this->specialProvisions,
            $this->properShippingNameAndDescription,
            $this->technicalName,
            $this->symbols,
            $this->authorization,
            $this->attributes,
            $this->id,
            $this->packingGroup,
            $this->properShippingName,
            $this->hazardClass,
            $this->additionalProperties,
        );
    }
}
