<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_float;
use function is_int;
use function sprintf;

final readonly class ValidatedHazardousCommodityContent implements SelfNormalizingModel
{
    /**
     * @param Option<HazardousCommodityQuantityDetail>       $quantity
     * @param Option<HazardousCommodityOptionDetail>         $options
     * @param Option<ValidatedHazardousCommodityDescription> $description
     * @param Option<NetExplosiveDetail>                     $netExplosiveDetail
     * @param Option<float>                                  $massPoints
     * @param array<int|string, mixed>                       $additionalProperties
     */
    public function __construct(
        private Option $quantity,
        private Option $options,
        private Option $description,
        private Option $netExplosiveDetail,
        private Option $massPoints,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ValidatedHazardousCommodityContentBuilder
    {
        return new ValidatedHazardousCommodityContentBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Indicates hazardous commodity quantity details.
     *
     * @return Option<HazardousCommodityQuantityDetail>
     */
    public function getQuantity(): Option
    {
        return $this->quantity;
    }

    /**
     * Provides details of Hazardous Commodity Option Detail.
     *
     * @return Option<HazardousCommodityOptionDetail>
     */
    public function getOptions(): Option
    {
        return $this->options;
    }

    /**
     * Identifies and describes an individual hazardous commodity. For 201001 load, this is based on
     * data from the FedEx Ground Hazardous Materials Shipping Guide.
     *
     * @return Option<ValidatedHazardousCommodityDescription>
     */
    public function getDescription(): Option
    {
        return $this->description;
    }

    /**
     * Specifies the total mass of the contained explosive substances, without the mass of any
     * casings, bullets, shells, etc.
     *
     * @return Option<NetExplosiveDetail>
     */
    public function getNetExplosiveDetail(): Option
    {
        return $this->netExplosiveDetail;
    }

    /**
     * The mass points are a calculation used by ADR regulations for measuring the risk of a
     * particular hazardous commodity.
     *
     * Example: 2.0
     *
     * @return Option<float>
     */
    public function getMassPoints(): Option
    {
        return $this->massPoints;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $quantity = None::create();
        $options = None::create();
        $description = None::create();
        $netExplosiveDetail = None::create();
        $massPoints = None::create();
        if (array_key_exists('massPoints', $data) && is_int($data['massPoints'])) {
            $data['massPoints'] = (float) $data['massPoints'];
        }
        if (array_key_exists('quantity', $data) && $data['quantity'] !== null) {
            $quantityRaw = $data['quantity'];
            if (!is_array($quantityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "quantity" must be object, got %s.', get_debug_type($quantityRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $quantityRawTyped */
            $quantityRawTyped = $quantityRaw;
            $quantity = Some::create(HazardousCommodityQuantityDetail::fromArray($quantityRawTyped));
        }
        if (array_key_exists('options', $data) && $data['options'] !== null) {
            $optionsRaw = $data['options'];
            if (!is_array($optionsRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "options" must be object, got %s.', get_debug_type($optionsRaw)),
                );
            }
            /** @var array<string, mixed> $optionsRawTyped */
            $optionsRawTyped = $optionsRaw;
            $options = Some::create(HazardousCommodityOptionDetail::fromArray($optionsRawTyped));
        }
        if (array_key_exists('description', $data) && $data['description'] !== null) {
            $descriptionRaw = $data['description'];
            if (!is_array($descriptionRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "description" must be object, got %s.', get_debug_type($descriptionRaw)),
                );
            }
            /** @var array<string, mixed> $descriptionRawTyped */
            $descriptionRawTyped = $descriptionRaw;
            $description = Some::create(ValidatedHazardousCommodityDescription::fromArray($descriptionRawTyped));
        }
        if (array_key_exists('netExplosiveDetail', $data) && $data['netExplosiveDetail'] !== null) {
            $netExplosiveDetailRaw = $data['netExplosiveDetail'];
            if (!is_array($netExplosiveDetailRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "netExplosiveDetail" must be object, got %s.',
                        get_debug_type($netExplosiveDetailRaw),
                    ),
                );
            }
            /** @var array<string, mixed> $netExplosiveDetailRawTyped */
            $netExplosiveDetailRawTyped = $netExplosiveDetailRaw;
            $netExplosiveDetail = Some::create(NetExplosiveDetail::fromArray($netExplosiveDetailRawTyped));
        }
        if (array_key_exists('massPoints', $data) && $data['massPoints'] !== null) {
            $massPointsRaw = $data['massPoints'];
            if (!(is_float($massPointsRaw) || is_int($massPointsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "massPoints" must be number, got %s.', get_debug_type($massPointsRaw)),
                );
            }
            $massPoints = Some::create((float) $massPointsRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'quantity' => true,
                'options' => true,
                'description' => true,
                'netExplosiveDetail' => true,
                'massPoints' => true,
            ],
        );

        return new self($quantity, $options, $description, $netExplosiveDetail, $massPoints, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $quantityOption = $this->quantity;
        if ($quantityOption->isDefined()) {
            $quantity = $quantityOption->get();
            $dataArray['quantity'] = $normalizationTarget->model($quantity);
        }
        $optionsOption = $this->options;
        if ($optionsOption->isDefined()) {
            $options = $optionsOption->get();
            $dataArray['options'] = $normalizationTarget->model($options);
        }
        $descriptionOption = $this->description;
        if ($descriptionOption->isDefined()) {
            $description = $descriptionOption->get();
            $dataArray['description'] = $normalizationTarget->model($description);
        }
        $netExplosiveDetailOption = $this->netExplosiveDetail;
        if ($netExplosiveDetailOption->isDefined()) {
            $netExplosiveDetail = $netExplosiveDetailOption->get();
            $dataArray['netExplosiveDetail'] = $normalizationTarget->model($netExplosiveDetail);
        }
        $massPointsOption = $this->massPoints;
        if ($massPointsOption->isDefined()) {
            $massPoints = $massPointsOption->get();
            $dataArray['massPoints'] = $massPoints;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ValidatedHazardousCommodityContentBuilder
    {
        return new ValidatedHazardousCommodityContentBuilder(
            $this->quantity,
            $this->options,
            $this->description,
            $this->netExplosiveDetail,
            $this->massPoints,
            $this->additionalProperties,
        );
    }
}
