<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ValidatedHazardousCommodityContent}.
 */
final class ValidatedHazardousCommodityContentBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<HazardousCommodityQuantityDetail>       $quantity
     * @param Option<HazardousCommodityOptionDetail>         $options
     * @param Option<ValidatedHazardousCommodityDescription> $description
     * @param Option<NetExplosiveDetail>                     $netExplosiveDetail
     * @param Option<float>                                  $massPoints
     * @param array<int|string, mixed>                       $additionalProperties
     */
    public function __construct(
        private Option $quantity,
        private Option $options,
        private Option $description,
        private Option $netExplosiveDetail,
        private Option $massPoints,
        private array $additionalProperties,
    ) {
    }

    /**
     * Indicates hazardous commodity quantity details.
     */
    public function setQuantity(HazardousCommodityQuantityDetail $quantity): self
    {
        $this->quantity = Some::create($quantity);

        return $this;
    }

    /**
     * Provides details of Hazardous Commodity Option Detail.
     */
    public function setOptions(HazardousCommodityOptionDetail $options): self
    {
        $this->options = Some::create($options);

        return $this;
    }

    /**
     * Identifies and describes an individual hazardous commodity. For 201001 load, this is based on
     * data from the FedEx Ground Hazardous Materials Shipping Guide.
     */
    public function setDescription(ValidatedHazardousCommodityDescription $description): self
    {
        $this->description = Some::create($description);

        return $this;
    }

    /**
     * Specifies the total mass of the contained explosive substances, without the mass of any
     * casings, bullets, shells, etc.
     */
    public function setNetExplosiveDetail(NetExplosiveDetail $netExplosiveDetail): self
    {
        $this->netExplosiveDetail = Some::create($netExplosiveDetail);

        return $this;
    }

    /**
     * The mass points are a calculation used by ADR regulations for measuring the risk of a
     * particular hazardous commodity.
     *
     * Example: 2.0
     */
    public function setMassPoints(float $massPoints): self
    {
        $this->massPoints = Some::create($massPoints);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ValidatedHazardousCommodityContent
    {
        return new ValidatedHazardousCommodityContent(
            $this->quantity,
            $this->options,
            $this->description,
            $this->netExplosiveDetail,
            $this->massPoints,
            $this->additionalProperties,
        );
    }
}
