<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see ValidatedHazardousCommodityDescription}.
 */
final class ValidatedHazardousCommodityDescriptionBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<int>              $sequenceNumber
     * @param Option<string>           $packingInstructions
     * @param Option<list<string>>     $subsidiaryClasses
     * @param Option<string>           $labelText
     * @param Option<string>           $tunnelRestrictionCode
     * @param Option<string>           $specialProvisions
     * @param Option<string>           $properShippingNameAndDescription
     * @param Option<string>           $technicalName
     * @param Option<string>           $symbols
     * @param Option<string>           $authorization
     * @param Option<list<string>>     $attributes
     * @param Option<string>           $id
     * @param Option<string>           $packingGroup
     * @param Option<string>           $properShippingName
     * @param Option<string>           $hazardClass
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $sequenceNumber,
        private Option $packingInstructions,
        private Option $subsidiaryClasses,
        private Option $labelText,
        private Option $tunnelRestrictionCode,
        private Option $specialProvisions,
        private Option $properShippingNameAndDescription,
        private Option $technicalName,
        private Option $symbols,
        private Option $authorization,
        private Option $attributes,
        private Option $id,
        private Option $packingGroup,
        private Option $properShippingName,
        private Option $hazardClass,
        private array $additionalProperties,
    ) {
    }

    /**
     * In conjunction with the regulatory identifier, this field uniquely identifies a specific
     * hazardous materials commodity.
     *
     * Example: 876
     */
    public function setSequenceNumber(int $sequenceNumber): self
    {
        $this->sequenceNumber = Some::create($sequenceNumber);

        return $this;
    }

    /**
     * Specifies Packing Instructions.
     *
     * Example: packingInstructions
     */
    public function setPackingInstructions(string $packingInstructions): self
    {
        $this->packingInstructions = Some::create($packingInstructions);

        return $this;
    }

    /**
     * Specifies subsidiary Classes.
     *
     * Example:["Subsidiary Classes"]
     *
     * @param list<string> $subsidiaryClasses
     */
    public function setSubsidiaryClasses(array $subsidiaryClasses): self
    {
        $this->subsidiaryClasses = Some::create($subsidiaryClasses);

        return $this;
    }

    /**
     * Specifies Hazard Label Text.
     *
     * Example: labelText
     */
    public function setLabelText(string $labelText): self
    {
        $this->labelText = Some::create($labelText);

        return $this;
    }

    /**
     * There are five categories of tunnel categorization with A representing the least restrictive
     * and E as the most restrictive. Category A, as the least restrictive, will not be sign-posted.
     * Category E, the most restrictive, only allows the passage of UN2919, UN3291, UN3331, UN3359
     * and UN3373.
     *
     * Example: UN2919
     */
    public function setTunnelRestrictionCode(string $tunnelRestrictionCode): self
    {
        $this->tunnelRestrictionCode = Some::create($tunnelRestrictionCode);

        return $this;
    }

    /**
     * Specifies Special Provisions if any.
     *
     * Example: specialProvisions
     */
    public function setSpecialProvisions(string $specialProvisions): self
    {
        $this->specialProvisions = Some::create($specialProvisions);

        return $this;
    }

    /**
     * Fully-expanded descriptive text for a hazardous commodity.
     *
     * Example: properShippingNameAndDescription
     */
    public function setProperShippingNameAndDescription(string $properShippingNameAndDescription): self
    {
        $this->properShippingNameAndDescription = Some::create($properShippingNameAndDescription);

        return $this;
    }

    /**
     * Specifies Technical Name.
     *
     * Example: technicalName
     */
    public function setTechnicalName(string $technicalName): self
    {
        $this->technicalName = Some::create($technicalName);

        return $this;
    }

    /**
     * Specifies Symbols.
     *
     * Example: symbols
     */
    public function setSymbols(string $symbols): self
    {
        $this->symbols = Some::create($symbols);

        return $this;
    }

    /**
     * Information related to quantity limitations and operator or state variations as may be
     * applicable to the dangerous goods commodity.
     */
    public function setAuthorization(string $authorization): self
    {
        $this->authorization = Some::create($authorization);

        return $this;
    }

    /**
     * Specifies attributes.
     *
     * Example: ["attributes"]
     *
     * @param list<string> $attributes
     */
    public function setAttributes(array $attributes): self
    {
        $this->attributes = Some::create($attributes);

        return $this;
    }

    /**
     * Specifies the Identification.
     *
     * Example: 1234
     */
    public function setId(string $id): self
    {
        $this->id = Some::create($id);

        return $this;
    }

    /**
     * Specifies packing Group.
     *
     * Example: Packing Group
     */
    public function setPackingGroup(string $packingGroup): self
    {
        $this->packingGroup = Some::create($packingGroup);

        return $this;
    }

    /**
     * Specifies Proper Shipping Name.
     *
     * Example: Proper Shipping Name
     */
    public function setProperShippingName(string $properShippingName): self
    {
        $this->properShippingName = Some::create($properShippingName);

        return $this;
    }

    /**
     * Specifies hazard class.
     *
     * Example: Hazard Class
     */
    public function setHazardClass(string $hazardClass): self
    {
        $this->hazardClass = Some::create($hazardClass);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ValidatedHazardousCommodityDescription
    {
        return new ValidatedHazardousCommodityDescription(
            $this->sequenceNumber,
            $this->packingInstructions,
            $this->subsidiaryClasses,
            $this->labelText,
            $this->tunnelRestrictionCode,
            $this->specialProvisions,
            $this->properShippingNameAndDescription,
            $this->technicalName,
            $this->symbols,
            $this->authorization,
            $this->attributes,
            $this->id,
            $this->packingGroup,
            $this->properShippingName,
            $this->hazardClass,
            $this->additionalProperties,
        );
    }
}
