<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

/**
 * Builds a {@see VariableHandlingCharges1}.
 */
final class VariableHandlingCharges1Builder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<Money1>           $variableHandlingCharge
     * @param Option<Money1>           $fixedVariableHandlingCharge
     * @param Option<Money1>           $percentVariableHandlingCharge
     * @param Option<Money1>           $totalCustomerCharge
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $variableHandlingCharge,
        private Option $fixedVariableHandlingCharge,
        private Option $percentVariableHandlingCharge,
        private Option $totalCustomerCharge,
        private array $additionalProperties,
    ) {
    }

    /**
     * Optional. The variable handling charge amount calculated based on the requested variable
     * handling charge detail.
     */
    public function setVariableHandlingCharge(Money1 $variableHandlingCharge): self
    {
        $this->variableHandlingCharge = Some::create($variableHandlingCharge);

        return $this;
    }

    /**
     * Optional. The variable handling charge amount calculated based on the requested variable
     * handling charge detail.
     */
    public function setFixedVariableHandlingCharge(Money1 $fixedVariableHandlingCharge): self
    {
        $this->fixedVariableHandlingCharge = Some::create($fixedVariableHandlingCharge);

        return $this;
    }

    /**
     * Optional. The variable handling charge amount calculated based on the requested variable
     * handling charge detail.
     */
    public function setPercentVariableHandlingCharge(Money1 $percentVariableHandlingCharge): self
    {
        $this->percentVariableHandlingCharge = Some::create($percentVariableHandlingCharge);

        return $this;
    }

    /**
     * Specifies the total customer assessed handling charges.
     *
     * Example: 445.54
     */
    public function setTotalCustomerCharge(Money1 $totalCustomerCharge): self
    {
        $this->totalCustomerCharge = Some::create($totalCustomerCharge);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): VariableHandlingCharges1
    {
        return new VariableHandlingCharges1(
            $this->variableHandlingCharge,
            $this->fixedVariableHandlingCharge,
            $this->percentVariableHandlingCharge,
            $this->totalCustomerCharge,
            $this->additionalProperties,
        );
    }
}
