<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_array;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class VariableHandlingChargeDetail implements SelfNormalizingModel
{
    /**
     * @param Option<VariableHandlingChargeDetailRateType|UnknownEnumValue<string>>         $rateType
     * @param Option<float>                                                                 $percentValue
     * @param Option<VariableHandlingChargeDetailRateLevelType|UnknownEnumValue<string>>    $rateLevelType
     * @param Option<VariableHandlingChargeDetailFixedValue>                                $fixedValue
     * @param Option<VariableHandlingChargeDetailRateElementBasis|UnknownEnumValue<string>> $rateElementBasis
     * @param array<int|string, mixed>                                                      $additionalProperties
     */
    public function __construct(
        private Option $rateType,
        private Option $percentValue,
        private Option $rateLevelType,
        private Option $fixedValue,
        private Option $rateElementBasis,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): VariableHandlingChargeDetailBuilder
    {
        return new VariableHandlingChargeDetailBuilder(
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The rate type indicates what type of rate request is being returned; account, preferred,
     * incentive, etc.
     *
     * Example: PREFERRED_CURRENCY
     *
     * @return Option<VariableHandlingChargeDetailRateType|UnknownEnumValue<string>>
     */
    public function getRateType(): Option
    {
        return $this->rateType;
    }

    /**
     * This is the variable handling percentage. If the percent value is mentioned as 10, it means
     * 10%(multiplier of 0.1).
     *
     * Example: 12.45
     *
     * @return Option<float>
     */
    public function getPercentValue(): Option
    {
        return $this->percentValue;
    }

    /**
     * indicates whether or not the rating is being done at the package level, or if the packages
     * are bundled together. At the package level, charges are applied based on the details of each
     * individual package. If they are bundled, one package is chosen as the parent and charges are
     * applied based on that one package.
     *
     * Example: INDIVIDUAL_PACKAGE_RATE
     *
     * @return Option<VariableHandlingChargeDetailRateLevelType|UnknownEnumValue<string>>
     */
    public function getRateLevelType(): Option
    {
        return $this->rateLevelType;
    }

    /**
     * This is to specify a fixed handling charge on the shipment. The element allows entry of 7
     * characters before the decimal and 2 characters following the decimal.
     *
     * Example: 5.00.
     *
     * @return Option<VariableHandlingChargeDetailFixedValue>
     */
    public function getFixedValue(): Option
    {
        return $this->fixedValue;
    }

    /**
     * Specify the charge type upon which the variable handling percentage amount is calculated.
     *
     * @return Option<VariableHandlingChargeDetailRateElementBasis|UnknownEnumValue<string>>
     */
    public function getRateElementBasis(): Option
    {
        return $this->rateElementBasis;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $rateType = None::create();
        $percentValue = None::create();
        $rateLevelType = None::create();
        $fixedValue = None::create();
        $rateElementBasis = None::create();
        if (array_key_exists('percentValue', $data) && is_int($data['percentValue'])) {
            $data['percentValue'] = (float) $data['percentValue'];
        }
        if (array_key_exists('rateType', $data) && $data['rateType'] !== null) {
            $rateTypeRaw = $data['rateType'];
            if (!is_string($rateTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rateType" must be string, got %s.', get_debug_type($rateTypeRaw)),
                );
            }
            $rateType = Some::create(
                VariableHandlingChargeDetailRateType::tryFrom($rateTypeRaw) ?? UnknownEnumValue::of($rateTypeRaw),
            );
        }
        if (array_key_exists('percentValue', $data) && $data['percentValue'] !== null) {
            $percentValueRaw = $data['percentValue'];
            if (!(is_float($percentValueRaw) || is_int($percentValueRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "percentValue" must be number, got %s.', get_debug_type($percentValueRaw)),
                );
            }
            $percentValue = Some::create((float) $percentValueRaw);
        }
        if (array_key_exists('rateLevelType', $data) && $data['rateLevelType'] !== null) {
            $rateLevelTypeRaw = $data['rateLevelType'];
            if (!is_string($rateLevelTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "rateLevelType" must be string, got %s.', get_debug_type($rateLevelTypeRaw)),
                );
            }
            $rateLevelType = Some::create(
                VariableHandlingChargeDetailRateLevelType::tryFrom($rateLevelTypeRaw)
                    ?? UnknownEnumValue::of($rateLevelTypeRaw),
            );
        }
        if (array_key_exists('fixedValue', $data) && $data['fixedValue'] !== null) {
            $fixedValueRaw = $data['fixedValue'];
            if (!is_array($fixedValueRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "fixedValue" must be object, got %s.', get_debug_type($fixedValueRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $fixedValueRawTyped */
            $fixedValueRawTyped = $fixedValueRaw;
            $fixedValue = Some::create(VariableHandlingChargeDetailFixedValue::fromArray($fixedValueRawTyped));
        }
        if (array_key_exists('rateElementBasis', $data) && $data['rateElementBasis'] !== null) {
            $rateElementBasisRaw = $data['rateElementBasis'];
            if (!is_string($rateElementBasisRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "rateElementBasis" must be string, got %s.',
                        get_debug_type($rateElementBasisRaw),
                    ),
                );
            }
            $rateElementBasis = Some::create(
                VariableHandlingChargeDetailRateElementBasis::tryFrom($rateElementBasisRaw)
                    ?? UnknownEnumValue::of($rateElementBasisRaw),
            );
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'rateType' => true,
                'percentValue' => true,
                'rateLevelType' => true,
                'fixedValue' => true,
                'rateElementBasis' => true,
            ],
        );

        return new self(
            $rateType,
            $percentValue,
            $rateLevelType,
            $fixedValue,
            $rateElementBasis,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $rateTypeOption = $this->rateType;
        if ($rateTypeOption->isDefined()) {
            $rateType = $rateTypeOption->get();
            $dataArray['rateType'] = $rateType->value;
        }
        $percentValueOption = $this->percentValue;
        if ($percentValueOption->isDefined()) {
            $percentValue = $percentValueOption->get();
            $dataArray['percentValue'] = $percentValue;
        }
        $rateLevelTypeOption = $this->rateLevelType;
        if ($rateLevelTypeOption->isDefined()) {
            $rateLevelType = $rateLevelTypeOption->get();
            $dataArray['rateLevelType'] = $rateLevelType->value;
        }
        $fixedValueOption = $this->fixedValue;
        if ($fixedValueOption->isDefined()) {
            $fixedValue = $fixedValueOption->get();
            $dataArray['fixedValue'] = $normalizationTarget->model($fixedValue);
        }
        $rateElementBasisOption = $this->rateElementBasis;
        if ($rateElementBasisOption->isDefined()) {
            $rateElementBasis = $rateElementBasisOption->get();
            $dataArray['rateElementBasis'] = $rateElementBasis->value;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): VariableHandlingChargeDetailBuilder
    {
        return new VariableHandlingChargeDetailBuilder(
            $this->rateType,
            $this->percentValue,
            $this->rateLevelType,
            $this->fixedValue,
            $this->rateElementBasis,
            $this->additionalProperties,
        );
    }
}
