<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Model;

use Override;
use Prefabcortex\FedexShipApi\Exception\MalformedDataException;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_int;
use function sprintf;

final readonly class Version implements SelfNormalizingModel
{
    /**
     * @param Option<int>              $major
     * @param Option<int>              $minor
     * @param Option<int>              $patch
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $major,
        private Option $minor,
        private Option $patch,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): VersionBuilder
    {
        return new VersionBuilder(None::create(), None::create(), None::create(), []);
    }

    /**
     * This version is incremented when significant changes are made to the API functionality. These
     * could be breaking changes and might require code-adjustments from clients. Accepts only
     * numbers.
     *
     * @return Option<int>
     */
    public function getMajor(): Option
    {
        return $this->major;
    }

    /**
     * This represents a backward-compatible bug fix or minor adjustment to an existing API
     * functionality. This is the second number in API versioning scheme. Accepts only numbers.
     *
     * @return Option<int>
     */
    public function getMinor(): Option
    {
        return $this->minor;
    }

    /**
     * This represents a backward-compatible bug fix or minor adjustment to an existing API
     * functionality. This is the third number in API versioning scheme. Accepts only numbers.
     *
     * @return Option<int>
     */
    public function getPatch(): Option
    {
        return $this->patch;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $major = None::create();
        $minor = None::create();
        $patch = None::create();
        if (array_key_exists('major', $data) && $data['major'] !== null) {
            $majorRaw = $data['major'];
            if (!is_int($majorRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "major" must be int, got %s.', get_debug_type($majorRaw)),
                );
            }
            $major = Some::create($majorRaw);
        }
        if (array_key_exists('minor', $data) && $data['minor'] !== null) {
            $minorRaw = $data['minor'];
            if (!is_int($minorRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "minor" must be int, got %s.', get_debug_type($minorRaw)),
                );
            }
            $minor = Some::create($minorRaw);
        }
        if (array_key_exists('patch', $data) && $data['patch'] !== null) {
            $patchRaw = $data['patch'];
            if (!is_int($patchRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "patch" must be int, got %s.', get_debug_type($patchRaw)),
                );
            }
            $patch = Some::create($patchRaw);
        }
        $additionalProperties = array_diff_key($data, ['major' => true, 'minor' => true, 'patch' => true]);

        return new self($major, $minor, $patch, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $majorOption = $this->major;
        if ($majorOption->isDefined()) {
            $major = $majorOption->get();
            $dataArray['major'] = $major;
        }
        $minorOption = $this->minor;
        if ($minorOption->isDefined()) {
            $minor = $minorOption->get();
            $dataArray['minor'] = $minor;
        }
        $patchOption = $this->patch;
        if ($patchOption->isDefined()) {
            $patch = $patchOption->get();
            $dataArray['patch'] = $patch;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): VersionBuilder
    {
        return new VersionBuilder($this->major, $this->minor, $this->patch, $this->additionalProperties);
    }
}
