<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Exception;

use Override;
use Prefabcortex\FedexShipApi\Http\ErrorMessage;
use Prefabcortex\FedexShipApi\Model\ErrorResponseVO500;
use Psr\Http\Message\ResponseInterface;

final class CreateShipmentInternalServerErrorException extends InternalServerErrorException
{
    public function __construct(
        private readonly ErrorResponseVO500 $errorResponseVO500,
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
    ) {
        parent::__construct(ErrorMessage::describe($rawResponse, 'Failure'));
    }

    public function getErrorResponseVO500(): ErrorResponseVO500
    {
        return $this->errorResponseVO500;
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }
}
