<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Parameter;

use Prefabcortex\FedexShipApi\Http\HeaderParameter;
use Prefabcortex\FedexShipApi\Http\HeaderParameters;
use Prefabcortex\FedexShipApi\Http\ScalarValue;
use Prefabcortex\FedexShipApi\Optional\None;
use Prefabcortex\FedexShipApi\Optional\Option;
use Prefabcortex\FedexShipApi\Optional\Some;
use SensitiveParameter;

final class ShipmentPackageValidateHeaderParameters
{
    /**
     * This element allows you to assign a unique identifier to your transaction. This element is
     * also returned in the reply and helps you match the request to the reply.
     *
     * @var Option<string>
     */
    private Option $xCustomerTransactionId;
    /**
     * This indicates the combination of language code and country code. <a
     * onclick='loadDocReference("locales")'>Click here to see Locales</a>.
     *
     * @var Option<string>
     */
    private Option $xLocale;

    /** @param string $authorization this indicates the authorization token for the input request */
    public function __construct(#[SensitiveParameter] private readonly string $authorization)
    {
        $this->xCustomerTransactionId = None::create();
        $this->xLocale = None::create();
    }

    public function getAuthorization(): string
    {
        return $this->authorization;
    }

    /** @return Option<string> */
    public function getXCustomerTransactionId(): Option
    {
        return $this->xCustomerTransactionId;
    }

    public function withXCustomerTransactionId(string $xCustomerTransactionId): self
    {
        $copy = clone $this;
        $copy->xCustomerTransactionId = Some::create($xCustomerTransactionId);

        return $copy;
    }

    /** @return Option<string> */
    public function getXLocale(): Option
    {
        return $this->xLocale;
    }

    public function withXLocale(string $xLocale): self
    {
        $copy = clone $this;
        $copy->xLocale = Some::create($xLocale);

        return $copy;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toHeaderParameters(): HeaderParameters
    {
        $parameters = [];
        $parameters[] = new HeaderParameter('authorization', new ScalarValue($this->authorization));
        if ($this->xCustomerTransactionId->isDefined()) {
            $parameters[] = new HeaderParameter(
                'x-customer-transaction-id',
                new ScalarValue($this->xCustomerTransactionId->get()),
            );
        }
        if ($this->xLocale->isDefined()) {
            $parameters[] = new HeaderParameter('x-locale', new ScalarValue($this->xLocale->get()));
        }

        return new HeaderParameters(...$parameters);
    }

    /**
     * What `print_r()` and `var_dump()` show of this object: the credential is redacted.
     *
     * `var_export()` and `serialize()` do not ask this method and still read the value.
     *
     * @return array<string, mixed>
     */
    public function __debugInfo(): array
    {
        return [
            'xCustomerTransactionId' => $this->xCustomerTransactionId,
            'xLocale' => $this->xLocale,
            'authorization' => '[redacted]',
        ];
    }
}
