<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi;

/**
 * The servers the API description names, for `ClientConfig::forServer()`.
 */
enum Server
{
    /**
     * `/`.
     *
     * Relative to wherever the API is served — see `ClientConfig::withOrigin()`.
     */
    case Root;
}
