<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\AdrLicenseDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;

/**
 * The rules a document for {@see AdrLicenseDetail} has to satisfy.
 */
final class AdrLicenseDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'licenseOrPermitDetail' => new Optional([
                    new NotNull(),
                    ...LicenseOrPermitDetailConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
