<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\AncillaryFeeAndTax;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see AncillaryFeeAndTax} has to satisfy.
 */
final class AncillaryFeeAndTaxConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'type' => new Optional([...AncillaryFeeAndTaxTypeConstraint::constraints()]),
                'description' => new Optional([new Type(['string']), new NotNull()]),
                'amount' => new Optional([new NotNull(), ...Money1Constraint::constraints()]),
            ], null, null, true),
        ];
    }
}
