<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\Commodity1;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Commodity1} has to satisfy.
 */
final class Commodity1Constraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'clearanceItemDetail' => new Optional([
                    new All([...ClearanceItemDetailConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'unitPrice' => new Optional([new NotNull(), ...MoneyConstraint::constraints()]),
                'additionalMeasures' => new Optional([
                    new All([...AdditionalMeasuresConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'numberOfPieces' => new Optional([new Type(['integer']), new NotNull()]),
                'quantity' => new Optional([new Type(['integer']), new NotNull()]),
                'quantityUnits' => new Optional([new Type(['string']), new NotNull()]),
                'customsValue' => new Optional([new NotNull(), ...CustomsMoneyConstraint::constraints()]),
                'countryOfManufacture' => new Optional([new Type(['string']), new NotNull()]),
                'cIMarksAndNumbers' => new Optional([new Type(['string']), new NotNull()]),
                'harmonizedCode' => new Optional([new Type(['string']), new NotNull()]),
                'description' => new Required([new Type(['string']), new NotNull()]),
                'name' => new Optional([new Type(['string']), new NotNull()]),
                'weight' => new Optional([new NotNull(), ...Weight4Constraint::constraints()]),
                'exportLicenseNumber' => new Optional([new Type(['string']), new NotNull()]),
                'exportLicenseExpirationDate' => new Optional([new Type(['string']), new NotNull()]),
                'partNumber' => new Optional([new Type(['string']), new NotNull()]),
                'purpose' => new Optional([...Commodity1PurposeConstraint::constraints()]),
                'usmcaDetail' => new Optional([new NotNull(), ...UsmcaDetailConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
