<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\FullSchemaVerifyShipment;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;

/**
 * The rules a document for {@see FullSchemaVerifyShipment} has to satisfy.
 */
final class FullSchemaVerifyShipmentConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'requestedShipment' => new Required([
                    new NotNull(),
                    ...RequestedShipmentVerifyConstraint::constraints(),
                ]),
                'accountNumber' => new Optional([new NotNull(), ...ShipperAccountNumberConstraint::constraints()]),
                'version' => new Optional([new NotNull(), ...VersionConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
