<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\HazardousCommodityDescription01ProcessingOptionsItem;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Type;

use function array_map;

/**
 * The rules a document for {@see HazardousCommodityDescription01ProcessingOptionsItem} has to
 * satisfy.
 */
final class HazardousCommodityDescription01ProcessingOptionsItemConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new Type(['string']),
            new Choice(
                null,
                array_map(static fn ($c) => $c->value, HazardousCommodityDescription01ProcessingOptionsItem::cases()),
            ),
            new NotNull(),
        ];
    }
}
