<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\LabelResponseVO;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see LabelResponseVO} has to satisfy.
 */
final class LabelResponseVOConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'contentKey' => new Optional([new Type(['string']), new NotNull()]),
                'copiesToPrint' => new Optional([new Type(['integer']), new NotNull()]),
                'contentType' => new Optional([...LabelResponseVOContentTypeConstraint::constraints()]),
                'trackingNumber' => new Optional([new Type(['string']), new NotNull()]),
                'docType' => new Optional([new Type(['string']), new NotNull()]),
                'alerts' => new Optional([
                    new All([...AlertConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'encodedLabel' => new Optional([new Type(['string']), new NotNull()]),
                'url' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
