<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\PackageRating;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see PackageRating} has to satisfy.
 */
final class PackageRatingConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'effectiveNetDiscount' => new Optional([new Type(['number']), new NotNull()]),
                'actualRateType' => new Optional([new Type(['string']), new NotNull()]),
                'packageRateDetails' => new Optional([
                    new All([...PackageRateDetailConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
