<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\PartyAddress2;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see PartyAddress2} has to satisfy.
 */
final class PartyAddress2Constraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'streetLines' => new Required([new All([new Type(['string'])]), new Type(['array']), new NotNull()]),
                'city' => new Required([new Length(null, null, 35), new Type(['string']), new NotNull()]),
                'stateOrProvinceCode' => new Optional([new Type(['string']), new NotNull()]),
                'postalCode' => new Optional([new Type(['string']), new NotNull()]),
                'countryCode' => new Required([new Type(['string']), new NotNull()]),
                'residential' => new Optional([new Type(['bool']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
