<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\ShippingDocumentDispositionDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;

/**
 * The rules a document for {@see ShippingDocumentDispositionDetail} has to satisfy.
 */
final class ShippingDocumentDispositionDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'eMailDetail' => new Optional([new NotNull(), ...ShippingDocumentEmailDetailConstraint::constraints()]),
                'dispositionType' => new Optional([
                    ...ShippingDocumentDispositionDetailDispositionTypeConstraint::constraints(),
                ]),
            ], null, null, true),
        ];
    }
}
