<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\SmartPostInfoDetail;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see SmartPostInfoDetail} has to satisfy.
 */
final class SmartPostInfoDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'ancillaryEndorsement' => new Optional([
                    ...SmartPostInfoDetailAncillaryEndorsementConstraint::constraints(),
                ]),
                'hubId' => new Required([new Type(['string']), new NotNull()]),
                'indicia' => new Required([...SmartPostInfoDetailIndiciaConstraint::constraints()]),
                'specialServices' => new Optional([...SmartPostInfoDetailSpecialServicesConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
