<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\UploadDocumentReferenceDetail1;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see UploadDocumentReferenceDetail1} has to satisfy.
 */
final class UploadDocumentReferenceDetail1Constraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'documentType' => new Optional([
                    ...UploadDocumentReferenceDetail1DocumentTypeConstraint::constraints(),
                ]),
                'documentReference' => new Optional([new Type(['string']), new NotNull()]),
                'description' => new Optional([new Type(['string']), new NotNull()]),
                'documentId' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
