<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\FedexShipApi\Validator;

use Override;
use Prefabcortex\FedexShipApi\Model\UsmcaCommercialInvoiceCertificationOfOriginDetail;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see UsmcaCommercialInvoiceCertificationOfOriginDetail} has to satisfy.
 */
final class UsmcaCommercialInvoiceCertificationOfOriginDetailConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'customerImageUsages' => new Optional([
                    new All([...CustomerImageUsageConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'documentFormat' => new Optional([new NotNull(), ...ShippingDocumentFormatConstraint::constraints()]),
                'certifierSpecification' => new Optional([
                    ...UsmcaCommercialInvoiceCertificationOfOriginDetailCertifierSpecificationConstraint::constraints(),
                ]),
                'importerSpecification' => new Optional([
                    ...UsmcaCommercialInvoiceCertificationOfOriginDetailImporterSpecificationConstraint::constraints(),
                ]),
                'producerSpecification' => new Optional([
                    ...UsmcaCommercialInvoiceCertificationOfOriginDetailProducerSpecificationConstraint::constraints(),
                ]),
                'producer' => new Optional([new NotNull(), ...Party3Constraint::constraints()]),
                'certifierJobTitle' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
